; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Feb 01 2018 17:48:48 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAGLCYK9DGZQF:
	dc.w DATAGLCYK9DGZQF_0-DATAGLCYK9DGZQF, DATAGLCYK9DGZQF_1-DATAGLCYK9DGZQF
	dc.w DATAGLCYK9DGZQF_2-DATAGLCYK9DGZQF, DATAGLCYK9DGZQF_3-DATAGLCYK9DGZQF
	dc.w DATAGLCYK9DGZQF_4-DATAGLCYK9DGZQF
DATAGLCYK9DGZQF_0: dc.b $3
	dc.b $F0, $B, $0, $0, $E8
	dc.b $F0, $B, $8, $0, $0
	dc.b $10, $1, $0, $38, $FC
DATAGLCYK9DGZQF_1: dc.b $2
	dc.b $F0, $F, $0, $C, $F0
	dc.b $10, $1, $0, $38, $FC
DATAGLCYK9DGZQF_2: dc.b $2
	dc.b $F0, $3, $0, $1C, $FC
	dc.b $10, $1, $8, $38, $FC
DATAGLCYK9DGZQF_3: dc.b $2
	dc.b $F0, $F, $8, $C, $F0
	dc.b $10, $1, $8, $38, $FC
DATAGLCYK9DGZQF_4: dc.b $3
	dc.b $F0, $B, $0, $20, $E8
	dc.b $F0, $B, $0, $2C, $0
	dc.b $10, $1, $0, $38, $FC
	even