; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jan 01 2020 15:27:02 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAXVUMENVNSKD:
	dc.w DATAXVUMENVNSKD_0-DATAXVUMENVNSKD, DATAXVUMENVNSKD_1-DATAXVUMENVNSKD
	dc.w DATAXVUMENVNSKD_2-DATAXVUMENVNSKD, DATAXVUMENVNSKD_3-DATAXVUMENVNSKD
	dc.w DATAXVUMENVNSKD_4-DATAXVUMENVNSKD, DATAXVUMENVNSKD_5-DATAXVUMENVNSKD
	dc.w DATAXVUMENVNSKD_6-DATAXVUMENVNSKD, DATAXVUMENVNSKD_7-DATAXVUMENVNSKD
DATAXVUMENVNSKD_0: dc.b $6
	dc.b $28, $5, $0, $0, $2E
	dc.b $28, $0, $0, $4, $3E
	dc.b $28, $5, $0, $5, $11
	dc.b $30, $0, $0, $9, $21
	dc.b $18, $F, $0, $A, $19
	dc.b $38, $E, $0, $1A, $19
DATAXVUMENVNSKD_1: dc.b $5
	dc.b $30, $1, $0, $26, $30
	dc.b $38, $0, $0, $28, $38
	dc.b $33, $5, $0, $29, $17
	dc.b $18, $F, $0, $A, $19
	dc.b $38, $E, $0, $1A, $19
DATAXVUMENVNSKD_2: dc.b $6
	dc.b $28, $5, $0, $0, $2E
	dc.b $28, $0, $0, $4, $3E
	dc.b $28, $5, $0, $5, $11
	dc.b $30, $0, $0, $9, $21
	dc.b $18, $F, $0, $A, $19
	dc.b $38, $E, $0, $1A, $19
DATAXVUMENVNSKD_3: dc.b $5
	dc.b $30, $1, $0, $26, $30
	dc.b $38, $0, $0, $28, $38
	dc.b $33, $5, $0, $29, $17
	dc.b $18, $F, $0, $A, $19
	dc.b $38, $E, $0, $1A, $19
DATAXVUMENVNSKD_4: dc.b $6
	dc.b $28, $5, $0, $0, $2E
	dc.b $28, $0, $0, $4, $3E
	dc.b $28, $5, $0, $5, $11
	dc.b $30, $0, $0, $9, $21
	dc.b $18, $F, $0, $A, $19
	dc.b $38, $E, $0, $1A, $19
DATAXVUMENVNSKD_5: dc.b $5
	dc.b $30, $1, $0, $26, $30
	dc.b $38, $0, $0, $28, $38
	dc.b $33, $5, $0, $29, $17
	dc.b $18, $F, $0, $A, $19
	dc.b $38, $E, $0, $1A, $19
DATAXVUMENVNSKD_6: dc.b $6
	dc.b $28, $5, $0, $0, $2E
	dc.b $28, $0, $0, $4, $3E
	dc.b $28, $5, $0, $5, $11
	dc.b $30, $0, $0, $9, $21
	dc.b $18, $F, $0, $A, $19
	dc.b $38, $E, $0, $1A, $19
DATAXVUMENVNSKD_7: dc.b $5
	dc.b $30, $1, $0, $26, $30
	dc.b $38, $0, $0, $28, $38
	dc.b $33, $5, $0, $29, $17
	dc.b $18, $F, $0, $A, $19
	dc.b $38, $E, $0, $1A, $19
	even