; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Feb 01 2018 13:15:58 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA257P0RAZDQ4:
	dc.w DATA257P0RAZDQ4_0-DATA257P0RAZDQ4, DATA257P0RAZDQ4_1-DATA257P0RAZDQ4
	dc.w DATA257P0RAZDQ4_2-DATA257P0RAZDQ4, DATA257P0RAZDQ4_3-DATA257P0RAZDQ4
	dc.w DATA257P0RAZDQ4_4-DATA257P0RAZDQ4, DATA257P0RAZDQ4_5-DATA257P0RAZDQ4
	dc.w DATA257P0RAZDQ4_6-DATA257P0RAZDQ4, DATA257P0RAZDQ4_7-DATA257P0RAZDQ4
	dc.w DATA257P0RAZDQ4_8-DATA257P0RAZDQ4, DATA257P0RAZDQ4_9-DATA257P0RAZDQ4
	dc.w DATA257P0RAZDQ4_A-DATA257P0RAZDQ4, DATA257P0RAZDQ4_B-DATA257P0RAZDQ4
DATA257P0RAZDQ4_0: dc.b $1
	dc.b $EF, $F, $0, $0, $F0
DATA257P0RAZDQ4_1: dc.b $2
	dc.b $F5, $5, $0, $10, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA257P0RAZDQ4_2: dc.b $2
	dc.b $F5, $5, $0, $14, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA257P0RAZDQ4_3: dc.b $2
	dc.b $F5, $5, $0, $18, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA257P0RAZDQ4_4: dc.b $2
	dc.b $F5, $5, $0, $1C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA257P0RAZDQ4_5: dc.b $2
	dc.b $F5, $5, $0, $24, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA257P0RAZDQ4_6: dc.b $2
	dc.b $F5, $5, $0, $28, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA257P0RAZDQ4_7: dc.b $2
	dc.b $F5, $5, $0, $2C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA257P0RAZDQ4_8: dc.b $2
	dc.b $F5, $5, $20, $30, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA257P0RAZDQ4_9: dc.b $2
	dc.b $F5, $5, $0, $34, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA257P0RAZDQ4_A: dc.b $2
	dc.b $F5, $5, $0, $20, $F8
	dc.b $EF, $F, $0, $0, $F0
DATA257P0RAZDQ4_B: dc.b $1
	dc.b $FF, $D, $0, $38, $F0
	even