; ================================================================================
; Sprite Mappings - generated by Flex 2 Wed Jan 01 2020 20:11:06 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAUZ1AC29YQVR:
	dc.w $0, DATAUZ1AC29YQVR_1-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_2-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_3-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_4-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_5-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_6-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_7-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_8-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_9-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_A-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_B-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_C-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_D-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_E-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_F-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_10-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_11-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_12-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_13-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_14-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_15-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_16-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_17-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_18-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_19-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_1A-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_1B-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_1C-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_1D-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_1E-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_1F-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_20-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_21-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_22-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_23-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_24-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_25-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_26-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_27-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_28-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_29-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_2A-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_2B-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_2C-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_2D-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_2E-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_2F-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_30-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_31-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_32-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_33-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_34-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_35-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_36-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_37-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_38-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_39-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_3A-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_3B-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_3C-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_3D-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_3E-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_3F-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_40-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_41-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_42-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_43-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_44-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_45-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_46-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_47-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_48-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_49-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_4A-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_4B-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_4C-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_4D-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_4E-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_4F-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_50-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_51-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_52-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_53-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_54-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_55-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_56-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_57-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_58-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_59-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_5A-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_5B-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_5C-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_5D-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_5E-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_5F-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_60-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_61-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_62-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_63-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_64-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_65-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_66-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_67-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_68-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_69-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_6A-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_6B-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_6C-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_6D-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_6E-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_6F-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_70-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_71-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_72-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_73-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_74-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_75-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_76-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_77-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_78-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_79-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_7A-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_7B-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_7C-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_7D-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_7E-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_7F-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_80-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_81-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_82-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_83-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_84-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_85-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_86-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_87-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_88-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_89-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_8A-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_8B-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_8C-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_8D-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_8E-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_8F-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_90-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_91-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_92-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_93-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_94-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_95-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_96-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_97-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_98-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_99-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_9A-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_9B-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_9C-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_9D-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_9E-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_9F-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_A0-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_A1-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_A2-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_A3-DATAUZ1AC29YQVR
	dc.w DATAUZ1AC29YQVR_A4-DATAUZ1AC29YQVR, DATAUZ1AC29YQVR_A5-DATAUZ1AC29YQVR
DATAUZ1AC29YQVR_1: dc.b $4
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $D, $0, $3, $F0
	dc.b $4, $8, $0, $B, $F0
	dc.b $C, $8, $0, $E, $F8
DATAUZ1AC29YQVR_2: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAUZ1AC29YQVR_3: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAUZ1AC29YQVR_4: dc.b $3
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $9, $0, $6, $F0
	dc.b $C, $8, $0, $C, $F8
DATAUZ1AC29YQVR_5: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $8, $0, $9, $F0
	dc.b $C, $8, $0, $C, $F8
DATAUZ1AC29YQVR_6: dc.b $4
	dc.b $EB, $D, $0, $0, $EC
	dc.b $FB, $9, $0, $8, $EC
	dc.b $FB, $6, $0, $E, $4
	dc.b $B, $4, $0, $14, $EC
DATAUZ1AC29YQVR_7: dc.b $2
	dc.b $EC, $D, $0, $0, $ED
	dc.b $FC, $E, $0, $8, $F5
DATAUZ1AC29YQVR_8: dc.b $2
	dc.b $ED, $9, $0, $0, $F3
	dc.b $FD, $A, $0, $6, $F3
DATAUZ1AC29YQVR_9: dc.b $4
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $9, $0, $6, $EC
	dc.b $FB, $6, $0, $C, $4
	dc.b $B, $4, $0, $12, $EC
DATAUZ1AC29YQVR_A: dc.b $2
	dc.b $EC, $9, $0, $0, $F3
	dc.b $FC, $E, $0, $6, $EB
DATAUZ1AC29YQVR_B: dc.b $3
	dc.b $ED, $D, $0, $0, $EC
	dc.b $FD, $C, $0, $8, $F4
	dc.b $5, $9, $0, $C, $F4
DATAUZ1AC29YQVR_C: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $6, $0, $6, $3
	dc.b $FB, $8, $0, $C, $EB
	dc.b $3, $9, $0, $F, $F3
	dc.b $13, $0, $0, $15, $FB
DATAUZ1AC29YQVR_D: dc.b $6
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $C, $0, $8, $EC
	dc.b $4, $9, $0, $C, $F4
	dc.b $FC, $5, $0, $12, $C
	dc.b $F4, $0, $0, $16, $14
DATAUZ1AC29YQVR_E: dc.b $4
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $D, $0, $8, $F5
	dc.b $D, $8, $0, $10, $FD
DATAUZ1AC29YQVR_F: dc.b $5
	dc.b $EB, $9, $0, $0, $EB
	dc.b $EB, $5, $0, $6, $3
	dc.b $FB, $D, $0, $A, $F3
	dc.b $B, $8, $0, $12, $F3
	dc.b $13, $4, $0, $15, $FB
DATAUZ1AC29YQVR_10: dc.b $4
	dc.b $EC, $9, $0, $0, $EC
	dc.b $EC, $1, $0, $6, $4
	dc.b $FC, $D, $0, $8, $F4
	dc.b $C, $8, $0, $10, $FC
DATAUZ1AC29YQVR_11: dc.b $5
	dc.b $ED, $9, $0, $0, $ED
	dc.b $ED, $1, $0, $6, $5
	dc.b $FD, $0, $0, $8, $ED
	dc.b $FD, $D, $0, $9, $F5
	dc.b $D, $8, $0, $11, $FD
DATAUZ1AC29YQVR_12: dc.b $4
	dc.b $F4, $7, $0, $0, $EB
	dc.b $EC, $9, $0, $8, $FB
	dc.b $FC, $4, $0, $E, $FB
	dc.b $4, $9, $0, $10, $FB
DATAUZ1AC29YQVR_13: dc.b $2
	dc.b $F4, $7, $0, $0, $EC
	dc.b $EC, $B, $0, $8, $FC
DATAUZ1AC29YQVR_14: dc.b $2
	dc.b $F4, $6, $0, $0, $ED
	dc.b $F4, $A, $0, $6, $FD
DATAUZ1AC29YQVR_15: dc.b $4
	dc.b $F4, $6, $0, $0, $EB
	dc.b $EC, $9, $0, $6, $FB
	dc.b $FC, $4, $0, $C, $FB
	dc.b $4, $9, $0, $E, $FB
DATAUZ1AC29YQVR_16: dc.b $2
	dc.b $F4, $6, $0, $0, $EC
	dc.b $F4, $B, $0, $6, $FC
DATAUZ1AC29YQVR_17: dc.b $3
	dc.b $F4, $7, $0, $0, $ED
	dc.b $EC, $0, $0, $8, $FD
	dc.b $F4, $A, $0, $9, $FD
DATAUZ1AC29YQVR_18: dc.b $6
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $4, $0, $6, $F3
	dc.b $F5, $4, $0, $8, $EB
	dc.b $F5, $A, $0, $A, $FB
	dc.b $D, $0, $0, $13, $FB
	dc.b $FD, $0, $0, $14, $13
DATAUZ1AC29YQVR_19: dc.b $6
	dc.b $FC, $6, $0, $0, $EC
	dc.b $E4, $8, $0, $6, $F4
	dc.b $EC, $4, $0, $9, $FC
	dc.b $F4, $4, $0, $B, $EC
	dc.b $F4, $A, $0, $D, $FC
	dc.b $C, $0, $0, $16, $FC
DATAUZ1AC29YQVR_1A: dc.b $4
	dc.b $FB, $6, $0, $0, $ED
	dc.b $F3, $4, $0, $6, $ED
	dc.b $EB, $A, $0, $8, $FD
	dc.b $3, $4, $0, $11, $FD
DATAUZ1AC29YQVR_1B: dc.b $5
	dc.b $FD, $6, $0, $0, $EB
	dc.b $ED, $8, $0, $6, $F3
	dc.b $F5, $4, $0, $9, $EB
	dc.b $F5, $D, $0, $B, $FB
	dc.b $5, $8, $0, $13, $FB
DATAUZ1AC29YQVR_1C: dc.b $4
	dc.b $FC, $6, $0, $0, $EC
	dc.b $F4, $4, $0, $6, $EC
	dc.b $EC, $A, $0, $8, $FC
	dc.b $4, $4, $0, $11, $FC
DATAUZ1AC29YQVR_1D: dc.b $5
	dc.b $FB, $6, $0, $0, $ED
	dc.b $EB, $A, $0, $6, $FD
	dc.b $F3, $4, $0, $F, $ED
	dc.b $3, $4, $0, $11, $FD
	dc.b $B, $0, $0, $13, $FD
DATAUZ1AC29YQVR_1E: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAUZ1AC29YQVR_1F: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAUZ1AC29YQVR_20: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAUZ1AC29YQVR_21: dc.b $2
	dc.b $EE, $9, $0, $0, $F4
	dc.b $FE, $E, $0, $6, $EC
DATAUZ1AC29YQVR_22: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATAUZ1AC29YQVR_23: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATAUZ1AC29YQVR_24: dc.b $4
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
	dc.b $FE, $0, $0, $14, $EE
DATAUZ1AC29YQVR_25: dc.b $3
	dc.b $EE, $9, $0, $0, $EE
	dc.b $EE, $1, $0, $6, $6
	dc.b $FE, $E, $0, $8, $F6
DATAUZ1AC29YQVR_26: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAUZ1AC29YQVR_27: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAUZ1AC29YQVR_28: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAUZ1AC29YQVR_29: dc.b $2
	dc.b $F4, $6, $0, $0, $EE
	dc.b $F4, $B, $0, $6, $FE
DATAUZ1AC29YQVR_2A: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATAUZ1AC29YQVR_2B: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAUZ1AC29YQVR_2C: dc.b $4
	dc.b $FA, $6, $0, $0, $EE
	dc.b $F2, $4, $0, $6, $EE
	dc.b $EA, $B, $0, $8, $FE
	dc.b $A, $0, $0, $14, $FE
DATAUZ1AC29YQVR_2D: dc.b $2
	dc.b $F2, $7, $0, $0, $EE
	dc.b $EA, $B, $0, $8, $FE
DATAUZ1AC29YQVR_2E: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAUZ1AC29YQVR_2F: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAUZ1AC29YQVR_30: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAUZ1AC29YQVR_31: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAUZ1AC29YQVR_32: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAUZ1AC29YQVR_33: dc.b $2
	dc.b $F4, $E, $0, $0, $EC
	dc.b $F4, $2, $0, $C, $C
DATAUZ1AC29YQVR_34: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAUZ1AC29YQVR_35: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAUZ1AC29YQVR_36: dc.b $1
	dc.b $F0, $F, $0, $0, $F0
DATAUZ1AC29YQVR_37: dc.b $2
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $E, $0, $6, $F0
DATAUZ1AC29YQVR_38: dc.b $4
	dc.b $ED, $9, $0, $0, $F0
	dc.b $FD, $D, $0, $6, $F0
	dc.b $D, $4, $0, $E, $0
	dc.b $5, $0, $0, $10, $E8
DATAUZ1AC29YQVR_39: dc.b $4
	dc.b $F4, $4, $0, $0, $0
	dc.b $FC, $D, $0, $2, $F8
	dc.b $C, $8, $0, $A, $F8
	dc.b $4, $0, $0, $D, $F0
DATAUZ1AC29YQVR_3A: dc.b $3
	dc.b $EC, $8, $8, $0, $E8
	dc.b $F4, $2, $8, $3, $0
	dc.b $F4, $F, $8, $6, $E0
DATAUZ1AC29YQVR_3B: dc.b $3
	dc.b $EC, $E, $8, $0, $E8
	dc.b $4, $D, $8, $C, $E0
	dc.b $C, $0, $18, $14, $0
DATAUZ1AC29YQVR_3C: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATAUZ1AC29YQVR_3D: dc.b $2
	dc.b $F4, $A, $0, $0, $E8
	dc.b $F4, $A, $8, $0, $0
DATAUZ1AC29YQVR_3E: dc.b $3
	dc.b $F4, $D, $0, $0, $E4
	dc.b $FC, $0, $0, $8, $4
	dc.b $4, $C, $0, $9, $EC
DATAUZ1AC29YQVR_3F: dc.b $3
	dc.b $F4, $D, $0, $0, $FC
	dc.b $FC, $5, $0, $8, $EC
	dc.b $4, $8, $0, $C, $FC
DATAUZ1AC29YQVR_40: dc.b $5
	dc.b $FD, $4, $0, $F, $F8
	dc.b $5, $0, $0, $11, $F8
	dc.b $EA, $B, $0, $0, $F0
	dc.b $A, $4, $0, $C, $F8
	dc.b $12, $0, $0, $E, $F8
DATAUZ1AC29YQVR_41: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATAUZ1AC29YQVR_42: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $0, $5, $0, $C, $8
	dc.b $F8, $0, $0, $10, $8
	dc.b $F0, $0, $0, $11, $F8
DATAUZ1AC29YQVR_43: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $F0, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATAUZ1AC29YQVR_44: dc.b $5
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $0, $9, $0, $B, $F4
	dc.b $10, $4, $0, $11, $F4
	dc.b $0, $0, $0, $13, $EC
DATAUZ1AC29YQVR_45: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAUZ1AC29YQVR_46: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAUZ1AC29YQVR_47: dc.b $2
	dc.b $ED, $A, $0, $0, $F3
	dc.b $5, $D, $0, $9, $EB
DATAUZ1AC29YQVR_48: dc.b $3
	dc.b $EC, $A, $0, $0, $F3
	dc.b $4, $8, $0, $9, $F3
	dc.b $C, $4, $0, $C, $F3
DATAUZ1AC29YQVR_49: dc.b $2
	dc.b $EC, $9, $0, $0, $F0
	dc.b $FC, $E, $0, $6, $F0
DATAUZ1AC29YQVR_4A: dc.b $3
	dc.b $EC, $A, $0, $0, $F0
	dc.b $4, $5, $0, $9, $F8
	dc.b $E4, $0, $0, $D, $F8
DATAUZ1AC29YQVR_4B: dc.b $3
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $B, $0, $A, $F4
DATAUZ1AC29YQVR_4C: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATAUZ1AC29YQVR_4D: dc.b $7
	dc.b $ED, $D, $0, $0, $F1
	dc.b $5, $5, $0, $8, $F1
	dc.b $DD, $9, $0, $C, $F9
	dc.b $FD, $4, $0, $12, $F9
	dc.b $5, $4, $0, $14, $1
	dc.b $D, $0, $0, $16, $9
	dc.b $ED, $0, $0, $17, $11
DATAUZ1AC29YQVR_4E: dc.b $2
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $F, $0, $3, $F0
DATAUZ1AC29YQVR_4F: dc.b $3
	dc.b $EC, $8, $0, $0, $F0
	dc.b $F4, $E, $0, $3, $F0
	dc.b $C, $8, $0, $F, $F8
DATAUZ1AC29YQVR_50: dc.b $1
	dc.b $F0, $B, $0, $0, $F4
DATAUZ1AC29YQVR_51: dc.b $1
	dc.b $F4, $6, $0, $0, $F8
DATAUZ1AC29YQVR_52: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
DATAUZ1AC29YQVR_53: dc.b $3
	dc.b $F4, $D, $8, $0, $E4
	dc.b $FC, $5, $8, $8, $4
	dc.b $4, $8, $8, $C, $EC
DATAUZ1AC29YQVR_54: dc.b $3
	dc.b $F4, $D, $8, $0, $FC
	dc.b $FC, $0, $8, $8, $F4
	dc.b $4, $C, $8, $9, $F4
DATAUZ1AC29YQVR_55: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F8, $1, $0, $C, $C
	dc.b $8, $C, $0, $E, $F4
DATAUZ1AC29YQVR_56: dc.b $3
	dc.b $EB, $9, $0, $0, $F4
	dc.b $FB, $E, $0, $6, $EC
	dc.b $3, $1, $0, $12, $C
DATAUZ1AC29YQVR_57: dc.b $2
	dc.b $F0, $F, $0, $0, $EC
	dc.b $F8, $2, $0, $10, $C
DATAUZ1AC29YQVR_58: dc.b $4
	dc.b $C, $8, $0, $0, $F3
	dc.b $4, $C, $0, $3, $F3
	dc.b $FC, $C, $0, $7, $F3
	dc.b $F4, $8, $0, $B, $FB
DATAUZ1AC29YQVR_59: dc.b $4
	dc.b $C, $8, $0, $0, $F3
	dc.b $4, $C, $0, $3, $F3
	dc.b $FC, $C, $0, $7, $F3
	dc.b $F4, $8, $0, $B, $FB
DATAUZ1AC29YQVR_5A: dc.b $4
	dc.b $C, $8, $0, $0, $F3
	dc.b $4, $C, $0, $3, $F3
	dc.b $FC, $C, $0, $7, $F3
	dc.b $F4, $8, $0, $B, $FB
DATAUZ1AC29YQVR_5B: dc.b $4
	dc.b $C, $8, $0, $0, $F3
	dc.b $4, $C, $0, $3, $F3
	dc.b $FC, $C, $0, $7, $F3
	dc.b $F4, $8, $0, $B, $FB
DATAUZ1AC29YQVR_5C: dc.b $4
	dc.b $C, $8, $0, $0, $F3
	dc.b $4, $C, $0, $3, $F3
	dc.b $FC, $C, $0, $7, $F3
	dc.b $F4, $8, $0, $B, $FB
DATAUZ1AC29YQVR_5D: dc.b $4
	dc.b $C, $8, $0, $0, $F3
	dc.b $4, $C, $0, $3, $F3
	dc.b $FC, $C, $0, $7, $F3
	dc.b $F4, $8, $0, $B, $FB
DATAUZ1AC29YQVR_5E: dc.b $7
	dc.b $B, $C, $0, $0, $EC
	dc.b $B, $0, $0, $4, $C
	dc.b $3, $C, $0, $5, $EC
	dc.b $3, $0, $0, $9, $C
	dc.b $FB, $C, $0, $A, $EC
	dc.b $FB, $0, $0, $E, $C
	dc.b $F3, $C, $0, $F, $F4
DATAUZ1AC29YQVR_5F: dc.b $7
	dc.b $B, $C, $0, $0, $EC
	dc.b $B, $0, $0, $4, $C
	dc.b $3, $C, $0, $5, $EC
	dc.b $3, $0, $0, $9, $C
	dc.b $FB, $C, $0, $A, $EC
	dc.b $FB, $0, $0, $E, $C
	dc.b $F3, $C, $0, $F, $F4
DATAUZ1AC29YQVR_60: dc.b $7
	dc.b $B, $C, $0, $0, $EC
	dc.b $B, $0, $0, $4, $C
	dc.b $3, $C, $0, $5, $EC
	dc.b $3, $0, $0, $9, $C
	dc.b $FB, $C, $0, $A, $EC
	dc.b $FB, $0, $0, $E, $C
	dc.b $F3, $C, $0, $F, $F4
DATAUZ1AC29YQVR_61: dc.b $6
	dc.b $B, $C, $0, $0, $F5
	dc.b $3, $C, $0, $4, $ED
	dc.b $3, $0, $0, $8, $D
	dc.b $FB, $C, $0, $9, $ED
	dc.b $FB, $0, $0, $D, $D
	dc.b $F3, $C, $0, $E, $F5
DATAUZ1AC29YQVR_62: dc.b $8
	dc.b $C, $8, $0, $0, $F0
	dc.b $4, $C, $0, $3, $F0
	dc.b $4, $0, $0, $7, $10
	dc.b $FC, $C, $0, $8, $F0
	dc.b $FC, $0, $0, $C, $10
	dc.b $F4, $C, $0, $D, $F0
	dc.b $F4, $0, $0, $11, $10
	dc.b $EC, $8, $0, $12, $F8
DATAUZ1AC29YQVR_63: dc.b $7
	dc.b $B, $C, $0, $0, $F0
	dc.b $3, $C, $0, $4, $F0
	dc.b $3, $0, $0, $8, $10
	dc.b $FB, $C, $0, $9, $F0
	dc.b $FB, $0, $0, $D, $10
	dc.b $F3, $C, $0, $E, $F0
	dc.b $EB, $C, $0, $12, $F0
DATAUZ1AC29YQVR_64: dc.b $9
	dc.b $E, $8, $0, $0, $F0
	dc.b $6, $C, $0, $3, $F0
	dc.b $6, $0, $0, $7, $10
	dc.b $FE, $C, $0, $8, $F0
	dc.b $FE, $0, $0, $C, $10
	dc.b $F6, $C, $0, $D, $F0
	dc.b $F6, $0, $0, $11, $10
	dc.b $EE, $C, $0, $12, $F0
	dc.b $E6, $0, $0, $16, $0
DATAUZ1AC29YQVR_65: dc.b $7
	dc.b $A, $C, $0, $0, $F0
	dc.b $2, $C, $0, $4, $F0
	dc.b $2, $0, $0, $8, $10
	dc.b $FA, $C, $0, $9, $F0
	dc.b $FA, $0, $0, $D, $10
	dc.b $F2, $C, $0, $E, $F0
	dc.b $EA, $8, $0, $12, $F8
DATAUZ1AC29YQVR_66: dc.b $5
	dc.b $7, $8, $0, $0, $F9
	dc.b $FF, $C, $0, $3, $F1
	dc.b $F7, $C, $0, $7, $F1
	dc.b $EF, $C, $0, $B, $F1
	dc.b $E7, $C, $0, $F, $F1
DATAUZ1AC29YQVR_67: dc.b $5
	dc.b $7, $8, $0, $0, $F8
	dc.b $FF, $C, $0, $3, $F0
	dc.b $F7, $C, $0, $7, $F0
	dc.b $EF, $C, $0, $B, $F0
	dc.b $E7, $C, $0, $F, $F0
DATAUZ1AC29YQVR_68: dc.b $5
	dc.b $7, $8, $0, $0, $F9
	dc.b $FF, $C, $0, $3, $F1
	dc.b $F7, $C, $0, $7, $F1
	dc.b $EF, $C, $0, $B, $F1
	dc.b $E7, $C, $0, $F, $F1
DATAUZ1AC29YQVR_69: dc.b $5
	dc.b $6, $4, $0, $0, $F8
	dc.b $FE, $C, $0, $2, $F0
	dc.b $F6, $C, $0, $6, $F0
	dc.b $EE, $C, $0, $A, $F0
	dc.b $E6, $C, $0, $E, $F0
DATAUZ1AC29YQVR_6A: dc.b $8
	dc.b $3, $C, $0, $0, $F0
	dc.b $3, $0, $0, $4, $10
	dc.b $FB, $C, $0, $5, $E8
	dc.b $FB, $4, $0, $9, $8
	dc.b $F3, $C, $0, $B, $E8
	dc.b $F3, $0, $0, $F, $8
	dc.b $EB, $C, $0, $10, $E8
	dc.b $E3, $8, $0, $14, $F0
DATAUZ1AC29YQVR_6B: dc.b $9
	dc.b $3, $C, $0, $0, $E8
	dc.b $3, $0, $0, $4, $8
	dc.b $FB, $C, $0, $5, $E8
	dc.b $FB, $0, $0, $9, $8
	dc.b $F3, $C, $0, $A, $E8
	dc.b $F3, $0, $0, $E, $8
	dc.b $EB, $C, $0, $F, $E8
	dc.b $EB, $0, $0, $13, $8
	dc.b $E3, $4, $0, $14, $F8
DATAUZ1AC29YQVR_6C: dc.b $9
	dc.b $3, $C, $0, $0, $F0
	dc.b $3, $0, $0, $4, $10
	dc.b $FB, $C, $0, $5, $E8
	dc.b $FB, $4, $0, $9, $8
	dc.b $F3, $C, $0, $B, $E8
	dc.b $F3, $0, $0, $F, $8
	dc.b $EB, $C, $0, $10, $E8
	dc.b $EB, $0, $0, $14, $8
	dc.b $E3, $8, $0, $15, $F0
DATAUZ1AC29YQVR_6D: dc.b $9
	dc.b $3, $C, $0, $0, $E8
	dc.b $3, $0, $0, $4, $8
	dc.b $FB, $C, $0, $5, $E8
	dc.b $FB, $0, $0, $9, $8
	dc.b $F3, $C, $0, $A, $E8
	dc.b $F3, $0, $0, $E, $8
	dc.b $EB, $C, $0, $F, $E8
	dc.b $EB, $0, $0, $13, $8
	dc.b $E3, $4, $0, $14, $F8
DATAUZ1AC29YQVR_6E: dc.b $2
	dc.b $EE, $E, $0, $0, $ED
	dc.b $6, $9, $0, $C, $F5
DATAUZ1AC29YQVR_6F: dc.b $1
	dc.b $F4, $B, $0, $0, $F6
DATAUZ1AC29YQVR_70: dc.b $6
	dc.b $EB, $5, $0, $0, $F1
	dc.b $FB, $0, $0, $4, $F9
	dc.b $EA, $B, $0, $5, $F0
	dc.b $A, $4, $0, $11, $F8
	dc.b $12, $0, $0, $13, $F8
	dc.b $EC, $1, $0, $14, $1
DATAUZ1AC29YQVR_71: dc.b $5
	dc.b $F0, $5, $0, $0, $F1
	dc.b $EA, $B, $0, $4, $F0
	dc.b $A, $4, $0, $10, $F8
	dc.b $12, $0, $0, $12, $F8
	dc.b $F2, $1, $0, $13, $1
DATAUZ1AC29YQVR_72: dc.b $5
	dc.b $FB, $4, $0, $0, $F0
	dc.b $EA, $B, $0, $2, $F0
	dc.b $A, $4, $0, $E, $F8
	dc.b $12, $0, $0, $10, $F8
	dc.b $FB, $4, $0, $11, $4
DATAUZ1AC29YQVR_73: dc.b $6
	dc.b $1, $4, $0, $0, $EF
	dc.b $F9, $0, $0, $2, $F7
	dc.b $EA, $B, $0, $3, $F0
	dc.b $A, $4, $0, $F, $F8
	dc.b $12, $0, $0, $11, $F8
	dc.b $1, $4, $0, $12, $0
DATAUZ1AC29YQVR_74: dc.b $5
	dc.b $FD, $1, $0, $0, $F6
	dc.b $EA, $B, $0, $2, $F0
	dc.b $A, $4, $0, $E, $F8
	dc.b $12, $0, $0, $10, $F8
	dc.b $1, $1, $0, $11, $3
DATAUZ1AC29YQVR_75: dc.b $3
	dc.b $EA, $B, $0, $0, $F0
	dc.b $A, $4, $0, $C, $F8
	dc.b $12, $0, $0, $E, $F8
DATAUZ1AC29YQVR_76: dc.b $2
	dc.b $F4, $5, $0, $0, $F8
	dc.b $4, $0, $0, $4, $0
DATAUZ1AC29YQVR_77: dc.b $1
	dc.b $F8, $5, $0, $0, $F8
DATAUZ1AC29YQVR_78: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
DATAUZ1AC29YQVR_79: dc.b $2
	dc.b $0, $4, $0, $0, $F8
	dc.b $F8, $0, $0, $2, $0
DATAUZ1AC29YQVR_7A: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
DATAUZ1AC29YQVR_7B: dc.b $1
	dc.b $FC, $4, $0, $0, $F8
DATAUZ1AC29YQVR_7C: dc.b $1
	dc.b $F8, $1, $0, $0, $FC
DATAUZ1AC29YQVR_7D: dc.b $1
	dc.b $FC, $4, $0, $0, $F8
DATAUZ1AC29YQVR_7E: dc.b $1
	dc.b $FC, $4, $0, $0, $F8
DATAUZ1AC29YQVR_7F: dc.b $2
	dc.b $F8, $4, $0, $0, $F8
	dc.b $0, $0, $0, $2, $F8
DATAUZ1AC29YQVR_80: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $E8, $1, $0, $8, $C
	dc.b $F8, $9, $0, $A, $F4
	dc.b $8, $C, $0, $10, $F4
	dc.b $10, $0, $0, $14, $F4
DATAUZ1AC29YQVR_81: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATAUZ1AC29YQVR_82: dc.b $2
	dc.b $ED, $B, $0, $0, $F3
	dc.b $D, $C, $0, $C, $F3
DATAUZ1AC29YQVR_83: dc.b $3
	dc.b $ED, $B, $0, $0, $F1
	dc.b $D, $C, $0, $C, $F1
	dc.b $FD, $1, $0, $10, $9
DATAUZ1AC29YQVR_84: dc.b $5
	dc.b $FD, $C, $0, $0, $E9
	dc.b $ED, $9, $0, $4, $F1
	dc.b $D, $C, $0, $A, $F1
	dc.b $5, $4, $0, $E, $F9
	dc.b $FD, $0, $0, $10, $9
DATAUZ1AC29YQVR_85: dc.b $4
	dc.b $F6, $D, $0, $0, $EE
	dc.b $EE, $8, $0, $8, $F6
	dc.b $6, $5, $0, $B, $F6
	dc.b $E, $0, $0, $F, $6
DATAUZ1AC29YQVR_86: dc.b $3
	dc.b $ED, $A, $0, $0, $F1
	dc.b $D, $C, $0, $9, $F1
	dc.b $5, $4, $0, $D, $F9
DATAUZ1AC29YQVR_87: dc.b $4
	dc.b $ED, $A, $0, $0, $F2
	dc.b $D, $C, $0, $9, $F2
	dc.b $5, $8, $0, $D, $FA
	dc.b $FD, $0, $0, $10, $A
DATAUZ1AC29YQVR_88: dc.b $3
	dc.b $ED, $B, $0, $0, $F4
	dc.b $D, $8, $0, $C, $F4
	dc.b $FD, $1, $0, $F, $C
DATAUZ1AC29YQVR_89: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $8, $0, $C, $F4
DATAUZ1AC29YQVR_8A: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $C, $0, $C, $F4
DATAUZ1AC29YQVR_8B: dc.b $2
	dc.b $ED, $B, $0, $0, $F4
	dc.b $D, $C, $0, $C, $F4
DATAUZ1AC29YQVR_8C: dc.b $2
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $C, $0, $C, $F4
DATAUZ1AC29YQVR_8D: dc.b $2
	dc.b $ED, $D, $0, $0, $EF
	dc.b $FD, $A, $0, $8, $F7
DATAUZ1AC29YQVR_8E: dc.b $2
	dc.b $ED, $B, $0, $0, $F8
	dc.b $D, $4, $0, $C, $0
DATAUZ1AC29YQVR_8F: dc.b $3
	dc.b $ED, $B, $0, $0, $F8
	dc.b $D, $8, $0, $C, $F8
	dc.b $5, $0, $0, $F, $10
DATAUZ1AC29YQVR_90: dc.b $3
	dc.b $ED, $B, $0, $0, $F8
	dc.b $D, $8, $0, $C, $F8
	dc.b $FD, $1, $0, $F, $10
DATAUZ1AC29YQVR_91: dc.b $3
	dc.b $EC, $A, $0, $0, $F7
	dc.b $C, $C, $0, $9, $F7
	dc.b $4, $8, $0, $D, $FF
DATAUZ1AC29YQVR_92: dc.b $3
	dc.b $ED, $A, $0, $0, $F6
	dc.b $D, $C, $0, $9, $F6
	dc.b $5, $4, $0, $D, $FE
DATAUZ1AC29YQVR_93: dc.b $2
	dc.b $ED, $B, $0, $0, $F9
	dc.b $D, $8, $0, $C, $F9
DATAUZ1AC29YQVR_94: dc.b $3
	dc.b $EC, $B, $0, $0, $F9
	dc.b $C, $8, $0, $C, $F9
	dc.b $FC, $0, $0, $F, $11
DATAUZ1AC29YQVR_95: dc.b $2
	dc.b $5, $D, $0, $0, $F1
	dc.b $ED, $A, $0, $8, $F9
DATAUZ1AC29YQVR_96: dc.b $2
	dc.b $ED, $B, $0, $0, $F8
	dc.b $D, $8, $0, $C, $F8
DATAUZ1AC29YQVR_97: dc.b $2
	dc.b $ED, $B, $0, $0, $FA
	dc.b $D, $8, $0, $C, $FA
DATAUZ1AC29YQVR_98: dc.b $2
	dc.b $ED, $B, $0, $0, $F8
	dc.b $D, $8, $0, $C, $F8
DATAUZ1AC29YQVR_99: dc.b $4
	dc.b $EF, $D, $0, $0, $F4
	dc.b $E7, $4, $0, $8, $FC
	dc.b $FF, $6, $0, $A, $FC
	dc.b $F, $0, $0, $10, $C
DATAUZ1AC29YQVR_9A: dc.b $4
	dc.b $EC, $B, $0, $0, $F7
	dc.b $C, $C, $0, $C, $F7
	dc.b $E4, $0, $0, $10, $FF
	dc.b $EC, $1, $0, $11, $F
DATAUZ1AC29YQVR_9B: dc.b $3
	dc.b $F4, $C, $0, $0, $F0
	dc.b $EC, $8, $0, $4, $F8
	dc.b $FC, $A, $0, $7, $F8
DATAUZ1AC29YQVR_9C: dc.b $3
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $4, $0, $C, $FC
	dc.b $FC, $0, $0, $E, $C
DATAUZ1AC29YQVR_9D: dc.b $4
	dc.b $EC, $D, $0, $0, $F0
	dc.b $FC, $6, $0, $8, $F8
	dc.b $FC, $4, $0, $E, $8
	dc.b $C, $0, $0, $10, $8
DATAUZ1AC29YQVR_9E: dc.b $4
	dc.b $EC, $D, $0, $0, $F0
	dc.b $FC, $6, $0, $8, $F8
	dc.b $FC, $4, $0, $E, $8
	dc.b $C, $0, $0, $10, $8
DATAUZ1AC29YQVR_9F: dc.b $4
	dc.b $EC, $D, $0, $0, $F2
	dc.b $FC, $6, $0, $8, $FA
	dc.b $FC, $4, $0, $E, $A
	dc.b $C, $0, $0, $10, $A
DATAUZ1AC29YQVR_A0: dc.b $3
	dc.b $EC, $D, $0, $0, $F4
	dc.b $FC, $A, $0, $8, $FC
	dc.b $FC, $0, $0, $11, $14
DATAUZ1AC29YQVR_A1: dc.b $4
	dc.b $EC, $D, $0, $0, $F6
	dc.b $FC, $6, $0, $8, $FE
	dc.b $FC, $4, $0, $E, $E
	dc.b $C, $0, $0, $10, $E
DATAUZ1AC29YQVR_A2: dc.b $3
	dc.b $ED, $B, $0, $0, $FB
	dc.b $D, $4, $0, $C, $3
	dc.b $FD, $1, $0, $E, $13
DATAUZ1AC29YQVR_A3: dc.b $4
	dc.b $ED, $A, $0, $0, $F6
	dc.b $5, $5, $0, $9, $FE
	dc.b $F5, $1, $0, $D, $E
	dc.b $D, $0, $0, $F, $E
DATAUZ1AC29YQVR_A4: dc.b $2
	dc.b $EE, $E, $0, $0, $F3
	dc.b $6, $9, $0, $C, $FB
DATAUZ1AC29YQVR_A5: dc.b $4
	dc.b $ED, $B, $0, $0, $F7
	dc.b $F5, $0, $0, $C, $EF
	dc.b $F5, $0, $0, $D, $F
	dc.b $D, $C, $0, $E, $F7
	even