; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Nov 28 2019 14:42:10 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA6F90BNPS814:
	dc.w DATA6F90BNPS814_0-DATA6F90BNPS814
DATA6F90BNPS814_0: dc.b $3
	dc.b $E5, $C, $0, $0, $EC
	dc.b $ED, $C, $0, $4, $EC
	dc.b $F5, $C, $0, $8, $EC
	even