; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Dec 01 2019 21:58:29 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAXGV1PBH8OUG:
	dc.w DATAXGV1PBH8OUG_0-DATAXGV1PBH8OUG, DATAXGV1PBH8OUG_1-DATAXGV1PBH8OUG
	dc.w DATAXGV1PBH8OUG_2-DATAXGV1PBH8OUG, DATAXGV1PBH8OUG_3-DATAXGV1PBH8OUG
	dc.w DATAXGV1PBH8OUG_4-DATAXGV1PBH8OUG, DATAXGV1PBH8OUG_5-DATAXGV1PBH8OUG
	dc.w DATAXGV1PBH8OUG_6-DATAXGV1PBH8OUG, DATAXGV1PBH8OUG_7-DATAXGV1PBH8OUG
	dc.w DATAXGV1PBH8OUG_8-DATAXGV1PBH8OUG, DATAXGV1PBH8OUG_9-DATAXGV1PBH8OUG
	dc.w DATAXGV1PBH8OUG_A-DATAXGV1PBH8OUG, DATAXGV1PBH8OUG_B-DATAXGV1PBH8OUG
	dc.w DATAXGV1PBH8OUG_C-DATAXGV1PBH8OUG
DATAXGV1PBH8OUG_0: dc.b $7
	dc.b $EC, $1, $20, $0, $E4
	dc.b $EC, $5, $20, $2, $C
	dc.b $14, $C, $20, $6, $EC
	dc.b $14, $0, $20, $A, $C
	dc.b $FC, $E, $20, $B, $E4
	dc.b $FC, $A, $20, $17, $4
	dc.b $E4, $0, $20, $20, $C
DATAXGV1PBH8OUG_1: dc.b $2
	dc.b $EC, $D, $20, $21, $EC
	dc.b $DC, $D, $20, $29, $EC
DATAXGV1PBH8OUG_2: dc.b $2
	dc.b $EC, $D, $20, $21, $EC
	dc.b $DC, $D, $20, $29, $EC
DATAXGV1PBH8OUG_3: dc.b $2
	dc.b $EC, $D, $20, $21, $EC
	dc.b $DC, $D, $20, $29, $EC
DATAXGV1PBH8OUG_4: dc.b $2
	dc.b $EC, $D, $20, $21, $EC
	dc.b $DC, $D, $20, $29, $EC
DATAXGV1PBH8OUG_5: dc.b $3
	dc.b $EC, $4, $20, $31, $EC
	dc.b $EC, $D, $20, $21, $EC
	dc.b $DC, $D, $20, $29, $EC
DATAXGV1PBH8OUG_6: dc.b $3
	dc.b $E4, $4, $0, $33, $C
	dc.b $EC, $D, $20, $21, $EC
	dc.b $DC, $D, $20, $29, $EC
DATAXGV1PBH8OUG_7: dc.b $3
	dc.b $EC, $4, $20, $31, $EC
	dc.b $EC, $D, $20, $21, $EC
	dc.b $DC, $D, $20, $29, $EC
DATAXGV1PBH8OUG_8: dc.b $1
	dc.b $4, $4, $0, $35, $18
DATAXGV1PBH8OUG_9: dc.b $0
DATAXGV1PBH8OUG_A: dc.b $0
DATAXGV1PBH8OUG_B: dc.b $2
	dc.b $0, $8, $1, $2A, $22
	dc.b $8, $8, $11, $2A, $22
DATAXGV1PBH8OUG_C: dc.b $2
	dc.b $F8, $B, $1, $2D, $22
	dc.b $0, $1, $1, $39, $3A
	even