; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Nov 23 2019 23:18:34 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATATVK71W827Q8:
	dc.w DATATVK71W827Q8_0-DATATVK71W827Q8, DATATVK71W827Q8_1-DATATVK71W827Q8
DATATVK71W827Q8_0: dc.b $6
	dc.b $E4, $8, $0, $20, $F4
	dc.b $EC, $D, $0, $23, $E4
	dc.b $EC, $9, $0, $2B, $4
	dc.b $FC, $5, $20, $3A, $E4
	dc.b $FC, $E, $20, $3E, $4
	dc.b $14, $4, $20, $4A, $4
DATATVK71W827Q8_1: dc.b $6
	dc.b $E4, $A, $0, $31, $F4
	dc.b $EC, $5, $0, $23, $E4
	dc.b $EC, $9, $0, $2B, $4
	dc.b $FC, $5, $20, $3A, $E4
	dc.b $FC, $E, $20, $3E, $4
	dc.b $14, $4, $20, $4A, $4
	even