; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Nov 14 2019 21:27:53 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAFDCC0IJS4CF:
	dc.w DATAFDCC0IJS4CF_0-DATAFDCC0IJS4CF
DATAFDCC0IJS4CF_0: dc.b $7
	dc.b $F4, $5, $0, $0, $E7
	dc.b $F4, $5, $0, $4, $F7
	dc.b $F4, $5, $0, $8, $7
	dc.b $F4, $5, $0, $C, $17
	dc.b $F4, $5, $0, $10, $27
	dc.b $F4, $5, $0, $14, $37
	dc.b $F4, $5, $0, $18, $47
	even