; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Nov 16 2019 11:25:53 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATARTRVNI24H7E:
	dc.w DATARTRVNI24H7E_0-DATARTRVNI24H7E, DATARTRVNI24H7E_1-DATARTRVNI24H7E
	dc.w DATARTRVNI24H7E_2-DATARTRVNI24H7E
DATARTRVNI24H7E_0: dc.b $2
	dc.b $F2, $4, $0, $0, $F8
	dc.b $FA, $C, $0, $2, $F0
DATARTRVNI24H7E_1: dc.b $2
	dc.b $E2, $0, $0, $6, $F8
	dc.b $EA, $E, $0, $7, $F0
DATARTRVNI24H7E_2: dc.b $1
	dc.b $E2, $F, $0, $13, $F0
	even