; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Nov 15 2019 18:18:31 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAOLY02KB7XVM:
	dc.w DATAOLY02KB7XVM_0-DATAOLY02KB7XVM, DATAOLY02KB7XVM_1-DATAOLY02KB7XVM
	dc.w DATAOLY02KB7XVM_2-DATAOLY02KB7XVM, DATAOLY02KB7XVM_3-DATAOLY02KB7XVM
	dc.w DATAOLY02KB7XVM_4-DATAOLY02KB7XVM
DATAOLY02KB7XVM_0: dc.b $3
	dc.b $F0, $B, $0, $0, $E8
	dc.b $F0, $B, $8, $0, $0
	dc.b $10, $1, $0, $38, $FC
DATAOLY02KB7XVM_1: dc.b $2
	dc.b $F0, $F, $0, $C, $F0
	dc.b $10, $1, $0, $38, $FC
DATAOLY02KB7XVM_2: dc.b $2
	dc.b $F0, $3, $0, $1C, $FC
	dc.b $10, $1, $8, $38, $FC
DATAOLY02KB7XVM_3: dc.b $2
	dc.b $F0, $F, $8, $C, $F0
	dc.b $10, $1, $8, $38, $FC
DATAOLY02KB7XVM_4: dc.b $3
	dc.b $F0, $B, $0, $20, $E8
	dc.b $F0, $B, $0, $2C, $0
	dc.b $10, $1, $0, $38, $FC
	even