; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Nov 30 2019 01:50:21 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATARNSUWCJ06S:
	dc.w DATARNSUWCJ06S_0-DATARNSUWCJ06S, DATARNSUWCJ06S_1-DATARNSUWCJ06S
	dc.w DATARNSUWCJ06S_2-DATARNSUWCJ06S, DATARNSUWCJ06S_3-DATARNSUWCJ06S
	dc.w DATARNSUWCJ06S_4-DATARNSUWCJ06S, DATARNSUWCJ06S_5-DATARNSUWCJ06S
	dc.w DATARNSUWCJ06S_6-DATARNSUWCJ06S, DATARNSUWCJ06S_7-DATARNSUWCJ06S
	dc.w DATARNSUWCJ06S_8-DATARNSUWCJ06S, DATARNSUWCJ06S_9-DATARNSUWCJ06S
	dc.w DATARNSUWCJ06S_A-DATARNSUWCJ06S, DATARNSUWCJ06S_B-DATARNSUWCJ06S
DATARNSUWCJ06S_0: dc.b $1
	dc.b $EF, $F, $0, $0, $F0
DATARNSUWCJ06S_1: dc.b $2
	dc.b $F3, $5, $0, $10, $F8
	dc.b $EF, $F, $0, $0, $F0
DATARNSUWCJ06S_2: dc.b $2
	dc.b $F3, $5, $0, $14, $F8
	dc.b $EF, $F, $0, $0, $F0
DATARNSUWCJ06S_3: dc.b $2
	dc.b $F3, $5, $0, $18, $F8
	dc.b $EF, $F, $0, $0, $F0
DATARNSUWCJ06S_4: dc.b $2
	dc.b $F3, $5, $0, $1C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATARNSUWCJ06S_5: dc.b $2
	dc.b $F3, $5, $0, $24, $F8
	dc.b $EF, $F, $0, $0, $F0
DATARNSUWCJ06S_6: dc.b $2
	dc.b $F3, $5, $0, $28, $F8
	dc.b $EF, $F, $0, $0, $F0
DATARNSUWCJ06S_7: dc.b $2
	dc.b $F3, $5, $0, $2C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATARNSUWCJ06S_8: dc.b $2
	dc.b $F3, $5, $20, $30, $F8
	dc.b $EF, $F, $0, $0, $F0
DATARNSUWCJ06S_9: dc.b $2
	dc.b $F3, $5, $0, $34, $F8
	dc.b $EF, $F, $0, $0, $F0
DATARNSUWCJ06S_A: dc.b $2
	dc.b $F3, $5, $0, $20, $F8
	dc.b $EF, $F, $0, $0, $F0
DATARNSUWCJ06S_B: dc.b $1
	dc.b $FF, $D, $0, $38, $F0
	even