; ================================================================================
; Sprite Mappings - generated by Flex 2 Thu Nov 14 2019 00:27:31 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAJFTV701N8CC:
	dc.w DATAJFTV701N8CC_0-DATAJFTV701N8CC, DATAJFTV701N8CC_1-DATAJFTV701N8CC
	dc.w DATAJFTV701N8CC_2-DATAJFTV701N8CC, DATAJFTV701N8CC_3-DATAJFTV701N8CC
	dc.w DATAJFTV701N8CC_4-DATAJFTV701N8CC, DATAJFTV701N8CC_5-DATAJFTV701N8CC
	dc.w DATAJFTV701N8CC_6-DATAJFTV701N8CC, DATAJFTV701N8CC_7-DATAJFTV701N8CC
DATAJFTV701N8CC_0: dc.b $1
	dc.b $F8, $5, $0, $0, $F8
DATAJFTV701N8CC_1: dc.b $1
	dc.b $F8, $5, $0, $4, $F8
DATAJFTV701N8CC_2: dc.b $1
	dc.b $F8, $1, $0, $8, $FC
DATAJFTV701N8CC_3: dc.b $1
	dc.b $F8, $5, $8, $4, $F8
DATAJFTV701N8CC_4: dc.b $1
	dc.b $F8, $5, $0, $A, $F8
DATAJFTV701N8CC_5: dc.b $1
	dc.b $F8, $5, $18, $A, $F8
DATAJFTV701N8CC_6: dc.b $1
	dc.b $F8, $5, $8, $A, $F8
DATAJFTV701N8CC_7: dc.b $1
	dc.b $F8, $5, $10, $A, $F8
	even