; ================================================================================
; Sprite Mappings - generated by Flex 2 Mon Nov 18 2019 20:10:14 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATACSU5WSBAP0J:
	dc.w DATACSU5WSBAP0J_0-DATACSU5WSBAP0J, DATACSU5WSBAP0J_1-DATACSU5WSBAP0J
	dc.w DATACSU5WSBAP0J_2-DATACSU5WSBAP0J, DATACSU5WSBAP0J_3-DATACSU5WSBAP0J
DATACSU5WSBAP0J_0: dc.b $A
	dc.b $80, $D, $A0, $0, $0
	dc.b $80, $D, $A0, $18, $20
	dc.b $80, $D, $80, $20, $40
	dc.b $90, $D, $A0, $10, $0
	dc.b $90, $D, $80, $28, $28
	dc.b $A0, $D, $A0, $8, $0
	dc.b $A0, $1, $A0, $0, $20
	dc.b $A0, $9, $80, $30, $30
	dc.b $40, $5, $81, $A, $0
	dc.b $40, $D, $A1, $E, $10
DATACSU5WSBAP0J_1: dc.b $A
	dc.b $80, $D, $A0, $0, $0
	dc.b $80, $D, $A0, $18, $20
	dc.b $80, $D, $80, $20, $40
	dc.b $90, $D, $A0, $10, $0
	dc.b $90, $D, $80, $28, $28
	dc.b $A0, $D, $80, $8, $0
	dc.b $A0, $1, $80, $0, $20
	dc.b $A0, $9, $80, $30, $30
	dc.b $40, $5, $81, $A, $0
	dc.b $40, $D, $A1, $E, $10
DATACSU5WSBAP0J_2: dc.b $A
	dc.b $80, $D, $A0, $0, $0
	dc.b $80, $D, $A0, $18, $20
	dc.b $80, $D, $80, $20, $40
	dc.b $90, $D, $80, $10, $0
	dc.b $90, $D, $80, $28, $28
	dc.b $A0, $D, $A0, $8, $0
	dc.b $A0, $1, $A0, $0, $20
	dc.b $A0, $9, $80, $30, $30
	dc.b $40, $5, $81, $A, $0
	dc.b $40, $D, $A1, $E, $10
DATACSU5WSBAP0J_3: dc.b $A
	dc.b $80, $D, $A0, $0, $0
	dc.b $80, $D, $A0, $18, $20
	dc.b $80, $D, $80, $20, $40
	dc.b $90, $D, $80, $10, $0
	dc.b $90, $D, $80, $28, $28
	dc.b $A0, $D, $80, $8, $0
	dc.b $A0, $1, $80, $0, $20
	dc.b $A0, $9, $80, $30, $30
	dc.b $40, $5, $81, $A, $0
	dc.b $40, $D, $A1, $E, $10
	even