; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Nov 29 2019 21:11:00 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAHC9SLLN7FET:
	dc.w DATAHC9SLLN7FET_0-DATAHC9SLLN7FET, DATAHC9SLLN7FET_1-DATAHC9SLLN7FET
	dc.w DATAHC9SLLN7FET_2-DATAHC9SLLN7FET, DATAHC9SLLN7FET_3-DATAHC9SLLN7FET
	dc.w DATAHC9SLLN7FET_4-DATAHC9SLLN7FET, DATAHC9SLLN7FET_5-DATAHC9SLLN7FET
	dc.w DATAHC9SLLN7FET_6-DATAHC9SLLN7FET, DATAHC9SLLN7FET_7-DATAHC9SLLN7FET
	dc.w DATAHC9SLLN7FET_8-DATAHC9SLLN7FET, DATAHC9SLLN7FET_9-DATAHC9SLLN7FET
	dc.w DATAHC9SLLN7FET_A-DATAHC9SLLN7FET, DATAHC9SLLN7FET_B-DATAHC9SLLN7FET
DATAHC9SLLN7FET_0: dc.b $1
	dc.b $EF, $F, $0, $0, $F0
DATAHC9SLLN7FET_1: dc.b $2
	dc.b $F5, $5, $0, $10, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHC9SLLN7FET_2: dc.b $2
	dc.b $F5, $5, $0, $14, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHC9SLLN7FET_3: dc.b $2
	dc.b $F5, $5, $0, $18, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHC9SLLN7FET_4: dc.b $2
	dc.b $F5, $5, $0, $1C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHC9SLLN7FET_5: dc.b $2
	dc.b $F5, $5, $0, $24, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHC9SLLN7FET_6: dc.b $2
	dc.b $F5, $5, $0, $28, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHC9SLLN7FET_7: dc.b $2
	dc.b $F5, $5, $0, $2C, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHC9SLLN7FET_8: dc.b $2
	dc.b $F5, $5, $20, $30, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHC9SLLN7FET_9: dc.b $2
	dc.b $F5, $5, $0, $34, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHC9SLLN7FET_A: dc.b $2
	dc.b $F5, $5, $0, $20, $F8
	dc.b $EF, $F, $0, $0, $F0
DATAHC9SLLN7FET_B: dc.b $1
	dc.b $FF, $D, $0, $38, $F0
	even