; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Nov 23 2019 22:11:25 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATA6MFUDJ5DSJF:
	dc.w $0, DATA6MFUDJ5DSJF_1-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_2-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_3-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_4-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_5-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_6-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_7-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_8-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_9-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_A-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_B-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_C-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_D-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_E-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_F-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_10-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_11-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_12-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_13-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_14-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_15-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_16-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_17-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_18-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_19-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_1A-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_1B-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_1C-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_1D-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_1E-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_1F-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_20-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_21-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_22-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_23-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_24-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_25-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_26-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_27-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_28-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_29-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_2A-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_2B-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_2C-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_2D-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_2E-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_2F-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_30-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_31-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_32-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_33-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_34-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_35-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_36-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_37-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_38-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_39-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_3A-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_3B-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_3C-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_3D-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_3E-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_3F-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_40-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_41-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_42-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_43-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_44-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_45-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_46-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_47-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_48-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_49-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_4A-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_4B-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_4C-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_4D-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_4E-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_4F-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_50-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_51-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_52-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_53-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_54-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_55-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_56-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_57-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_58-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_59-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_5A-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_5B-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_5C-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_5D-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_5E-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_5F-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_60-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_61-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_62-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_63-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_64-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_65-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_66-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_67-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_68-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_69-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_6A-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_6B-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_6C-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_6D-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_6E-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_6F-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_70-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_71-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_72-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_73-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_74-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_75-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_76-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_77-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_78-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_79-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_7A-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_7B-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_7C-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_7D-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_7E-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_7F-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_80-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_81-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_82-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_83-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_84-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_85-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_86-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_87-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_88-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_89-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_8A-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_8B-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_8C-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_8D-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_8E-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_8F-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_90-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_91-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_92-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_93-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_94-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_95-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_96-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_97-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_98-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_99-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_9A-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_9B-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_9C-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_9D-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_9E-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_9F-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_A0-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_A1-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_A2-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_A3-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_A4-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_A5-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_A6-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_A7-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_A8-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_A9-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_AA-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_AB-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_AC-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_AD-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_AE-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_AF-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_B0-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_B1-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_B2-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_B3-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_B4-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_B5-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_B6-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_B7-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_B8-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_B9-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_BA-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_BB-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_BC-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_BD-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_BE-DATA6MFUDJ5DSJF, DATA6MFUDJ5DSJF_BF-DATA6MFUDJ5DSJF
	dc.w DATA6MFUDJ5DSJF_C0-DATA6MFUDJ5DSJF
DATA6MFUDJ5DSJF_1: dc.b $4
	dc.b $EC, $F, $0, $0, $ED
	dc.b $FA, $2, $0, $10, $D
	dc.b $C, $4, $0, $13, $EC
	dc.b $C, $0, $0, $15, $5
DATA6MFUDJ5DSJF_2: dc.b $4
	dc.b $EC, $B, $0, $0, $F2
	dc.b $C, $C, $0, $C, $F2
	dc.b $F4, $1, $0, $10, $A
	dc.b $C, $0, $0, $12, $12
DATA6MFUDJ5DSJF_3: dc.b $2
	dc.b $ED, $D, $0, $0, $F2
	dc.b $FD, $A, $0, $8, $F2
DATA6MFUDJ5DSJF_4: dc.b $4
	dc.b $EC, $B, $0, $0, $F0
	dc.b $F4, $3, $0, $C, $8
	dc.b $C, $8, $0, $10, $F0
	dc.b $EC, $0, $0, $13, $8
DATA6MFUDJ5DSJF_5: dc.b $4
	dc.b $EC, $F, $0, $0, $ED
	dc.b $FC, $1, $0, $10, $D
	dc.b $C, $4, $0, $12, $ED
	dc.b $C, $0, $0, $14, $6
DATA6MFUDJ5DSJF_6: dc.b $5
	dc.b $FC, $9, $0, $0, $F5
	dc.b $4, $1, $0, $6, $ED
	dc.b $8, $0, $0, $8, $D
	dc.b $EC, $9, $0, $9, $F4
	dc.b $C, $8, $0, $F, $F5
DATA6MFUDJ5DSJF_7: dc.b $3
	dc.b $FD, $A, $0, $0, $F2
	dc.b $ED, $9, $0, $9, $F3
	dc.b $F5, $0, $0, $F, $B
DATA6MFUDJ5DSJF_8: dc.b $3
	dc.b $EC, $B, $0, $0, $F3
	dc.b $F4, $0, $0, $C, $B
	dc.b $C, $8, $0, $D, $F3
DATA6MFUDJ5DSJF_9: dc.b $4
	dc.b $EE, $E, $0, $0, $EB
	dc.b $6, $4, $0, $C, $F3
	dc.b $E, $1, $0, $E, $FB
	dc.b $F6, $1, $0, $10, $B
DATA6MFUDJ5DSJF_A: dc.b $5
	dc.b $F2, $D, $0, $0, $E9
	dc.b $FA, $6, $0, $8, $9
	dc.b $2, $8, $0, $E, $F1
	dc.b $A, $4, $0, $11, $F9
	dc.b $12, $4, $0, $13, $1
DATA6MFUDJ5DSJF_B: dc.b $5
	dc.b $F5, $C, $0, $0, $E9
	dc.b $ED, $8, $0, $4, $F1
	dc.b $FD, $C, $0, $7, $F1
	dc.b $5, $C, $0, $B, $F9
	dc.b $D, $4, $0, $F, $1
DATA6MFUDJ5DSJF_C: dc.b $4
	dc.b $ED, $E, $0, $0, $ED
	dc.b $5, $C, $0, $C, $F5
	dc.b $D, $4, $0, $10, $FD
	dc.b $FD, $0, $0, $12, $D
DATA6MFUDJ5DSJF_D: dc.b $5
	dc.b $F0, $E, $0, $0, $ED
	dc.b $8, $8, $0, $C, $ED
	dc.b $E8, $0, $0, $F, $F5
	dc.b $10, $1, $0, $10, $FD
	dc.b $F0, $2, $0, $12, $D
DATA6MFUDJ5DSJF_E: dc.b $5
	dc.b $F3, $E, $0, $0, $EC
	dc.b $EB, $4, $0, $C, $F4
	dc.b $B, $1, $0, $E, $FC
	dc.b $FB, $5, $0, $10, $C
	dc.b $B, $0, $0, $14, $C
DATA6MFUDJ5DSJF_F: dc.b $5
	dc.b $F9, $C, $0, $0, $E5
	dc.b $F1, $8, $0, $4, $ED
	dc.b $1, $C, $0, $7, $ED
	dc.b $9, $C, $0, $B, $F5
	dc.b $11, $4, $0, $F, $FD
DATA6MFUDJ5DSJF_10: dc.b $5
	dc.b $EF, $A, $0, $0, $F1
	dc.b $F7, $0, $0, $9, $E9
	dc.b $FF, $5, $0, $A, $9
	dc.b $7, $4, $0, $E, $F9
	dc.b $F, $4, $0, $10, $1
DATA6MFUDJ5DSJF_11: dc.b $4
	dc.b $F2, $F, $0, $0, $EC
	dc.b $EA, $4, $0, $10, $FC
	dc.b $F2, $0, $0, $12, $C
	dc.b $A, $1, $0, $13, $C
DATA6MFUDJ5DSJF_12: dc.b $4
	dc.b $F6, $E, $0, $0, $EC
	dc.b $E, $0, $0, $C, $F4
	dc.b $EE, $3, $0, $D, $C
	dc.b $EE, $0, $0, $11, $FB
DATA6MFUDJ5DSJF_13: dc.b $2
	dc.b $F2, $B, $0, $0, $ED
	dc.b $FA, $5, $0, $C, $5
DATA6MFUDJ5DSJF_14: dc.b $2
	dc.b $F2, $F, $0, $0, $EC
	dc.b $F2, $3, $0, $10, $C
DATA6MFUDJ5DSJF_15: dc.b $4
	dc.b $EE, $9, $0, $0, $FC
	dc.b $F6, $6, $0, $6, $EC
	dc.b $FE, $6, $0, $C, $FC
	dc.b $6, $1, $0, $12, $C
DATA6MFUDJ5DSJF_16: dc.b $3
	dc.b $EC, $7, $0, $0, $4
	dc.b $F4, $A, $0, $8, $EC
	dc.b $C, $4, $0, $11, $4
DATA6MFUDJ5DSJF_17: dc.b $3
	dc.b $F5, $E, $0, $0, $ED
	dc.b $D, $0, $0, $C, $F5
	dc.b $F5, $2, $0, $D, $D
DATA6MFUDJ5DSJF_18: dc.b $3
	dc.b $F5, $E, $0, $0, $EC
	dc.b $ED, $0, $0, $C, $F4
	dc.b $F5, $2, $0, $D, $C
DATA6MFUDJ5DSJF_19: dc.b $4
	dc.b $F7, $B, $0, $0, $EE
	dc.b $EF, $4, $0, $C, $F6
	dc.b $FF, $8, $0, $E, $6
	dc.b $7, $0, $0, $11, $6
DATA6MFUDJ5DSJF_1A: dc.b $5
	dc.b $EA, $B, $0, $0, $F8
	dc.b $F2, $1, $0, $C, $10
	dc.b $FA, $3, $0, $E, $F0
	dc.b $A, $4, $0, $12, $F8
	dc.b $12, $0, $0, $14, $F8
DATA6MFUDJ5DSJF_1B: dc.b $5
	dc.b $EB, $3, $0, $0, $7
	dc.b $F3, $3, $0, $4, $FF
	dc.b $F3, $1, $0, $8, $F
	dc.b $FB, $6, $0, $A, $EF
	dc.b $13, $0, $0, $10, $F7
DATA6MFUDJ5DSJF_1C: dc.b $4
	dc.b $F6, $E, $0, $0, $F0
	dc.b $E, $8, $0, $C, $F0
	dc.b $EE, $4, $0, $F, $0
	dc.b $F6, $1, $0, $11, $10
DATA6MFUDJ5DSJF_1D: dc.b $5
	dc.b $4, $C, $0, $0, $E9
	dc.b $EC, $A, $0, $4, $F1
	dc.b $C, $C, $0, $D, $F1
	dc.b $FC, $8, $0, $11, $9
	dc.b $4, $0, $0, $14, $9
DATA6MFUDJ5DSJF_1E: dc.b $5
	dc.b $FF, $A, $0, $0, $EE
	dc.b $EF, $9, $0, $9, $F6
	dc.b $E7, $4, $0, $F, $FE
	dc.b $FF, $8, $0, $11, $6
	dc.b $7, $0, $0, $14, $6
DATA6MFUDJ5DSJF_1F: dc.b $5
	dc.b $EA, $3, $0, $0, $7
	dc.b $F2, $3, $0, $4, $FF
	dc.b $F2, $1, $0, $8, $F
	dc.b $FA, $6, $0, $A, $EF
	dc.b $12, $0, $0, $10, $F7
DATA6MFUDJ5DSJF_20: dc.b $5
	dc.b $E9, $7, $0, $0, $FF
	dc.b $F1, $1, $0, $8, $F
	dc.b $F9, $6, $0, $A, $EF
	dc.b $9, $0, $0, $10, $FF
	dc.b $11, $0, $0, $11, $F7
DATA6MFUDJ5DSJF_21: dc.b $2
	dc.b $F0, $F, $0, $0, $F0
	dc.b $10, $C, $0, $10, $F0
DATA6MFUDJ5DSJF_22: dc.b $3
	dc.b $F0, $B, $0, $0, $F7
	dc.b $10, $8, $0, $C, $F7
	dc.b $0, $1, $0, $F, $EF
DATA6MFUDJ5DSJF_23: dc.b $2
	dc.b $F0, $F, $0, $0, $F1
	dc.b $10, $8, $0, $10, $F1
DATA6MFUDJ5DSJF_24: dc.b $3
	dc.b $F0, $B, $0, $0, $F7
	dc.b $10, $8, $0, $C, $F7
	dc.b $0, $1, $0, $F, $EF
DATA6MFUDJ5DSJF_25: dc.b $4
	dc.b $EF, $A, $0, $0, $EC
	dc.b $7, $D, $0, $9, $F4
	dc.b $F7, $1, $0, $11, $4
	dc.b $FF, $0, $0, $13, $C
DATA6MFUDJ5DSJF_26: dc.b $3
	dc.b $F7, $C, $0, $0, $E9
	dc.b $EF, $8, $0, $4, $F1
	dc.b $FF, $E, $0, $7, $F1
DATA6MFUDJ5DSJF_27: dc.b $4
	dc.b $F0, $B, $0, $0, $F0
	dc.b $F8, $0, $0, $C, $E8
	dc.b $F8, $3, $0, $D, $8
	dc.b $10, $4, $0, $11, $F8
DATA6MFUDJ5DSJF_28: dc.b $3
	dc.b $F7, $C, $0, $0, $E9
	dc.b $EF, $8, $0, $4, $F1
	dc.b $FF, $E, $0, $7, $F1
DATA6MFUDJ5DSJF_29: dc.b $3
	dc.b $F1, $E, $0, $0, $EC
	dc.b $9, $8, $0, $C, $FC
	dc.b $F1, $2, $0, $F, $C
DATA6MFUDJ5DSJF_2A: dc.b $3
	dc.b $F1, $E, $0, $0, $F0
	dc.b $9, $4, $0, $C, $0
	dc.b $F1, $2, $0, $E, $10
DATA6MFUDJ5DSJF_2B: dc.b $3
	dc.b $F0, $E, $0, $0, $F1
	dc.b $8, $C, $0, $C, $F9
	dc.b $F8, $1, $0, $10, $11
DATA6MFUDJ5DSJF_2C: dc.b $3
	dc.b $F1, $E, $0, $0, $F0
	dc.b $9, $4, $0, $C, $0
	dc.b $F1, $2, $0, $E, $10
DATA6MFUDJ5DSJF_2D: dc.b $3
	dc.b $EE, $F, $0, $0, $F7
	dc.b $F6, $2, $0, $10, $EF
	dc.b $E, $0, $0, $13, $F7
DATA6MFUDJ5DSJF_2E: dc.b $3
	dc.b $EE, $B, $0, $0, $FE
	dc.b $F6, $6, $0, $C, $EE
	dc.b $E, $0, $0, $12, $F6
DATA6MFUDJ5DSJF_2F: dc.b $4
	dc.b $F7, $E, $0, $0, $EF
	dc.b $EF, $C, $0, $C, $F7
	dc.b $F, $0, $0, $10, $F7
	dc.b $F7, $1, $0, $11, $F
DATA6MFUDJ5DSJF_30: dc.b $3
	dc.b $EE, $B, $0, $0, $FE
	dc.b $F6, $6, $0, $C, $EE
	dc.b $E, $0, $0, $12, $F6
DATA6MFUDJ5DSJF_31: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATA6MFUDJ5DSJF_32: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATA6MFUDJ5DSJF_33: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATA6MFUDJ5DSJF_34: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATA6MFUDJ5DSJF_35: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATA6MFUDJ5DSJF_36: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATA6MFUDJ5DSJF_37: dc.b $3
	dc.b $F0, $E, $0, $0, $ED
	dc.b $F0, $2, $0, $C, $D
	dc.b $8, $8, $0, $F, $F5
DATA6MFUDJ5DSJF_38: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F0, $2, $0, $C, $C
	dc.b $8, $8, $0, $F, $F4
DATA6MFUDJ5DSJF_39: dc.b $2
	dc.b $EB, $A, $0, $0, $F1
	dc.b $3, $6, $0, $9, $F9
DATA6MFUDJ5DSJF_3A: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATA6MFUDJ5DSJF_3B: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATA6MFUDJ5DSJF_3C: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATA6MFUDJ5DSJF_3D: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATA6MFUDJ5DSJF_3E: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATA6MFUDJ5DSJF_3F: dc.b $2
	dc.b $F2, $B, $0, $0, $F8
	dc.b $12, $8, $0, $C, $F8
DATA6MFUDJ5DSJF_40: dc.b $2
	dc.b $FA, $B, $0, $0, $F7
	dc.b $2, $1, $0, $C, $F
DATA6MFUDJ5DSJF_41: dc.b $4
	dc.b $EE, $B, $0, $0, $F5
	dc.b $F6, $1, $0, $C, $ED
	dc.b $FE, $2, $0, $E, $D
	dc.b $E, $4, $0, $11, $FD
DATA6MFUDJ5DSJF_42: dc.b $4
	dc.b $EE, $B, $0, $0, $F6
	dc.b $F6, $1, $0, $C, $EE
	dc.b $FE, $1, $0, $E, $E
	dc.b $E, $4, $0, $10, $FE
DATA6MFUDJ5DSJF_43: dc.b $3
	dc.b $F0, $B, $0, $0, $F9
	dc.b $F8, $1, $0, $C, $F1
	dc.b $10, $4, $0, $E, $1
DATA6MFUDJ5DSJF_44: dc.b $4
	dc.b $EA, $A, $0, $0, $ED
	dc.b $2, $9, $0, $9, $F5
	dc.b $F2, $1, $0, $F, $5
	dc.b $A, $1, $0, $11, $D
DATA6MFUDJ5DSJF_45: dc.b $5
	dc.b $EE, $E, $0, $0, $E8
	dc.b $6, $5, $0, $C, $F0
	dc.b $E6, $0, $0, $10, $F8
	dc.b $E, $0, $0, $11, $0
	dc.b $E6, $1, $0, $12, $8
DATA6MFUDJ5DSJF_46: dc.b $3
	dc.b $ED, $B, $0, $0, $ED
	dc.b $D, $8, $0, $C, $ED
	dc.b $E5, $0, $0, $F, $F5
DATA6MFUDJ5DSJF_47: dc.b $5
	dc.b $EE, $E, $0, $0, $EB
	dc.b $E6, $4, $0, $C, $F3
	dc.b $6, $5, $0, $E, $F3
	dc.b $E, $0, $0, $12, $3
	dc.b $F6, $0, $0, $13, $B
DATA6MFUDJ5DSJF_48: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $F8, $A, $0, $8, $F4
	dc.b $10, $0, $0, $11, $F4
	dc.b $E8, $1, $0, $12, $C
	dc.b $8, $0, $0, $14, $C
DATA6MFUDJ5DSJF_49: dc.b $4
	dc.b $EB, $D, $0, $0, $F0
	dc.b $3, $D, $0, $8, $F0
	dc.b $FB, $4, $0, $10, $F8
	dc.b $EB, $1, $0, $12, $10
DATA6MFUDJ5DSJF_4A: dc.b $4
	dc.b $EB, $D, $0, $0, $F0
	dc.b $3, $D, $0, $8, $F0
	dc.b $FB, $4, $0, $10, $F8
	dc.b $EB, $1, $0, $12, $10
DATA6MFUDJ5DSJF_4B: dc.b $3
	dc.b $F4, $E, $0, $0, $E6
	dc.b $F4, $2, $0, $C, $6
	dc.b $FC, $5, $0, $F, $E
DATA6MFUDJ5DSJF_4C: dc.b $3
	dc.b $F4, $E, $0, $0, $E6
	dc.b $F4, $2, $0, $C, $6
	dc.b $FC, $5, $0, $F, $E
DATA6MFUDJ5DSJF_4D: dc.b $3
	dc.b $EC, $F, $0, $0, $EF
	dc.b $4, $0, $0, $10, $F
	dc.b $C, $C, $0, $11, $EF
DATA6MFUDJ5DSJF_4E: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATA6MFUDJ5DSJF_4F: dc.b $2
	dc.b $D, $8, $0, $0, $F8
	dc.b $ED, $B, $0, $3, $F0
DATA6MFUDJ5DSJF_50: dc.b $3
	dc.b $EE, $B, $0, $0, $F0
	dc.b $F6, $2, $0, $C, $8
	dc.b $E, $8, $0, $F, $F8
DATA6MFUDJ5DSJF_51: dc.b $3
	dc.b $ED, $B, $0, $0, $F3
	dc.b $5, $1, $0, $C, $EB
	dc.b $D, $8, $0, $E, $F3
DATA6MFUDJ5DSJF_52: dc.b $2
	dc.b $EC, $B, $0, $0, $F3
	dc.b $C, $4, $0, $C, $F3
DATA6MFUDJ5DSJF_53: dc.b $4
	dc.b $ED, $B, $0, $0, $F3
	dc.b $5, $1, $0, $C, $EB
	dc.b $D, $4, $0, $E, $F3
	dc.b $D, $0, $0, $10, $3
DATA6MFUDJ5DSJF_54: dc.b $2
	dc.b $EC, $B, $0, $0, $F3
	dc.b $C, $4, $0, $C, $F3
DATA6MFUDJ5DSJF_55: dc.b $5
	dc.b $ED, $A, $0, $0, $F0
	dc.b $5, $5, $0, $9, $F8
	dc.b $F5, $0, $0, $D, $8
	dc.b $D, $0, $0, $E, $8
	dc.b $5, $0, $0, $F, $F0
DATA6MFUDJ5DSJF_56: dc.b $4
	dc.b $ED, $B, $0, $0, $F1
	dc.b $D, $0, $0, $C, $8
	dc.b $D, $0, $0, $D, $0
	dc.b $D, $0, $0, $E, $F8
DATA6MFUDJ5DSJF_57: dc.b $3
	dc.b $ED, $7, $0, $0, $F2
	dc.b $D, $8, $0, $8, $F8
	dc.b $ED, $3, $0, $B, $2
DATA6MFUDJ5DSJF_58: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATA6MFUDJ5DSJF_59: dc.b $6
	dc.b $5, $0, $0, $0, $0
	dc.b $D, $0, $0, $1, $8
	dc.b $D, $0, $0, $2, $F8
	dc.b $D, $0, $0, $3, $0
	dc.b $ED, $7, $0, $4, $F0
	dc.b $ED, $2, $0, $C, $0
DATA6MFUDJ5DSJF_5A: dc.b $4
	dc.b $5, $9, $0, $0, $F7
	dc.b $FD, $8, $0, $6, $EF
	dc.b $ED, $D, $0, $9, $EF
	dc.b $E5, $0, $0, $11, $FF
DATA6MFUDJ5DSJF_5B: dc.b $4
	dc.b $E4, $0, $0, $0, $F9
	dc.b $EC, $D, $0, $1, $F1
	dc.b $FC, $9, $0, $9, $F1
	dc.b $C, $8, $0, $F, $F9
DATA6MFUDJ5DSJF_5C: dc.b $3
	dc.b $F4, $A, $0, $0, $F9
	dc.b $F4, $1, $0, $9, $11
	dc.b $FC, $5, $0, $B, $E9
DATA6MFUDJ5DSJF_5D: dc.b $3
	dc.b $FB, $D, $0, $0, $F1
	dc.b $F3, $C, $0, $8, $F9
	dc.b $FB, $4, $0, $C, $11
DATA6MFUDJ5DSJF_5E: dc.b $2
	dc.b $F3, $A, $0, $0, $0
	dc.b $F3, $A, $8, $0, $E8
DATA6MFUDJ5DSJF_5F: dc.b $3
	dc.b $FB, $D, $8, $0, $EF
	dc.b $F3, $C, $8, $8, $E7
	dc.b $FB, $4, $8, $C, $DF
DATA6MFUDJ5DSJF_60: dc.b $3
	dc.b $F4, $A, $8, $0, $EF
	dc.b $F4, $1, $8, $9, $E7
	dc.b $FC, $5, $8, $B, $7
DATA6MFUDJ5DSJF_61: dc.b $3
	dc.b $F4, $D, $0, $0, $EA
	dc.b $4, $C, $0, $8, $F2
	dc.b $FC, $0, $0, $C, $A
DATA6MFUDJ5DSJF_62: dc.b $3
	dc.b $F4, $D, $0, $0, $EC
	dc.b $4, $8, $0, $8, $F4
	dc.b $F4, $1, $0, $B, $C
DATA6MFUDJ5DSJF_63: dc.b $3
	dc.b $F4, $D, $8, $0, $F6
	dc.b $4, $C, $8, $8, $EE
	dc.b $FC, $0, $8, $C, $EE
DATA6MFUDJ5DSJF_64: dc.b $5
	dc.b $EF, $8, $0, $0, $F2
	dc.b $FF, $C, $0, $3, $ED
	dc.b $F, $8, $0, $7, $F6
	dc.b $F7, $8, $0, $A, $F1
	dc.b $7, $4, $0, $D, $F5
DATA6MFUDJ5DSJF_65: dc.b $5
	dc.b $F4, $C, $0, $0, $F3
	dc.b $EC, $8, $0, $4, $F7
	dc.b $FC, $C, $0, $7, $F5
	dc.b $4, $C, $0, $B, $F3
	dc.b $C, $8, $0, $F, $F6
DATA6MFUDJ5DSJF_66: dc.b $5
	dc.b $EE, $A, $0, $0, $EE
	dc.b $FE, $4, $0, $9, $6
	dc.b $6, $8, $0, $B, $F5
	dc.b $E, $8, $0, $E, $F8
	dc.b $F6, $0, $10, $11, $6
DATA6MFUDJ5DSJF_67: dc.b $4
	dc.b $E8, $E, $0, $0, $EF
	dc.b $0, $5, $0, $C, $F7
	dc.b $0, $0, $0, $10, $7
	dc.b $10, $4, $0, $11, $FF
DATA6MFUDJ5DSJF_68: dc.b $6
	dc.b $E9, $E, $0, $0, $EE
	dc.b $1, $C, $0, $C, $F6
	dc.b $E1, $0, $0, $10, $FE
	dc.b $9, $8, $0, $11, $FE
	dc.b $E9, $0, $0, $14, $E
	dc.b $F9, $0, $0, $15, $E
DATA6MFUDJ5DSJF_69: dc.b $3
	dc.b $E9, $F, $0, $0, $F2
	dc.b $9, $C, $0, $10, $F2
	dc.b $E1, $0, $0, $14, $2
DATA6MFUDJ5DSJF_6A: dc.b $6
	dc.b $EC, $4, $0, $0, $F8
	dc.b $EC, $0, $0, $2, $8
	dc.b $F4, $C, $0, $3, $F2
	dc.b $FC, $8, $0, $7, $F5
	dc.b $4, $C, $0, $A, $F2
	dc.b $C, $8, $0, $E, $F5
DATA6MFUDJ5DSJF_6B: dc.b $7
	dc.b $EC, $4, $0, $0, $F9
	dc.b $E4, $0, $0, $2, $FE
	dc.b $EC, $0, $0, $3, $9
	dc.b $F4, $C, $0, $4, $F3
	dc.b $FC, $8, $0, $8, $F6
	dc.b $4, $C, $0, $B, $F3
	dc.b $C, $8, $0, $F, $F6
DATA6MFUDJ5DSJF_6C: dc.b $7
	dc.b $EC, $4, $0, $0, $F9
	dc.b $E4, $0, $0, $2, $FE
	dc.b $EC, $0, $0, $3, $9
	dc.b $F4, $C, $0, $4, $F3
	dc.b $FC, $8, $0, $8, $F6
	dc.b $4, $C, $0, $B, $F3
	dc.b $C, $8, $0, $F, $F6
DATA6MFUDJ5DSJF_6D: dc.b $3
	dc.b $EC, $A, $0, $0, $EF
	dc.b $4, $6, $0, $9, $F7
	dc.b $F4, $1, $0, $F, $7
DATA6MFUDJ5DSJF_6E: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $5, $0, $C, $F8
	dc.b $F8, $1, $0, $10, $8
DATA6MFUDJ5DSJF_6F: dc.b $8
	dc.b $8, $5, $0, $0, $F8
	dc.b $F0, $0, $0, $4, $8
	dc.b $0, $0, $0, $5, $8
	dc.b $F0, $2, $0, $6, $F8
	dc.b $E8, $3, $0, $9, $0
	dc.b $F0, $2, $0, $D, $F0
	dc.b $E8, $0, $0, $10, $F8
	dc.b $E8, $0, $0, $11, $F0
DATA6MFUDJ5DSJF_70: dc.b $9
	dc.b $8, $5, $0, $0, $F8
	dc.b $F0, $0, $0, $4, $8
	dc.b $0, $0, $0, $5, $8
	dc.b $F0, $2, $0, $6, $F8
	dc.b $E8, $3, $0, $9, $0
	dc.b $F8, $1, $0, $D, $F0
	dc.b $E8, $0, $0, $F, $F0
	dc.b $F0, $0, $0, $10, $F0
	dc.b $E8, $0, $0, $11, $F8
DATA6MFUDJ5DSJF_71: dc.b $2
	dc.b $ED, $F, $0, $0, $EE
	dc.b $D, $8, $0, $10, $F6
DATA6MFUDJ5DSJF_72: dc.b $3
	dc.b $EF, $B, $0, $0, $FB
	dc.b $FF, $5, $0, $C, $EB
	dc.b $F, $8, $0, $10, $FB
DATA6MFUDJ5DSJF_73: dc.b $2
	dc.b $F4, $B, $0, $0, $FB
	dc.b $FC, $6, $0, $C, $EB
DATA6MFUDJ5DSJF_74: dc.b $3
	dc.b $F3, $B, $0, $0, $FD
	dc.b $FB, $6, $0, $C, $ED
	dc.b $13, $0, $0, $12, $FD
DATA6MFUDJ5DSJF_75: dc.b $3
	dc.b $4, $D, $0, $0, $EE
	dc.b $F4, $D, $0, $8, $F6
	dc.b $4, $0, $0, $10, $E
DATA6MFUDJ5DSJF_76: dc.b $3
	dc.b $F2, $F, $0, $0, $F2
	dc.b $12, $0, $0, $10, $F2
	dc.b $EA, $4, $0, $11, $FA
DATA6MFUDJ5DSJF_77: dc.b $6
	dc.b $F7, $C, $0, $0, $EB
	dc.b $EF, $8, $0, $4, $F3
	dc.b $FF, $D, $0, $7, $F3
	dc.b $E7, $0, $0, $F, $FB
	dc.b $F, $4, $0, $10, $FB
	dc.b $F7, $0, $0, $12, $B
DATA6MFUDJ5DSJF_78: dc.b $3
	dc.b $EF, $F, $0, $0, $F2
	dc.b $F, $4, $0, $10, $F2
	dc.b $E7, $4, $0, $12, $FA
DATA6MFUDJ5DSJF_79: dc.b $4
	dc.b $EA, $7, $0, $0, $F9
	dc.b $F2, $1, $0, $8, $F1
	dc.b $F2, $3, $0, $A, $9
	dc.b $A, $9, $0, $E, $F1
DATA6MFUDJ5DSJF_7A: dc.b $3
	dc.b $EC, $E, $0, $0, $F3
	dc.b $4, $9, $0, $C, $FB
	dc.b $FC, $0, $0, $12, $13
DATA6MFUDJ5DSJF_7B: dc.b $2
	dc.b $EE, $E, $0, $0, $F4
	dc.b $6, $9, $0, $C, $FC
DATA6MFUDJ5DSJF_7C: dc.b $3
	dc.b $EE, $E, $0, $0, $F4
	dc.b $6, $8, $0, $C, $FC
	dc.b $E, $4, $0, $F, $4
DATA6MFUDJ5DSJF_7D: dc.b $3
	dc.b $EC, $E, $0, $0, $F3
	dc.b $4, $9, $0, $C, $FB
	dc.b $FC, $0, $0, $12, $13
DATA6MFUDJ5DSJF_7E: dc.b $3
	dc.b $EC, $F, $0, $0, $F2
	dc.b $F4, $1, $0, $10, $EA
	dc.b $4, $0, $0, $12, $12
DATA6MFUDJ5DSJF_7F: dc.b $5
	dc.b $EA, $B, $0, $0, $F7
	dc.b $F2, $2, $0, $C, $EF
	dc.b $F2, $1, $0, $F, $F
	dc.b $FA, $0, $0, $11, $E7
	dc.b $A, $0, $0, $12, $F7
DATA6MFUDJ5DSJF_80: dc.b $4
	dc.b $F5, $D, $0, $0, $EA
	dc.b $ED, $C, $0, $8, $F2
	dc.b $5, $4, $0, $C, $F2
	dc.b $F5, $6, $0, $E, $A
DATA6MFUDJ5DSJF_81: dc.b $3
	dc.b $EE, $F, $0, $0, $EF
	dc.b $F6, $0, $0, $10, $E7
	dc.b $F6, $2, $0, $11, $F
DATA6MFUDJ5DSJF_82: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $F8, $A, $0, $8, $F4
	dc.b $10, $0, $0, $11, $F4
	dc.b $E8, $1, $0, $12, $C
	dc.b $8, $0, $0, $14, $C
DATA6MFUDJ5DSJF_83: dc.b $1
	dc.b $F1, $F, $0, $0, $F2
DATA6MFUDJ5DSJF_84: dc.b $1
	dc.b $F2, $F, $0, $0, $F2
DATA6MFUDJ5DSJF_85: dc.b $2
	dc.b $F1, $B, $0, $0, $F4
	dc.b $F9, $0, $0, $C, $EC
DATA6MFUDJ5DSJF_86: dc.b $3
	dc.b $E4, $B, $0, $0, $EF
	dc.b $4, $9, $0, $C, $EF
	dc.b $EC, $2, $0, $12, $7
DATA6MFUDJ5DSJF_87: dc.b $4
	dc.b $DC, $7, $0, $0, $EF
	dc.b $FC, $A, $0, $8, $EF
	dc.b $E4, $2, $0, $11, $FF
	dc.b $FC, $0, $0, $14, $7
DATA6MFUDJ5DSJF_88: dc.b $4
	dc.b $E1, $B, $0, $0, $F0
	dc.b $1, $9, $0, $C, $F0
	dc.b $E9, $0, $0, $12, $8
	dc.b $FA, $0, $0, $13, $8
DATA6MFUDJ5DSJF_89: dc.b $3
	dc.b $E2, $B, $0, $0, $F1
	dc.b $2, $9, $0, $C, $F1
	dc.b $FA, $0, $0, $12, $9
DATA6MFUDJ5DSJF_8A: dc.b $4
	dc.b $E7, $B, $0, $0, $F0
	dc.b $7, $5, $0, $C, $F8
	dc.b $EF, $1, $0, $10, $8
	dc.b $F, $0, $0, $12, $8
DATA6MFUDJ5DSJF_8B: dc.b $4
	dc.b $E8, $B, $0, $0, $EF
	dc.b $8, $5, $0, $C, $F7
	dc.b $F0, $1, $0, $10, $7
	dc.b $10, $0, $0, $12, $7
DATA6MFUDJ5DSJF_8C: dc.b $4
	dc.b $E7, $B, $0, $0, $EF
	dc.b $7, $5, $0, $C, $F7
	dc.b $EF, $1, $0, $10, $7
	dc.b $F, $0, $0, $12, $7
DATA6MFUDJ5DSJF_8D: dc.b $4
	dc.b $4, $C, $0, $0, $EF
	dc.b $E4, $3, $0, $4, $F7
	dc.b $C, $8, $0, $8, $F7
	dc.b $EC, $6, $0, $B, $FF
DATA6MFUDJ5DSJF_8E: dc.b $3
	dc.b $FC, $E, $0, $0, $F0
	dc.b $EC, $5, $0, $C, $F8
	dc.b $F4, $0, $0, $10, $8
DATA6MFUDJ5DSJF_8F: dc.b $4
	dc.b $EC, $D, $0, $0, $E8
	dc.b $FC, $9, $0, $8, $F0
	dc.b $E4, $0, $0, $E, $F8
	dc.b $C, $8, $0, $F, $F8
DATA6MFUDJ5DSJF_90: dc.b $3
	dc.b $EC, $E, $0, $0, $E8
	dc.b $4, $8, $0, $C, $F0
	dc.b $C, $8, $0, $F, $F8
DATA6MFUDJ5DSJF_91: dc.b $5
	dc.b $E7, $F, $0, $0, $ED
	dc.b $F7, $2, $0, $10, $D
	dc.b $7, $4, $0, $13, $ED
	dc.b $7, $1, $0, $15, $5
	dc.b $F, $4, $0, $17, $E5
DATA6MFUDJ5DSJF_92: dc.b $4
	dc.b $E8, $B, $0, $0, $F1
	dc.b $8, $D, $0, $C, $F1
	dc.b $F0, $1, $0, $14, $9
	dc.b $8, $0, $0, $16, $11
DATA6MFUDJ5DSJF_93: dc.b $2
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $6, $0, $C, $F8
DATA6MFUDJ5DSJF_94: dc.b $3
	dc.b $FC, $E, $0, $0, $EC
	dc.b $E4, $A, $0, $C, $F4
	dc.b $FC, $0, $0, $15, $C
DATA6MFUDJ5DSJF_95: dc.b $5
	dc.b $FB, $D, $0, $0, $EC
	dc.b $B, $4, $0, $8, $EC
	dc.b $E3, $A, $0, $A, $F4
	dc.b $B, $4, $0, $13, $4
	dc.b $FB, $1, $0, $15, $C
DATA6MFUDJ5DSJF_96: dc.b $5
	dc.b $6, $C, $0, $0, $ED
	dc.b $E, $0, $0, $4, $ED
	dc.b $E6, $B, $0, $5, $F5
	dc.b $E, $8, $0, $11, $FD
	dc.b $6, $0, $0, $14, $D
DATA6MFUDJ5DSJF_97: dc.b $4
	dc.b $E8, $B, $0, $0, $F3
	dc.b $8, $5, $0, $C, $F3
	dc.b $10, $0, $0, $10, $3
	dc.b $F5, $0, $8, $11, $B
DATA6MFUDJ5DSJF_98: dc.b $3
	dc.b $E7, $B, $0, $0, $F2
	dc.b $7, $9, $0, $C, $F2
	dc.b $EF, $1, $0, $12, $A
DATA6MFUDJ5DSJF_99: dc.b $5
	dc.b $ED, $E, $0, $0, $E3
	dc.b $5, $8, $0, $C, $EB
	dc.b $D, $1, $0, $F, $FB
	dc.b $ED, $2, $0, $11, $3
	dc.b $F5, $2, $0, $14, $B
DATA6MFUDJ5DSJF_9A: dc.b $6
	dc.b $EE, $E, $0, $0, $EA
	dc.b $F6, $0, $0, $C, $E2
	dc.b $FE, $5, $0, $D, $A
	dc.b $6, $8, $0, $11, $F2
	dc.b $E, $4, $0, $14, $2
	dc.b $16, $0, $0, $16, $2
DATA6MFUDJ5DSJF_9B: dc.b $4
	dc.b $EB, $E, $0, $0, $ED
	dc.b $F3, $0, $0, $C, $E5
	dc.b $3, $C, $0, $D, $F5
	dc.b $B, $4, $0, $11, $5
DATA6MFUDJ5DSJF_9C: dc.b $6
	dc.b $E7, $B, $0, $0, $ED
	dc.b $EF, $1, $0, $C, $E5
	dc.b $EF, $3, $0, $E, $5
	dc.b $FF, $0, $0, $12, $D
	dc.b $7, $4, $0, $13, $F5
	dc.b $F, $4, $0, $15, $FD
DATA6MFUDJ5DSJF_9D: dc.b $4
	dc.b $EC, $D, $0, $0, $E4
	dc.b $FC, $A, $0, $8, $EC
	dc.b $14, $0, $0, $11, $FC
	dc.b $F4, $6, $0, $12, $4
DATA6MFUDJ5DSJF_9E: dc.b $7
	dc.b $EB, $D, $0, $0, $E3
	dc.b $F3, $2, $0, $8, $3
	dc.b $FB, $8, $0, $B, $EB
	dc.b $FB, $5, $0, $E, $B
	dc.b $3, $4, $0, $12, $F3
	dc.b $B, $1, $0, $14, $FB
	dc.b $B, $0, $0, $16, $B
DATA6MFUDJ5DSJF_9F: dc.b $4
	dc.b $F0, $E, $0, $0, $E6
	dc.b $8, $C, $0, $C, $EE
	dc.b $10, $4, $0, $10, $FE
	dc.b $8, $0, $0, $12, $E
DATA6MFUDJ5DSJF_A0: dc.b $7
	dc.b $E7, $3, $0, $0, $F2
	dc.b $EF, $2, $0, $4, $EA
	dc.b $EF, $7, $0, $7, $FA
	dc.b $F7, $0, $0, $F, $E2
	dc.b $FF, $2, $0, $10, $A
	dc.b $7, $0, $0, $13, $12
	dc.b $F, $4, $0, $14, $FA
DATA6MFUDJ5DSJF_A1: dc.b $5
	dc.b $F4, $F, $0, $0, $E7
	dc.b $EC, $8, $0, $10, $F7
	dc.b $F4, $4, $0, $13, $7
	dc.b $4, $1, $0, $15, $7
	dc.b $C, $1, $0, $17, $F
DATA6MFUDJ5DSJF_A2: dc.b $4
	dc.b $F8, $E, $0, $0, $E4
	dc.b $F0, $8, $0, $C, $EC
	dc.b $F8, $6, $0, $F, $4
	dc.b $E8, $1, $0, $15, $C
DATA6MFUDJ5DSJF_A3: dc.b $2
	dc.b $F2, $B, $0, $0, $E8
	dc.b $FA, $9, $0, $C, $0
DATA6MFUDJ5DSJF_A4: dc.b $4
	dc.b $F4, $E, $0, $0, $E4
	dc.b $EC, $0, $0, $C, $FC
	dc.b $C, $8, $0, $D, $FC
	dc.b $F4, $6, $0, $10, $4
DATA6MFUDJ5DSJF_A5: dc.b $4
	dc.b $ED, $9, $0, $0, $FB
	dc.b $F5, $A, $0, $6, $E3
	dc.b $FD, $6, $0, $F, $FB
	dc.b $5, $1, $0, $15, $B
DATA6MFUDJ5DSJF_A6: dc.b $4
	dc.b $F3, $E, $0, $0, $E6
	dc.b $EB, $6, $0, $C, $6
	dc.b $3, $1, $0, $12, $6
	dc.b $B, $0, $0, $14, $E
DATA6MFUDJ5DSJF_A7: dc.b $4
	dc.b $F5, $E, $0, $0, $E8
	dc.b $ED, $0, $0, $C, $F8
	dc.b $FD, $5, $0, $D, $8
	dc.b $F5, $0, $0, $11, $10
DATA6MFUDJ5DSJF_A8: dc.b $3
	dc.b $F6, $E, $0, $0, $E7
	dc.b $EE, $4, $0, $C, $EF
	dc.b $F6, $6, $0, $E, $7
DATA6MFUDJ5DSJF_A9: dc.b $5
	dc.b $F7, $B, $0, $0, $ED
	dc.b $17, $8, $0, $C, $ED
	dc.b $EF, $8, $0, $F, $F5
	dc.b $FF, $8, $0, $12, $5
	dc.b $7, $1, $0, $15, $5
DATA6MFUDJ5DSJF_AA: dc.b $6
	dc.b $F9, $E, $0, $0, $EC
	dc.b $11, $8, $0, $C, $EC
	dc.b $19, $0, $0, $F, $F4
	dc.b $E9, $5, $0, $10, $FC
	dc.b $F1, $1, $0, $14, $C
	dc.b $F9, $0, $0, $16, $14
DATA6MFUDJ5DSJF_AB: dc.b $4
	dc.b $EF, $5, $0, $0, $5
	dc.b $F7, $B, $0, $4, $ED
	dc.b $FF, $1, $0, $10, $5
	dc.b $17, $0, $0, $12, $F5
DATA6MFUDJ5DSJF_AC: dc.b $7
	dc.b $FE, $E, $0, $0, $EA
	dc.b $F6, $C, $0, $C, $F2
	dc.b $16, $4, $0, $10, $F2
	dc.b $EE, $0, $0, $12, $2
	dc.b $FE, $4, $0, $13, $A
	dc.b $6, $0, $0, $15, $A
	dc.b $F6, $0, $0, $16, $12
DATA6MFUDJ5DSJF_AD: dc.b $5
	dc.b $FD, $E, $0, $0, $ED
	dc.b $15, $4, $0, $C, $ED
	dc.b $ED, $9, $0, $E, $F5
	dc.b $FD, $2, $0, $14, $D
	dc.b $FD, $0, $0, $17, $15
DATA6MFUDJ5DSJF_AE: dc.b $7
	dc.b $0, $A, $0, $0, $ED
	dc.b $18, $4, $0, $9, $ED
	dc.b $F8, $8, $0, $B, $F5
	dc.b $E8, $5, $0, $E, $FD
	dc.b $0, $8, $0, $12, $5
	dc.b $8, $0, $0, $15, $5
	dc.b $F0, $0, $0, $16, $D
DATA6MFUDJ5DSJF_AF: dc.b $4
	dc.b $F8, $E, $0, $0, $ED
	dc.b $10, $8, $0, $C, $ED
	dc.b $E8, $1, $0, $F, $5
	dc.b $F0, $1, $0, $11, $D
DATA6MFUDJ5DSJF_B0: dc.b $7
	dc.b $8, $C, $0, $0, $E6
	dc.b $F8, $D, $0, $4, $EE
	dc.b $10, $8, $0, $C, $EE
	dc.b $18, $0, $0, $F, $F6
	dc.b $F0, $8, $0, $10, $FE
	dc.b $E8, $0, $0, $13, $6
	dc.b $F8, $1, $0, $14, $E
DATA6MFUDJ5DSJF_B1: dc.b $5
	dc.b $0, $9, $0, $0, $EC
	dc.b $F8, $C, $0, $6, $F4
	dc.b $E8, $5, $0, $A, $FC
	dc.b $0, $4, $0, $E, $4
	dc.b $F0, $0, $0, $10, $C
DATA6MFUDJ5DSJF_B2: dc.b $3
	dc.b $F8, $A, $0, $0, $EF
	dc.b $E8, $5, $0, $9, $F7
	dc.b $F0, $6, $0, $D, $7
DATA6MFUDJ5DSJF_B3: dc.b $3
	dc.b $F8, $A, $0, $0, $EE
	dc.b $E8, $5, $0, $9, $F6
	dc.b $F0, $6, $0, $D, $6
DATA6MFUDJ5DSJF_B4: dc.b $3
	dc.b $0, $9, $0, $0, $EC
	dc.b $F0, $D, $0, $6, $F4
	dc.b $0, $4, $0, $E, $4
DATA6MFUDJ5DSJF_B5: dc.b $4
	dc.b $E7, $B, $0, $0, $F9
	dc.b $EF, $1, $0, $C, $F1
	dc.b $7, $C, $0, $E, $F1
	dc.b $F, $4, $0, $12, $F9
DATA6MFUDJ5DSJF_B6: dc.b $4
	dc.b $E7, $B, $0, $0, $F9
	dc.b $EF, $1, $0, $C, $F1
	dc.b $7, $C, $0, $E, $F1
	dc.b $F, $4, $0, $12, $F9
DATA6MFUDJ5DSJF_B7: dc.b $3
	dc.b $EB, $E, $0, $0, $F3
	dc.b $3, $9, $0, $C, $F3
	dc.b $13, $0, $0, $12, $FB
DATA6MFUDJ5DSJF_B8: dc.b $3
	dc.b $EA, $E, $0, $0, $F3
	dc.b $2, $9, $0, $C, $F3
	dc.b $12, $0, $0, $12, $FB
DATA6MFUDJ5DSJF_B9: dc.b $5
	dc.b $F3, $D, $0, $0, $E8
	dc.b $EB, $8, $0, $8, $F0
	dc.b $3, $8, $0, $B, $F8
	dc.b $B, $4, $0, $E, $0
	dc.b $FB, $0, $0, $10, $8
DATA6MFUDJ5DSJF_BA: dc.b $4
	dc.b $E8, $B, $0, $0, $ED
	dc.b $8, $8, $0, $C, $FD
	dc.b $F0, $2, $0, $F, $5
	dc.b $0, $0, $0, $12, $D
DATA6MFUDJ5DSJF_BB: dc.b $4
	dc.b $EB, $B, $0, $0, $EF
	dc.b $B, $8, $0, $C, $FF
	dc.b $F3, $2, $0, $F, $7
	dc.b $3, $0, $0, $12, $F
DATA6MFUDJ5DSJF_BC: dc.b $3
	dc.b $EB, $B, $0, $0, $F0
	dc.b $B, $4, $0, $C, $0
	dc.b $FB, $1, $0, $E, $8
DATA6MFUDJ5DSJF_BD: dc.b $3
	dc.b $EF, $B, $0, $0, $E9
	dc.b $F7, $6, $0, $C, $1
	dc.b $FF, $0, $0, $12, $11
DATA6MFUDJ5DSJF_BE: dc.b $3
	dc.b $EE, $B, $0, $0, $E9
	dc.b $F6, $6, $0, $C, $1
	dc.b $FE, $0, $0, $12, $11
DATA6MFUDJ5DSJF_BF: dc.b $4
	dc.b $ED, $B, $0, $0, $E9
	dc.b $D, $0, $0, $C, $F1
	dc.b $F5, $6, $0, $D, $1
	dc.b $FD, $0, $0, $13, $11
DATA6MFUDJ5DSJF_C0: dc.b $4
	dc.b $EE, $B, $0, $0, $E9
	dc.b $E, $0, $0, $C, $F1
	dc.b $F6, $6, $0, $D, $1
	dc.b $FE, $0, $0, $13, $11
	even