; ================================================================================
; Sprite Mappings - generated by Flex 2 Fri Nov 15 2019 13:37:36 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAP3584RZLR4B:
	dc.w $0, DATAP3584RZLR4B_1-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_2-DATAP3584RZLR4B, DATAP3584RZLR4B_3-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_4-DATAP3584RZLR4B, DATAP3584RZLR4B_5-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_6-DATAP3584RZLR4B, DATAP3584RZLR4B_7-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_8-DATAP3584RZLR4B, DATAP3584RZLR4B_9-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_A-DATAP3584RZLR4B, DATAP3584RZLR4B_B-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_C-DATAP3584RZLR4B, DATAP3584RZLR4B_D-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_E-DATAP3584RZLR4B, DATAP3584RZLR4B_F-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_10-DATAP3584RZLR4B, DATAP3584RZLR4B_11-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_12-DATAP3584RZLR4B, DATAP3584RZLR4B_13-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_14-DATAP3584RZLR4B, DATAP3584RZLR4B_15-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_16-DATAP3584RZLR4B, DATAP3584RZLR4B_17-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_18-DATAP3584RZLR4B, DATAP3584RZLR4B_19-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_1A-DATAP3584RZLR4B, DATAP3584RZLR4B_1B-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_1C-DATAP3584RZLR4B, DATAP3584RZLR4B_1D-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_1E-DATAP3584RZLR4B, DATAP3584RZLR4B_1F-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_20-DATAP3584RZLR4B, DATAP3584RZLR4B_21-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_22-DATAP3584RZLR4B, DATAP3584RZLR4B_23-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_24-DATAP3584RZLR4B, DATAP3584RZLR4B_25-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_26-DATAP3584RZLR4B, DATAP3584RZLR4B_27-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_28-DATAP3584RZLR4B, DATAP3584RZLR4B_29-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_2A-DATAP3584RZLR4B, DATAP3584RZLR4B_2B-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_2C-DATAP3584RZLR4B, DATAP3584RZLR4B_2D-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_2E-DATAP3584RZLR4B, DATAP3584RZLR4B_2F-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_30-DATAP3584RZLR4B, DATAP3584RZLR4B_31-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_32-DATAP3584RZLR4B, DATAP3584RZLR4B_33-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_34-DATAP3584RZLR4B, DATAP3584RZLR4B_35-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_36-DATAP3584RZLR4B, DATAP3584RZLR4B_37-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_38-DATAP3584RZLR4B, DATAP3584RZLR4B_39-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_3A-DATAP3584RZLR4B, DATAP3584RZLR4B_3B-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_3C-DATAP3584RZLR4B, DATAP3584RZLR4B_3D-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_3E-DATAP3584RZLR4B, DATAP3584RZLR4B_3F-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_40-DATAP3584RZLR4B, DATAP3584RZLR4B_41-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_42-DATAP3584RZLR4B, DATAP3584RZLR4B_43-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_44-DATAP3584RZLR4B, DATAP3584RZLR4B_45-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_46-DATAP3584RZLR4B, DATAP3584RZLR4B_47-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_48-DATAP3584RZLR4B, DATAP3584RZLR4B_49-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_4A-DATAP3584RZLR4B, DATAP3584RZLR4B_4B-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_4C-DATAP3584RZLR4B, DATAP3584RZLR4B_4D-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_4E-DATAP3584RZLR4B, DATAP3584RZLR4B_4F-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_50-DATAP3584RZLR4B, DATAP3584RZLR4B_51-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_52-DATAP3584RZLR4B, DATAP3584RZLR4B_53-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_54-DATAP3584RZLR4B, DATAP3584RZLR4B_55-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_56-DATAP3584RZLR4B, DATAP3584RZLR4B_57-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_58-DATAP3584RZLR4B, DATAP3584RZLR4B_59-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_5A-DATAP3584RZLR4B, DATAP3584RZLR4B_5B-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_5C-DATAP3584RZLR4B, DATAP3584RZLR4B_5D-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_5E-DATAP3584RZLR4B, DATAP3584RZLR4B_5F-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_60-DATAP3584RZLR4B, DATAP3584RZLR4B_61-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_62-DATAP3584RZLR4B, DATAP3584RZLR4B_63-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_64-DATAP3584RZLR4B, DATAP3584RZLR4B_65-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_66-DATAP3584RZLR4B, DATAP3584RZLR4B_67-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_68-DATAP3584RZLR4B, DATAP3584RZLR4B_69-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_6A-DATAP3584RZLR4B, DATAP3584RZLR4B_6B-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_6C-DATAP3584RZLR4B, DATAP3584RZLR4B_6D-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_6E-DATAP3584RZLR4B, DATAP3584RZLR4B_6F-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_70-DATAP3584RZLR4B, DATAP3584RZLR4B_71-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_72-DATAP3584RZLR4B, DATAP3584RZLR4B_73-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_74-DATAP3584RZLR4B, DATAP3584RZLR4B_75-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_76-DATAP3584RZLR4B, DATAP3584RZLR4B_77-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_78-DATAP3584RZLR4B, DATAP3584RZLR4B_79-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_7A-DATAP3584RZLR4B, DATAP3584RZLR4B_7B-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_7C-DATAP3584RZLR4B, DATAP3584RZLR4B_7D-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_7E-DATAP3584RZLR4B, DATAP3584RZLR4B_7F-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_80-DATAP3584RZLR4B, DATAP3584RZLR4B_81-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_82-DATAP3584RZLR4B, DATAP3584RZLR4B_83-DATAP3584RZLR4B
	dc.w DATAP3584RZLR4B_84-DATAP3584RZLR4B
DATAP3584RZLR4B_1: dc.b $4
	dc.b $EC, $F, $0, $0, $ED
	dc.b $FC, $2, $0, $10, $D
	dc.b $C, $4, $0, $13, $ED
	dc.b $C, $0, $0, $15, $5
DATAP3584RZLR4B_2: dc.b $4
	dc.b $ED, $D, $0, $0, $ED
	dc.b $FD, $A, $0, $8, $F5
	dc.b $5, $1, $0, $11, $ED
	dc.b $5, $1, $0, $13, $D
DATAP3584RZLR4B_3: dc.b $2
	dc.b $EE, $D, $0, $0, $F2
	dc.b $FE, $A, $0, $8, $F2
DATAP3584RZLR4B_4: dc.b $3
	dc.b $EC, $B, $0, $0, $F2
	dc.b $F4, $3, $0, $C, $A
	dc.b $C, $8, $0, $10, $F2
DATAP3584RZLR4B_5: dc.b $4
	dc.b $EC, $F, $0, $0, $EE
	dc.b $FC, $1, $0, $10, $E
	dc.b $C, $4, $0, $12, $EE
	dc.b $C, $0, $0, $14, $6
DATAP3584RZLR4B_6: dc.b $5
	dc.b $ED, $D, $0, $0, $EE
	dc.b $FD, $9, $0, $8, $F6
	dc.b $5, $1, $0, $E, $EE
	dc.b $5, $1, $0, $10, $E
	dc.b $D, $0, $0, $12, $6
DATAP3584RZLR4B_7: dc.b $2
	dc.b $EE, $D, $0, $0, $F2
	dc.b $FE, $A, $0, $8, $F2
DATAP3584RZLR4B_8: dc.b $3
	dc.b $EC, $B, $0, $0, $F2
	dc.b $F4, $0, $0, $C, $A
	dc.b $C, $C, $0, $D, $F2
DATAP3584RZLR4B_9: dc.b $4
	dc.b $F0, $E, $0, $0, $EB
	dc.b $F0, $2, $0, $C, $B
	dc.b $8, $8, $0, $F, $F3
	dc.b $10, $5, $0, $12, $FB
DATAP3584RZLR4B_A: dc.b $4
	dc.b $F2, $E, $0, $0, $ED
	dc.b $FA, $5, $0, $C, $D
	dc.b $A, $8, $0, $10, $FD
	dc.b $12, $0, $0, $13, $FD
DATAP3584RZLR4B_B: dc.b $3
	dc.b $ED, $E, $0, $0, $EF
	dc.b $5, $C, $0, $C, $F7
	dc.b $D, $4, $0, $10, $7
DATAP3584RZLR4B_C: dc.b $4
	dc.b $ED, $E, $0, $0, $ED
	dc.b $FD, $5, $0, $C, $D
	dc.b $5, $8, $0, $10, $F5
	dc.b $D, $8, $0, $13, $FD
DATAP3584RZLR4B_D: dc.b $4
	dc.b $EE, $F, $0, $0, $ED
	dc.b $F6, $2, $0, $10, $D
	dc.b $E, $8, $0, $13, $ED
	dc.b $16, $4, $0, $16, $FD
DATAP3584RZLR4B_E: dc.b $4
	dc.b $ED, $A, $0, $0, $ED
	dc.b $F5, $A, $0, $9, $5
	dc.b $5, $5, $0, $12, $F5
	dc.b $15, $0, $0, $16, $FD
DATAP3584RZLR4B_F: dc.b $3
	dc.b $F1, $E, $0, $0, $EC
	dc.b $9, $C, $0, $C, $F4
	dc.b $11, $4, $0, $10, $FC
DATAP3584RZLR4B_10: dc.b $3
	dc.b $F2, $E, $0, $0, $EC
	dc.b $2, $2, $0, $C, $C
	dc.b $A, $5, $0, $F, $FC
DATAP3584RZLR4B_11: dc.b $5
	dc.b $ED, $9, $0, $0, $FC
	dc.b $F5, $7, $0, $6, $EC
	dc.b $FD, $5, $0, $E, $FC
	dc.b $5, $1, $0, $12, $C
	dc.b $D, $0, $0, $14, $4
DATAP3584RZLR4B_12: dc.b $5
	dc.b $ED, $5, $0, $0, $5
	dc.b $F5, $A, $0, $4, $ED
	dc.b $FD, $2, $0, $D, $5
	dc.b $5, $1, $0, $10, $D
	dc.b $D, $4, $0, $12, $ED
DATAP3584RZLR4B_13: dc.b $3
	dc.b $F5, $E, $0, $0, $EE
	dc.b $F5, $2, $0, $C, $E
	dc.b $D, $0, $0, $F, $F6
DATAP3584RZLR4B_14: dc.b $2
	dc.b $F3, $F, $0, $0, $EC
	dc.b $F3, $3, $0, $10, $C
DATAP3584RZLR4B_15: dc.b $5
	dc.b $EE, $D, $0, $0, $F4
	dc.b $F6, $2, $0, $8, $EC
	dc.b $FE, $9, $0, $B, $F4
	dc.b $6, $1, $0, $11, $C
	dc.b $E, $4, $0, $13, $FC
DATAP3584RZLR4B_16: dc.b $6
	dc.b $ED, $9, $0, $0, $FD
	dc.b $F5, $6, $0, $6, $ED
	dc.b $FD, $5, $0, $C, $FD
	dc.b $5, $1, $0, $10, $D
	dc.b $D, $0, $0, $12, $F5
	dc.b $D, $0, $0, $13, $5
DATAP3584RZLR4B_17: dc.b $3
	dc.b $F5, $E, $0, $0, $EE
	dc.b $F5, $2, $0, $C, $E
	dc.b $D, $0, $0, $F, $F6
DATAP3584RZLR4B_18: dc.b $3
	dc.b $F5, $E, $0, $0, $EC
	dc.b $F5, $2, $0, $C, $C
	dc.b $D, $4, $0, $F, $EC
DATAP3584RZLR4B_19: dc.b $4
	dc.b $EF, $B, $0, $0, $F1
	dc.b $F7, $9, $0, $C, $9
	dc.b $7, $0, $0, $12, $9
	dc.b $F, $8, $0, $13, $F1
DATAP3584RZLR4B_1A: dc.b $5
	dc.b $EA, $8, $0, $0, $F8
	dc.b $F2, $7, $0, $3, $F8
	dc.b $FA, $3, $0, $B, $F0
	dc.b $FA, $5, $0, $F, $8
	dc.b $12, $0, $0, $13, $F8
DATAP3584RZLR4B_1B: dc.b $3
	dc.b $EF, $5, $0, $0, $7
	dc.b $F7, $B, $0, $4, $EF
	dc.b $FF, $1, $0, $10, $7
DATAP3584RZLR4B_1C: dc.b $6
	dc.b $ED, $7, $0, $0, $0
	dc.b $F5, $3, $0, $8, $F8
	dc.b $F5, $1, $0, $C, $10
	dc.b $FD, $2, $0, $E, $F0
	dc.b $D, $0, $0, $11, $0
	dc.b $15, $0, $0, $12, $F8
DATAP3584RZLR4B_1D: dc.b $4
	dc.b $EE, $F, $0, $0, $EF
	dc.b $F6, $1, $0, $10, $17
	dc.b $FE, $1, $0, $12, $F
	dc.b $E, $C, $0, $14, $EF
DATAP3584RZLR4B_1E: dc.b $5
	dc.b $EC, $8, $0, $0, $F8
	dc.b $F4, $7, $0, $3, $F8
	dc.b $FC, $2, $0, $B, $F0
	dc.b $FC, $9, $0, $E, $8
	dc.b $14, $0, $0, $14, $F8
DATAP3584RZLR4B_1F: dc.b $3
	dc.b $EF, $5, $0, $0, $8
	dc.b $F7, $B, $0, $4, $F0
	dc.b $FF, $1, $0, $10, $8
DATAP3584RZLR4B_20: dc.b $3
	dc.b $EE, $A, $0, $0, $2
	dc.b $F6, $7, $0, $9, $F2
	dc.b $6, $1, $0, $11, $2
DATAP3584RZLR4B_21: dc.b $2
	dc.b $F0, $F, $0, $0, $F0
	dc.b $10, $C, $0, $10, $F0
DATAP3584RZLR4B_22: dc.b $3
	dc.b $F0, $B, $0, $0, $F8
	dc.b $F8, $3, $0, $C, $F0
	dc.b $10, $8, $0, $10, $F8
DATAP3584RZLR4B_23: dc.b $2
	dc.b $F0, $F, $0, $0, $F1
	dc.b $10, $8, $0, $10, $F1
DATAP3584RZLR4B_24: dc.b $3
	dc.b $F0, $B, $0, $0, $F8
	dc.b $F8, $3, $0, $C, $F0
	dc.b $10, $8, $0, $10, $F8
DATAP3584RZLR4B_25: dc.b $3
	dc.b $EF, $E, $0, $0, $ED
	dc.b $FF, $1, $0, $C, $D
	dc.b $7, $9, $0, $E, $F5
DATAP3584RZLR4B_26: dc.b $3
	dc.b $EE, $B, $0, $0, $F0
	dc.b $F6, $3, $0, $C, $8
	dc.b $E, $8, $0, $10, $F0
DATAP3584RZLR4B_27: dc.b $3
	dc.b $EF, $E, $0, $0, $ED
	dc.b $FF, $1, $0, $C, $D
	dc.b $7, $9, $0, $E, $F5
DATAP3584RZLR4B_28: dc.b $3
	dc.b $EE, $B, $0, $0, $F0
	dc.b $F6, $3, $0, $C, $8
	dc.b $E, $8, $0, $10, $F0
DATAP3584RZLR4B_29: dc.b $2
	dc.b $F0, $F, $0, $0, $F0
	dc.b $F0, $3, $0, $10, $10
DATAP3584RZLR4B_2A: dc.b $3
	dc.b $F0, $E, $0, $0, $F0
	dc.b $F0, $3, $0, $C, $10
	dc.b $8, $8, $0, $10, $F8
DATAP3584RZLR4B_2B: dc.b $2
	dc.b $F0, $F, $0, $0, $F0
	dc.b $F0, $3, $0, $10, $10
DATAP3584RZLR4B_2C: dc.b $3
	dc.b $F0, $E, $0, $0, $F0
	dc.b $F0, $3, $0, $C, $10
	dc.b $8, $8, $0, $10, $F8
DATAP3584RZLR4B_2D: dc.b $3
	dc.b $EE, $F, $0, $0, $F6
	dc.b $F6, $2, $0, $10, $EE
	dc.b $E, $0, $0, $13, $F6
DATAP3584RZLR4B_2E: dc.b $2
	dc.b $EF, $F, $0, $0, $F5
	dc.b $F7, $2, $0, $10, $ED
DATAP3584RZLR4B_2F: dc.b $4
	dc.b $EF, $E, $0, $0, $EE
	dc.b $EF, $2, $0, $C, $E
	dc.b $7, $8, $0, $F, $EE
	dc.b $F, $0, $0, $12, $F6
DATAP3584RZLR4B_30: dc.b $2
	dc.b $EF, $F, $0, $0, $F5
	dc.b $F7, $2, $0, $10, $ED
DATAP3584RZLR4B_31: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATAP3584RZLR4B_32: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATAP3584RZLR4B_33: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATAP3584RZLR4B_34: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATAP3584RZLR4B_35: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATAP3584RZLR4B_36: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATAP3584RZLR4B_37: dc.b $3
	dc.b $F0, $E, $0, $0, $ED
	dc.b $F0, $2, $0, $C, $D
	dc.b $8, $8, $0, $F, $F5
DATAP3584RZLR4B_38: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $F0, $2, $0, $C, $C
	dc.b $8, $8, $0, $F, $F4
DATAP3584RZLR4B_39: dc.b $2
	dc.b $EB, $A, $0, $0, $F1
	dc.b $3, $6, $0, $9, $F9
DATAP3584RZLR4B_3A: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAP3584RZLR4B_3B: dc.b $2
	dc.b $F1, $E, $0, $0, $F1
	dc.b $9, $8, $0, $C, $F1
DATAP3584RZLR4B_3C: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAP3584RZLR4B_3D: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAP3584RZLR4B_3E: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAP3584RZLR4B_3F: dc.b $2
	dc.b $F2, $B, $0, $0, $F8
	dc.b $12, $8, $0, $C, $F8
DATAP3584RZLR4B_40: dc.b $2
	dc.b $FA, $B, $0, $0, $F7
	dc.b $2, $1, $0, $C, $F
DATAP3584RZLR4B_41: dc.b $4
	dc.b $EE, $B, $0, $0, $F5
	dc.b $F6, $1, $0, $C, $ED
	dc.b $FE, $2, $0, $E, $D
	dc.b $E, $4, $0, $11, $FD
DATAP3584RZLR4B_42: dc.b $4
	dc.b $EE, $B, $0, $0, $F6
	dc.b $F6, $1, $0, $C, $EE
	dc.b $FE, $1, $0, $E, $E
	dc.b $E, $4, $0, $10, $FE
DATAP3584RZLR4B_43: dc.b $3
	dc.b $EF, $B, $0, $0, $F9
	dc.b $F7, $1, $0, $C, $F1
	dc.b $F, $4, $0, $E, $1
DATAP3584RZLR4B_44: dc.b $4
	dc.b $EB, $A, $0, $0, $ED
	dc.b $3, $9, $0, $9, $F5
	dc.b $F3, $1, $0, $F, $5
	dc.b $B, $1, $0, $11, $D
DATAP3584RZLR4B_45: dc.b $3
	dc.b $EC, $D, $0, $0, $EB
	dc.b $EC, $0, $0, $8, $B
	dc.b $FC, $A, $0, $9, $EB
DATAP3584RZLR4B_46: dc.b $5
	dc.b $EA, $E, $0, $0, $EA
	dc.b $FA, $0, $0, $C, $A
	dc.b $2, $8, $0, $D, $F2
	dc.b $A, $8, $0, $10, $EA
	dc.b $12, $4, $0, $13, $F2
DATAP3584RZLR4B_47: dc.b $4
	dc.b $EA, $A, $0, $0, $EB
	dc.b $F2, $2, $0, $9, $3
	dc.b $2, $6, $0, $C, $F3
	dc.b $A, $0, $0, $12, $EB
DATAP3584RZLR4B_48: dc.b $4
	dc.b $EC, $B, $0, $0, $F8
	dc.b $F4, $3, $0, $C, $F0
	dc.b $F4, $0, $0, $10, $10
	dc.b $C, $8, $0, $11, $F8
DATAP3584RZLR4B_49: dc.b $3
	dc.b $EE, $F, $0, $0, $F0
	dc.b $F6, $0, $0, $10, $10
	dc.b $E, $C, $0, $11, $F0
DATAP3584RZLR4B_4A: dc.b $3
	dc.b $EE, $F, $0, $0, $F0
	dc.b $F6, $0, $0, $10, $10
	dc.b $E, $C, $0, $11, $F0
DATAP3584RZLR4B_4B: dc.b $3
	dc.b $F4, $E, $0, $0, $E6
	dc.b $F4, $2, $0, $C, $6
	dc.b $FC, $5, $0, $F, $E
DATAP3584RZLR4B_4C: dc.b $3
	dc.b $F4, $E, $0, $0, $E6
	dc.b $F4, $2, $0, $C, $6
	dc.b $FC, $5, $0, $F, $E
DATAP3584RZLR4B_4D: dc.b $3
	dc.b $EC, $F, $0, $0, $EF
	dc.b $4, $0, $0, $10, $F
	dc.b $C, $C, $0, $11, $EF
DATAP3584RZLR4B_4E: dc.b $5
	dc.b $ED, $A, $0, $0, $EE
	dc.b $5, $0, $0, $9, $F6
	dc.b $F5, $0, $0, $A, $6
	dc.b $5, $0, $0, $B, $FE
	dc.b $D, $8, $0, $C, $F6
DATAP3584RZLR4B_4F: dc.b $5
	dc.b $F5, $0, $0, $0, $6
	dc.b $ED, $A, $0, $1, $EE
	dc.b $5, $0, $0, $A, $FE
	dc.b $5, $0, $0, $B, $F6
	dc.b $D, $8, $0, $C, $F6
DATAP3584RZLR4B_50: dc.b $3
	dc.b $EE, $B, $0, $0, $ED
	dc.b $F6, $2, $0, $C, $5
	dc.b $D, $8, $0, $F, $F6
DATAP3584RZLR4B_51: dc.b $4
	dc.b $EF, $B, $0, $0, $F9
	dc.b $F7, $0, $0, $C, $F1
	dc.b $7, $1, $0, $D, $F1
	dc.b $F, $8, $0, $F, $F9
DATAP3584RZLR4B_52: dc.b $2
	dc.b $EF, $B, $0, $0, $F5
	dc.b $F, $4, $0, $C, $F5
DATAP3584RZLR4B_53: dc.b $4
	dc.b $EF, $B, $0, $0, $F9
	dc.b $F7, $0, $0, $C, $F1
	dc.b $7, $1, $0, $D, $F1
	dc.b $F, $4, $0, $F, $F9
DATAP3584RZLR4B_54: dc.b $2
	dc.b $EF, $B, $0, $0, $F5
	dc.b $F, $4, $0, $C, $F5
DATAP3584RZLR4B_55: dc.b $3
	dc.b $ED, $A, $0, $0, $F0
	dc.b $F5, $3, $0, $9, $8
	dc.b $5, $5, $0, $D, $F8
DATAP3584RZLR4B_56: dc.b $5
	dc.b $ED, $B, $0, $0, $EF
	dc.b $D, $0, $0, $C, $F8
	dc.b $D, $0, $0, $D, $8
	dc.b $D, $0, $0, $E, $0
	dc.b $F5, $0, $0, $F, $7
DATAP3584RZLR4B_57: dc.b $A
	dc.b $FD, $0, $0, $0, $FE
	dc.b $F5, $0, $0, $1, $FE
	dc.b $D, $8, $0, $2, $F6
	dc.b $F5, $0, $0, $5, $6
	dc.b $ED, $3, $0, $6, $EE
	dc.b $ED, $1, $0, $A, $F6
	dc.b $FD, $0, $0, $C, $F6
	dc.b $5, $0, $0, $D, $F6
	dc.b $5, $0, $0, $E, $FE
	dc.b $ED, $0, $0, $F, $FE
DATAP3584RZLR4B_58: dc.b $3
	dc.b $ED, $B, $0, $0, $EE
	dc.b $D, $8, $0, $C, $F6
	dc.b $F5, $0, $0, $F, $6
DATAP3584RZLR4B_59: dc.b $7
	dc.b $F5, $0, $0, $0, $6
	dc.b $5, $0, $0, $1, $6
	dc.b $5, $0, $0, $2, $FE
	dc.b $D, $0, $0, $3, $6
	dc.b $D, $4, $0, $4, $F6
	dc.b $ED, $7, $0, $6, $EE
	dc.b $ED, $2, $0, $E, $FE
DATAP3584RZLR4B_5A: dc.b $3
	dc.b $EC, $A, $0, $0, $ED
	dc.b $F4, $3, $0, $9, $5
	dc.b $4, $5, $0, $D, $F5
DATAP3584RZLR4B_5B: dc.b $3
	dc.b $EE, $E, $0, $0, $EA
	dc.b $6, $9, $0, $C, $F2
	dc.b $E, $0, $0, $12, $A
DATAP3584RZLR4B_5C: dc.b $3
	dc.b $F4, $A, $8, $0, $FB
	dc.b $FC, $5, $8, $9, $EB
	dc.b $4, $0, $8, $D, $E3
DATAP3584RZLR4B_5D: dc.b $3
	dc.b $F4, $A, $8, $0, $F4
	dc.b $4, $0, $8, $9, $C
	dc.b $4, $0, $8, $A, $EC
DATAP3584RZLR4B_5E: dc.b $2
	dc.b $F4, $A, $0, $0, $F2
	dc.b $4, $0, $0, $9, $A
DATAP3584RZLR4B_5F: dc.b $3
	dc.b $F4, $A, $0, $0, $F3
	dc.b $4, $0, $0, $9, $EB
	dc.b $4, $0, $0, $A, $B
DATAP3584RZLR4B_60: dc.b $3
	dc.b $F4, $A, $0, $0, $EE
	dc.b $FC, $5, $0, $9, $6
	dc.b $4, $0, $0, $D, $16
DATAP3584RZLR4B_61: dc.b $2
	dc.b $F4, $E, $0, $0, $F0
	dc.b $4, $0, $0, $C, $10
DATAP3584RZLR4B_62: dc.b $2
	dc.b $F4, $A, $0, $0, $F2
	dc.b $4, $0, $0, $9, $A
DATAP3584RZLR4B_63: dc.b $2
	dc.b $F4, $E, $8, $0, $F1
	dc.b $4, $0, $8, $C, $E9
DATAP3584RZLR4B_64: dc.b $3
	dc.b $F4, $E, $0, $0, $E9
	dc.b $F4, $2, $0, $C, $9
	dc.b $C, $8, $0, $F, $F1
DATAP3584RZLR4B_65: dc.b $3
	dc.b $F4, $E, $0, $0, $E8
	dc.b $F4, $2, $0, $C, $8
	dc.b $C, $8, $0, $F, $F0
DATAP3584RZLR4B_66: dc.b $5
	dc.b $EE, $A, $0, $0, $EC
	dc.b $F6, $3, $0, $9, $4
	dc.b $FE, $0, $0, $D, $C
	dc.b $6, $5, $0, $E, $F4
	dc.b $E, $0, $0, $12, $C
DATAP3584RZLR4B_67: dc.b $4
	dc.b $EC, $B, $0, $0, $F4
	dc.b $C, $4, $0, $C, $F4
	dc.b $F2, $0, $0, $E, $C
	dc.b $14, $0, $0, $F, $F5
DATAP3584RZLR4B_68: dc.b $4
	dc.b $FC, $E, $0, $0, $F0
	dc.b $14, $0, $0, $C, $1
	dc.b $F7, $0, $0, $D, $10
	dc.b $EC, $9, $0, $E, $F8
DATAP3584RZLR4B_69: dc.b $3
	dc.b $F0, $B, $0, $0, $EC
	dc.b $F8, $2, $0, $C, $4
	dc.b $F8, $2, $0, $F, $C
DATAP3584RZLR4B_6A: dc.b $2
	dc.b $F1, $F, $0, $0, $F2
	dc.b $11, $C, $0, $10, $F2
DATAP3584RZLR4B_6B: dc.b $2
	dc.b $F4, $F, $0, $0, $F0
	dc.b $EC, $4, $0, $10, $F8
DATAP3584RZLR4B_6C: dc.b $2
	dc.b $F4, $F, $0, $0, $F0
	dc.b $EC, $4, $0, $10, $F8
DATAP3584RZLR4B_6D: dc.b $3
	dc.b $EC, $A, $0, $0, $EF
	dc.b $4, $6, $0, $9, $F7
	dc.b $F4, $1, $0, $F, $7
DATAP3584RZLR4B_6E: dc.b $3
	dc.b $E8, $B, $0, $0, $F0
	dc.b $8, $5, $0, $C, $F8
	dc.b $F8, $1, $0, $10, $8
DATAP3584RZLR4B_6F: dc.b $8
	dc.b $8, $5, $0, $0, $F8
	dc.b $F0, $0, $0, $4, $8
	dc.b $0, $0, $0, $5, $8
	dc.b $F0, $2, $0, $6, $F8
	dc.b $E8, $3, $0, $9, $0
	dc.b $F0, $2, $0, $D, $F0
	dc.b $E8, $0, $0, $10, $F8
	dc.b $E8, $0, $0, $11, $F0
DATAP3584RZLR4B_70: dc.b $9
	dc.b $8, $5, $0, $0, $F8
	dc.b $F0, $0, $0, $4, $8
	dc.b $0, $0, $0, $5, $8
	dc.b $F0, $2, $0, $6, $F8
	dc.b $E8, $3, $0, $9, $0
	dc.b $F8, $1, $0, $D, $F0
	dc.b $E8, $0, $0, $F, $F0
	dc.b $F0, $0, $0, $10, $F0
	dc.b $E8, $0, $0, $11, $F8
DATAP3584RZLR4B_71: dc.b $4
	dc.b $F0, $D, $0, $0, $EE
	dc.b $E8, $8, $0, $8, $F6
	dc.b $F0, $0, $0, $B, $E
	dc.b $FF, $6, $0, $C, $F7
DATAP3584RZLR4B_72: dc.b $4
	dc.b $E7, $A, $0, $0, $F7
	dc.b $EF, $0, $0, $9, $EF
	dc.b $EF, $0, $0, $A, $F
	dc.b $FF, $6, $0, $B, $F7
DATAP3584RZLR4B_73: dc.b $3
	dc.b $F4, $D, $0, $0, $EE
	dc.b $EC, $4, $0, $8, $F6
	dc.b $4, $9, $0, $A, $F6
DATAP3584RZLR4B_74: dc.b $3
	dc.b $F9, $F, $0, $0, $EE
	dc.b $F1, $C, $0, $10, $F6
	dc.b $F9, $1, $0, $14, $E
DATAP3584RZLR4B_75: dc.b $3
	dc.b $F1, $E, $0, $0, $F6
	dc.b $F9, $2, $0, $C, $EE
	dc.b $9, $9, $0, $F, $F6
DATAP3584RZLR4B_76: dc.b $3
	dc.b $F9, $F, $0, $0, $EE
	dc.b $F1, $C, $0, $10, $F6
	dc.b $F9, $1, $0, $14, $E
DATAP3584RZLR4B_77: dc.b $3
	dc.b $F1, $E, $0, $0, $F6
	dc.b $F9, $2, $0, $C, $EE
	dc.b $9, $9, $0, $F, $F6
DATAP3584RZLR4B_78: dc.b $4
	dc.b $EF, $F, $0, $0, $ED
	dc.b $F, $8, $0, $10, $F5
	dc.b $E7, $0, $0, $13, $FD
	dc.b $FF, $1, $0, $14, $D
DATAP3584RZLR4B_79: dc.b $4
	dc.b $F0, $F, $0, $0, $ED
	dc.b $10, $8, $0, $10, $F5
	dc.b $E8, $0, $0, $13, $FD
	dc.b $0, $1, $0, $14, $D
DATAP3584RZLR4B_7A: dc.b $4
	dc.b $F0, $F, $0, $0, $ED
	dc.b $10, $8, $0, $10, $F5
	dc.b $E8, $0, $0, $13, $FD
	dc.b $0, $1, $0, $14, $D
DATAP3584RZLR4B_7B: dc.b $4
	dc.b $F1, $F, $0, $0, $ED
	dc.b $11, $8, $0, $10, $F5
	dc.b $E9, $0, $0, $13, $FD
	dc.b $1, $1, $0, $14, $D
DATAP3584RZLR4B_7C: dc.b $4
	dc.b $ED, $F, $0, $0, $F1
	dc.b $D, $8, $0, $10, $F9
	dc.b $F5, $2, $0, $13, $11
	dc.b $E5, $0, $0, $16, $F9
DATAP3584RZLR4B_7D: dc.b $3
	dc.b $EA, $B, $0, $0, $F1
	dc.b $A, $8, $0, $C, $F9
	dc.b $F2, $6, $0, $F, $9
DATAP3584RZLR4B_7E: dc.b $4
	dc.b $ED, $F, $0, $0, $F1
	dc.b $D, $8, $0, $10, $F9
	dc.b $F5, $2, $0, $13, $11
	dc.b $E5, $0, $0, $16, $F9
DATAP3584RZLR4B_7F: dc.b $3
	dc.b $EA, $B, $0, $0, $F1
	dc.b $A, $8, $0, $C, $F9
	dc.b $F2, $6, $0, $F, $9
DATAP3584RZLR4B_80: dc.b $4
	dc.b $EE, $F, $0, $0, $ED
	dc.b $E, $0, $0, $10, $5
	dc.b $EE, $3, $0, $11, $D
	dc.b $F6, $1, $0, $15, $15
DATAP3584RZLR4B_81: dc.b $4
	dc.b $EE, $F, $0, $0, $EE
	dc.b $EE, $3, $0, $10, $E
	dc.b $F6, $0, $0, $14, $E6
	dc.b $E, $0, $0, $15, $6
DATAP3584RZLR4B_82: dc.b $4
	dc.b $EE, $F, $0, $0, $ED
	dc.b $E, $0, $0, $10, $5
	dc.b $EE, $2, $0, $11, $D
	dc.b $F6, $1, $0, $14, $15
DATAP3584RZLR4B_83: dc.b $4
	dc.b $EE, $F, $0, $0, $EE
	dc.b $EE, $3, $0, $10, $E
	dc.b $F6, $0, $0, $14, $E6
	dc.b $E, $0, $0, $15, $6
DATAP3584RZLR4B_84: dc.b $4
	dc.b $EC, $B, $0, $0, $F8
	dc.b $F4, $3, $0, $C, $F0
	dc.b $F4, $0, $0, $10, $10
	dc.b $C, $8, $0, $11, $F8
	even