; ================================================================================
; Sprite Mappings - generated by Flex 2 Sun Nov 24 2019 17:20:56 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAE1VS56T7VD:
	dc.w $0, DATAE1VS56T7VD_1-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_2-DATAE1VS56T7VD, DATAE1VS56T7VD_3-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_4-DATAE1VS56T7VD, DATAE1VS56T7VD_5-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_6-DATAE1VS56T7VD, DATAE1VS56T7VD_7-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_8-DATAE1VS56T7VD, DATAE1VS56T7VD_9-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_A-DATAE1VS56T7VD, DATAE1VS56T7VD_B-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_C-DATAE1VS56T7VD, DATAE1VS56T7VD_D-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_E-DATAE1VS56T7VD, DATAE1VS56T7VD_F-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_10-DATAE1VS56T7VD, DATAE1VS56T7VD_11-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_12-DATAE1VS56T7VD, DATAE1VS56T7VD_13-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_14-DATAE1VS56T7VD, DATAE1VS56T7VD_15-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_16-DATAE1VS56T7VD, DATAE1VS56T7VD_17-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_18-DATAE1VS56T7VD, DATAE1VS56T7VD_19-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_1A-DATAE1VS56T7VD, DATAE1VS56T7VD_1B-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_1C-DATAE1VS56T7VD, DATAE1VS56T7VD_1D-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_1E-DATAE1VS56T7VD, DATAE1VS56T7VD_1F-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_20-DATAE1VS56T7VD, DATAE1VS56T7VD_21-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_22-DATAE1VS56T7VD, DATAE1VS56T7VD_23-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_24-DATAE1VS56T7VD, DATAE1VS56T7VD_25-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_26-DATAE1VS56T7VD, DATAE1VS56T7VD_27-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_28-DATAE1VS56T7VD, DATAE1VS56T7VD_29-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_2A-DATAE1VS56T7VD, DATAE1VS56T7VD_2B-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_2C-DATAE1VS56T7VD, DATAE1VS56T7VD_2D-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_2E-DATAE1VS56T7VD, DATAE1VS56T7VD_2F-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_30-DATAE1VS56T7VD, DATAE1VS56T7VD_31-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_32-DATAE1VS56T7VD, DATAE1VS56T7VD_33-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_34-DATAE1VS56T7VD, DATAE1VS56T7VD_35-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_36-DATAE1VS56T7VD, DATAE1VS56T7VD_37-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_38-DATAE1VS56T7VD, DATAE1VS56T7VD_39-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_3A-DATAE1VS56T7VD, DATAE1VS56T7VD_3B-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_3C-DATAE1VS56T7VD, DATAE1VS56T7VD_3D-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_3E-DATAE1VS56T7VD, DATAE1VS56T7VD_3F-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_40-DATAE1VS56T7VD, DATAE1VS56T7VD_41-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_42-DATAE1VS56T7VD, DATAE1VS56T7VD_43-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_44-DATAE1VS56T7VD, DATAE1VS56T7VD_45-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_46-DATAE1VS56T7VD, DATAE1VS56T7VD_47-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_48-DATAE1VS56T7VD, DATAE1VS56T7VD_49-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_4A-DATAE1VS56T7VD, DATAE1VS56T7VD_4B-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_4C-DATAE1VS56T7VD, DATAE1VS56T7VD_4D-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_4E-DATAE1VS56T7VD, DATAE1VS56T7VD_4F-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_50-DATAE1VS56T7VD, DATAE1VS56T7VD_51-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_52-DATAE1VS56T7VD, DATAE1VS56T7VD_53-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_54-DATAE1VS56T7VD, DATAE1VS56T7VD_55-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_56-DATAE1VS56T7VD, DATAE1VS56T7VD_57-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_58-DATAE1VS56T7VD, DATAE1VS56T7VD_59-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_5A-DATAE1VS56T7VD, DATAE1VS56T7VD_5B-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_5C-DATAE1VS56T7VD, DATAE1VS56T7VD_5D-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_5E-DATAE1VS56T7VD, DATAE1VS56T7VD_5F-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_60-DATAE1VS56T7VD, DATAE1VS56T7VD_61-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_62-DATAE1VS56T7VD, DATAE1VS56T7VD_63-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_64-DATAE1VS56T7VD, DATAE1VS56T7VD_65-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_66-DATAE1VS56T7VD, DATAE1VS56T7VD_67-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_68-DATAE1VS56T7VD, DATAE1VS56T7VD_69-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_6A-DATAE1VS56T7VD, DATAE1VS56T7VD_6B-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_6C-DATAE1VS56T7VD, DATAE1VS56T7VD_6D-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_6E-DATAE1VS56T7VD, DATAE1VS56T7VD_6F-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_70-DATAE1VS56T7VD, DATAE1VS56T7VD_71-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_72-DATAE1VS56T7VD, DATAE1VS56T7VD_73-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_74-DATAE1VS56T7VD, DATAE1VS56T7VD_75-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_76-DATAE1VS56T7VD, DATAE1VS56T7VD_77-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_78-DATAE1VS56T7VD, DATAE1VS56T7VD_79-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_7A-DATAE1VS56T7VD, DATAE1VS56T7VD_7B-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_7C-DATAE1VS56T7VD, DATAE1VS56T7VD_7D-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_7E-DATAE1VS56T7VD, DATAE1VS56T7VD_7F-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_80-DATAE1VS56T7VD, DATAE1VS56T7VD_81-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_82-DATAE1VS56T7VD, DATAE1VS56T7VD_83-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_84-DATAE1VS56T7VD, DATAE1VS56T7VD_85-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_86-DATAE1VS56T7VD, DATAE1VS56T7VD_87-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_88-DATAE1VS56T7VD, DATAE1VS56T7VD_89-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_8A-DATAE1VS56T7VD, DATAE1VS56T7VD_8B-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_8C-DATAE1VS56T7VD, DATAE1VS56T7VD_8D-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_8E-DATAE1VS56T7VD, DATAE1VS56T7VD_8F-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_90-DATAE1VS56T7VD, DATAE1VS56T7VD_91-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_92-DATAE1VS56T7VD, DATAE1VS56T7VD_93-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_94-DATAE1VS56T7VD, DATAE1VS56T7VD_95-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_96-DATAE1VS56T7VD, DATAE1VS56T7VD_97-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_98-DATAE1VS56T7VD, DATAE1VS56T7VD_99-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_9A-DATAE1VS56T7VD, DATAE1VS56T7VD_9B-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_9C-DATAE1VS56T7VD, DATAE1VS56T7VD_9D-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_9E-DATAE1VS56T7VD, DATAE1VS56T7VD_9F-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_A0-DATAE1VS56T7VD, DATAE1VS56T7VD_A1-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_A2-DATAE1VS56T7VD, DATAE1VS56T7VD_A3-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_A4-DATAE1VS56T7VD, DATAE1VS56T7VD_A5-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_A6-DATAE1VS56T7VD, DATAE1VS56T7VD_A7-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_A8-DATAE1VS56T7VD, DATAE1VS56T7VD_A9-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_AA-DATAE1VS56T7VD, DATAE1VS56T7VD_AB-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_AC-DATAE1VS56T7VD, DATAE1VS56T7VD_AD-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_AE-DATAE1VS56T7VD, DATAE1VS56T7VD_AF-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_B0-DATAE1VS56T7VD, DATAE1VS56T7VD_B1-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_B2-DATAE1VS56T7VD, DATAE1VS56T7VD_B3-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_B4-DATAE1VS56T7VD, DATAE1VS56T7VD_B5-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_B6-DATAE1VS56T7VD, DATAE1VS56T7VD_B7-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_B8-DATAE1VS56T7VD, DATAE1VS56T7VD_B9-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_BA-DATAE1VS56T7VD, DATAE1VS56T7VD_BB-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_BC-DATAE1VS56T7VD, DATAE1VS56T7VD_BD-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_BE-DATAE1VS56T7VD, DATAE1VS56T7VD_BF-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_C0-DATAE1VS56T7VD, DATAE1VS56T7VD_C1-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_C2-DATAE1VS56T7VD, DATAE1VS56T7VD_C3-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_C4-DATAE1VS56T7VD, DATAE1VS56T7VD_C5-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_C6-DATAE1VS56T7VD, DATAE1VS56T7VD_C7-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_C8-DATAE1VS56T7VD, DATAE1VS56T7VD_C9-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_CA-DATAE1VS56T7VD, DATAE1VS56T7VD_CB-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_CC-DATAE1VS56T7VD, DATAE1VS56T7VD_CD-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_CE-DATAE1VS56T7VD, DATAE1VS56T7VD_CF-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_D0-DATAE1VS56T7VD, DATAE1VS56T7VD_D1-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_D2-DATAE1VS56T7VD, DATAE1VS56T7VD_D3-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_D4-DATAE1VS56T7VD, DATAE1VS56T7VD_D5-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_D6-DATAE1VS56T7VD, DATAE1VS56T7VD_D7-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_D8-DATAE1VS56T7VD, DATAE1VS56T7VD_D9-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_DA-DATAE1VS56T7VD, DATAE1VS56T7VD_DB-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_DC-DATAE1VS56T7VD, DATAE1VS56T7VD_DD-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_DE-DATAE1VS56T7VD, DATAE1VS56T7VD_DF-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_E0-DATAE1VS56T7VD, DATAE1VS56T7VD_E1-DATAE1VS56T7VD
	dc.w DATAE1VS56T7VD_E2-DATAE1VS56T7VD, DATAE1VS56T7VD_E3-DATAE1VS56T7VD
DATAE1VS56T7VD_1: dc.b $4
	dc.b $EC, $F, $0, $0, $ED
	dc.b $FA, $2, $0, $10, $D
	dc.b $C, $4, $0, $13, $EC
	dc.b $C, $0, $0, $15, $5
DATAE1VS56T7VD_2: dc.b $4
	dc.b $EC, $B, $0, $0, $F2
	dc.b $C, $C, $0, $C, $F2
	dc.b $F4, $1, $0, $10, $A
	dc.b $C, $0, $0, $12, $12
DATAE1VS56T7VD_3: dc.b $2
	dc.b $ED, $D, $0, $0, $F2
	dc.b $FD, $A, $0, $8, $F2
DATAE1VS56T7VD_4: dc.b $4
	dc.b $EC, $B, $0, $0, $F0
	dc.b $F4, $3, $0, $C, $8
	dc.b $C, $8, $0, $10, $F0
	dc.b $EC, $0, $0, $13, $8
DATAE1VS56T7VD_5: dc.b $4
	dc.b $EC, $F, $0, $0, $ED
	dc.b $FC, $1, $0, $10, $D
	dc.b $C, $4, $0, $12, $ED
	dc.b $C, $0, $0, $14, $6
DATAE1VS56T7VD_6: dc.b $5
	dc.b $FC, $9, $0, $0, $F5
	dc.b $4, $1, $0, $6, $ED
	dc.b $8, $0, $0, $8, $D
	dc.b $EC, $9, $0, $9, $F4
	dc.b $C, $8, $0, $F, $F5
DATAE1VS56T7VD_7: dc.b $3
	dc.b $FD, $A, $0, $0, $F2
	dc.b $ED, $9, $0, $9, $F3
	dc.b $F5, $0, $0, $F, $B
DATAE1VS56T7VD_8: dc.b $3
	dc.b $EC, $B, $0, $0, $F3
	dc.b $F4, $0, $0, $C, $B
	dc.b $C, $8, $0, $D, $F3
DATAE1VS56T7VD_9: dc.b $4
	dc.b $EE, $E, $0, $0, $EB
	dc.b $6, $4, $0, $C, $F3
	dc.b $E, $1, $0, $E, $FB
	dc.b $F6, $1, $0, $10, $B
DATAE1VS56T7VD_A: dc.b $5
	dc.b $F2, $D, $0, $0, $E9
	dc.b $FA, $6, $0, $8, $9
	dc.b $2, $8, $0, $E, $F1
	dc.b $A, $4, $0, $11, $F9
	dc.b $12, $4, $0, $13, $1
DATAE1VS56T7VD_B: dc.b $5
	dc.b $F5, $C, $0, $0, $E9
	dc.b $ED, $8, $0, $4, $F1
	dc.b $FD, $C, $0, $7, $F1
	dc.b $5, $C, $0, $B, $F9
	dc.b $D, $4, $0, $F, $1
DATAE1VS56T7VD_C: dc.b $4
	dc.b $ED, $E, $0, $0, $ED
	dc.b $5, $C, $0, $C, $F5
	dc.b $D, $4, $0, $10, $FD
	dc.b $FD, $0, $0, $12, $D
DATAE1VS56T7VD_D: dc.b $5
	dc.b $F0, $E, $0, $0, $ED
	dc.b $8, $8, $0, $C, $ED
	dc.b $E8, $0, $0, $F, $F5
	dc.b $10, $1, $0, $10, $FD
	dc.b $F0, $2, $0, $12, $D
DATAE1VS56T7VD_E: dc.b $5
	dc.b $F3, $E, $0, $0, $EC
	dc.b $EB, $4, $0, $C, $F4
	dc.b $B, $1, $0, $E, $FC
	dc.b $FB, $5, $0, $10, $C
	dc.b $B, $0, $0, $14, $C
DATAE1VS56T7VD_F: dc.b $5
	dc.b $F9, $C, $0, $0, $E5
	dc.b $F1, $8, $0, $4, $ED
	dc.b $1, $C, $0, $7, $ED
	dc.b $9, $C, $0, $B, $F5
	dc.b $11, $4, $0, $F, $FD
DATAE1VS56T7VD_10: dc.b $5
	dc.b $EF, $A, $0, $0, $F1
	dc.b $F7, $0, $0, $9, $E9
	dc.b $FF, $5, $0, $A, $9
	dc.b $7, $4, $0, $E, $F9
	dc.b $F, $4, $0, $10, $1
DATAE1VS56T7VD_11: dc.b $4
	dc.b $F2, $F, $0, $0, $EC
	dc.b $EA, $4, $0, $10, $FC
	dc.b $F2, $0, $0, $12, $C
	dc.b $A, $1, $0, $13, $C
DATAE1VS56T7VD_12: dc.b $4
	dc.b $F6, $E, $0, $0, $EC
	dc.b $E, $0, $0, $C, $F4
	dc.b $EE, $3, $0, $D, $C
	dc.b $EE, $0, $0, $11, $FB
DATAE1VS56T7VD_13: dc.b $2
	dc.b $F2, $B, $0, $0, $ED
	dc.b $FA, $5, $0, $C, $5
DATAE1VS56T7VD_14: dc.b $2
	dc.b $F2, $F, $0, $0, $EC
	dc.b $F2, $3, $0, $10, $C
DATAE1VS56T7VD_15: dc.b $4
	dc.b $EE, $9, $0, $0, $FC
	dc.b $F6, $6, $0, $6, $EC
	dc.b $FE, $6, $0, $C, $FC
	dc.b $6, $1, $0, $12, $C
DATAE1VS56T7VD_16: dc.b $3
	dc.b $EC, $7, $0, $0, $4
	dc.b $F4, $A, $0, $8, $EC
	dc.b $C, $4, $0, $11, $4
DATAE1VS56T7VD_17: dc.b $3
	dc.b $F5, $E, $0, $0, $ED
	dc.b $D, $0, $0, $C, $F5
	dc.b $F5, $2, $0, $D, $D
DATAE1VS56T7VD_18: dc.b $3
	dc.b $F5, $E, $0, $0, $EC
	dc.b $ED, $0, $0, $C, $F4
	dc.b $F5, $2, $0, $D, $C
DATAE1VS56T7VD_19: dc.b $4
	dc.b $F7, $B, $0, $0, $EE
	dc.b $EF, $4, $0, $C, $F6
	dc.b $FF, $8, $0, $E, $6
	dc.b $7, $0, $0, $11, $6
DATAE1VS56T7VD_1A: dc.b $5
	dc.b $EA, $B, $0, $0, $F8
	dc.b $F2, $1, $0, $C, $10
	dc.b $FA, $3, $0, $E, $F0
	dc.b $A, $4, $0, $12, $F8
	dc.b $12, $0, $0, $14, $F8
DATAE1VS56T7VD_1B: dc.b $5
	dc.b $EB, $3, $0, $0, $7
	dc.b $F3, $3, $0, $4, $FF
	dc.b $F3, $1, $0, $8, $F
	dc.b $FB, $6, $0, $A, $EF
	dc.b $13, $0, $0, $10, $F7
DATAE1VS56T7VD_1C: dc.b $4
	dc.b $F6, $E, $0, $0, $F0
	dc.b $E, $8, $0, $C, $F0
	dc.b $EE, $4, $0, $F, $0
	dc.b $F6, $1, $0, $11, $10
DATAE1VS56T7VD_1D: dc.b $5
	dc.b $4, $C, $0, $0, $E9
	dc.b $EC, $A, $0, $4, $F1
	dc.b $C, $C, $0, $D, $F1
	dc.b $FC, $8, $0, $11, $9
	dc.b $4, $0, $0, $14, $9
DATAE1VS56T7VD_1E: dc.b $5
	dc.b $FF, $A, $0, $0, $EE
	dc.b $EF, $9, $0, $9, $F6
	dc.b $E7, $4, $0, $F, $FE
	dc.b $FF, $8, $0, $11, $6
	dc.b $7, $0, $0, $14, $6
DATAE1VS56T7VD_1F: dc.b $5
	dc.b $EA, $3, $0, $0, $7
	dc.b $F2, $3, $0, $4, $FF
	dc.b $F2, $1, $0, $8, $F
	dc.b $FA, $6, $0, $A, $EF
	dc.b $12, $0, $0, $10, $F7
DATAE1VS56T7VD_20: dc.b $5
	dc.b $E9, $7, $0, $0, $FF
	dc.b $F1, $1, $0, $8, $F
	dc.b $F9, $6, $0, $A, $EF
	dc.b $9, $0, $0, $10, $FF
	dc.b $11, $0, $0, $11, $F7
DATAE1VS56T7VD_21: dc.b $2
	dc.b $F0, $F, $0, $0, $F0
	dc.b $10, $C, $0, $10, $F0
DATAE1VS56T7VD_22: dc.b $3
	dc.b $F0, $B, $0, $0, $F7
	dc.b $10, $8, $0, $C, $F7
	dc.b $0, $1, $0, $F, $EF
DATAE1VS56T7VD_23: dc.b $2
	dc.b $F0, $F, $0, $0, $F1
	dc.b $10, $8, $0, $10, $F1
DATAE1VS56T7VD_24: dc.b $3
	dc.b $F0, $B, $0, $0, $F7
	dc.b $10, $8, $0, $C, $F7
	dc.b $0, $1, $0, $F, $EF
DATAE1VS56T7VD_25: dc.b $4
	dc.b $EF, $A, $0, $0, $EC
	dc.b $7, $D, $0, $9, $F4
	dc.b $F7, $1, $0, $11, $4
	dc.b $FF, $0, $0, $13, $C
DATAE1VS56T7VD_26: dc.b $3
	dc.b $F7, $C, $0, $0, $E9
	dc.b $EF, $8, $0, $4, $F1
	dc.b $FF, $E, $0, $7, $F1
DATAE1VS56T7VD_27: dc.b $4
	dc.b $F0, $B, $0, $0, $F0
	dc.b $F8, $0, $0, $C, $E8
	dc.b $F8, $3, $0, $D, $8
	dc.b $10, $4, $0, $11, $F8
DATAE1VS56T7VD_28: dc.b $3
	dc.b $F7, $C, $0, $0, $E9
	dc.b $EF, $8, $0, $4, $F1
	dc.b $FF, $E, $0, $7, $F1
DATAE1VS56T7VD_29: dc.b $3
	dc.b $F1, $E, $0, $0, $EC
	dc.b $9, $8, $0, $C, $FC
	dc.b $F1, $2, $0, $F, $C
DATAE1VS56T7VD_2A: dc.b $3
	dc.b $F1, $E, $0, $0, $F0
	dc.b $9, $4, $0, $C, $0
	dc.b $F1, $2, $0, $E, $10
DATAE1VS56T7VD_2B: dc.b $3
	dc.b $F0, $E, $0, $0, $F1
	dc.b $8, $C, $0, $C, $F9
	dc.b $F8, $1, $0, $10, $11
DATAE1VS56T7VD_2C: dc.b $3
	dc.b $F1, $E, $0, $0, $F0
	dc.b $9, $4, $0, $C, $0
	dc.b $F1, $2, $0, $E, $10
DATAE1VS56T7VD_2D: dc.b $3
	dc.b $EE, $F, $0, $0, $F7
	dc.b $F6, $2, $0, $10, $EF
	dc.b $E, $0, $0, $13, $F7
DATAE1VS56T7VD_2E: dc.b $3
	dc.b $EE, $B, $0, $0, $FE
	dc.b $F6, $6, $0, $C, $EE
	dc.b $E, $0, $0, $12, $F6
DATAE1VS56T7VD_2F: dc.b $4
	dc.b $F7, $E, $0, $0, $EF
	dc.b $EF, $C, $0, $C, $F7
	dc.b $F, $0, $0, $10, $F7
	dc.b $F7, $1, $0, $11, $F
DATAE1VS56T7VD_30: dc.b $3
	dc.b $EE, $B, $0, $0, $FE
	dc.b $F6, $6, $0, $C, $EE
	dc.b $E, $0, $0, $12, $F6
DATAE1VS56T7VD_31: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATAE1VS56T7VD_32: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATAE1VS56T7VD_33: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATAE1VS56T7VD_34: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATAE1VS56T7VD_35: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATAE1VS56T7VD_36: dc.b $2
	dc.b $F9, $E, $0, $0, $F5
	dc.b $11, $8, $0, $C, $F5
DATAE1VS56T7VD_37: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $8, $C, $0, $C, $F4
	dc.b $F8, $1, $0, $10, $C
DATAE1VS56T7VD_38: dc.b $4
	dc.b $F5, $E, $0, $0, $EC
	dc.b $ED, $0, $0, $C, $FC
	dc.b $D, $0, $0, $D, $FC
	dc.b $F5, $2, $0, $E, $C
DATAE1VS56T7VD_39: dc.b $3
	dc.b $EB, $B, $0, $0, $F1
	dc.b $B, $4, $0, $C, $F9
	dc.b $13, $0, $0, $E, $F9
DATAE1VS56T7VD_3A: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAE1VS56T7VD_3B: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAE1VS56T7VD_3C: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAE1VS56T7VD_3D: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAE1VS56T7VD_3E: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAE1VS56T7VD_3F: dc.b $1
	dc.b $F4, $B, $0, $0, $F6
DATAE1VS56T7VD_40: dc.b $2
	dc.b $FC, $E, $0, $0, $F5
	dc.b $F4, $4, $0, $C, $FD
DATAE1VS56T7VD_41: dc.b $3
	dc.b $EF, $B, $0, $0, $EC
	dc.b $F, $8, $0, $C, $F4
	dc.b $FF, $1, $0, $F, $4
DATAE1VS56T7VD_42: dc.b $4
	dc.b $EB, $7, $0, $0, $F0
	dc.b $F3, $3, $0, $8, $0
	dc.b $3, $0, $0, $C, $E8
	dc.b $3, $5, $0, $D, $8
DATAE1VS56T7VD_43: dc.b $4
	dc.b $F2, $D, $0, $0, $EC
	dc.b $2, $C, $0, $8, $F4
	dc.b $A, $8, $0, $C, $FC
	dc.b $12, $0, $0, $F, $4
DATAE1VS56T7VD_44: dc.b $5
	dc.b $E8, $B, $0, $0, $FC
	dc.b $F0, $4, $0, $C, $EC
	dc.b $F8, $1, $0, $E, $F4
	dc.b $8, $4, $0, $10, $FC
	dc.b $10, $0, $0, $12, $4
DATAE1VS56T7VD_45: dc.b $5
	dc.b $EE, $E, $0, $0, $E8
	dc.b $6, $5, $0, $C, $F0
	dc.b $E6, $0, $0, $10, $F8
	dc.b $E, $0, $0, $11, $0
	dc.b $E6, $1, $0, $12, $8
DATAE1VS56T7VD_46: dc.b $3
	dc.b $ED, $B, $0, $0, $ED
	dc.b $D, $8, $0, $C, $ED
	dc.b $E5, $0, $0, $F, $F5
DATAE1VS56T7VD_47: dc.b $5
	dc.b $EE, $E, $0, $0, $EB
	dc.b $E6, $4, $0, $C, $F3
	dc.b $6, $5, $0, $E, $F3
	dc.b $E, $0, $0, $12, $3
	dc.b $F6, $0, $0, $13, $B
DATAE1VS56T7VD_48: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $F8, $A, $0, $8, $F4
	dc.b $10, $0, $0, $11, $F4
	dc.b $E8, $1, $0, $12, $C
	dc.b $8, $0, $0, $14, $C
DATAE1VS56T7VD_49: dc.b $4
	dc.b $EB, $D, $0, $0, $F0
	dc.b $3, $D, $0, $8, $F0
	dc.b $FB, $4, $0, $10, $F8
	dc.b $EB, $1, $0, $12, $10
DATAE1VS56T7VD_4A: dc.b $4
	dc.b $EB, $D, $0, $0, $F0
	dc.b $3, $D, $0, $8, $F0
	dc.b $FB, $4, $0, $10, $F8
	dc.b $EB, $1, $0, $12, $10
DATAE1VS56T7VD_4B: dc.b $3
	dc.b $F7, $E, $0, $0, $E8
	dc.b $F7, $2, $0, $C, $8
	dc.b $FF, $1, $0, $F, $10
DATAE1VS56T7VD_4C: dc.b $4
	dc.b $F8, $E, $0, $0, $E8
	dc.b $F0, $0, $0, $C, $F8
	dc.b $F8, $2, $0, $D, $8
	dc.b $0, $1, $0, $10, $10
DATAE1VS56T7VD_4D: dc.b $3
	dc.b $EC, $F, $0, $0, $F0
	dc.b $4, $0, $0, $10, $10
	dc.b $C, $C, $0, $11, $EF
DATAE1VS56T7VD_4E: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATAE1VS56T7VD_4F: dc.b $2
	dc.b $D, $8, $0, $0, $F8
	dc.b $ED, $B, $0, $3, $F0
DATAE1VS56T7VD_50: dc.b $3
	dc.b $EE, $B, $0, $0, $F0
	dc.b $F6, $2, $0, $C, $8
	dc.b $E, $8, $0, $F, $F8
DATAE1VS56T7VD_51: dc.b $3
	dc.b $ED, $B, $0, $0, $F3
	dc.b $5, $1, $0, $C, $EB
	dc.b $D, $8, $0, $E, $F3
DATAE1VS56T7VD_52: dc.b $2
	dc.b $EC, $B, $0, $0, $F3
	dc.b $C, $4, $0, $C, $F3
DATAE1VS56T7VD_53: dc.b $4
	dc.b $ED, $B, $0, $0, $F3
	dc.b $5, $1, $0, $C, $EB
	dc.b $D, $4, $0, $E, $F3
	dc.b $D, $0, $0, $10, $3
DATAE1VS56T7VD_54: dc.b $2
	dc.b $EC, $B, $0, $0, $F3
	dc.b $C, $4, $0, $C, $F3
DATAE1VS56T7VD_55: dc.b $5
	dc.b $ED, $A, $0, $0, $F0
	dc.b $5, $5, $0, $9, $F8
	dc.b $F5, $0, $0, $D, $8
	dc.b $D, $0, $0, $E, $8
	dc.b $5, $0, $0, $F, $F0
DATAE1VS56T7VD_56: dc.b $4
	dc.b $ED, $B, $0, $0, $F1
	dc.b $D, $0, $0, $C, $8
	dc.b $D, $0, $0, $D, $0
	dc.b $D, $0, $0, $E, $F8
DATAE1VS56T7VD_57: dc.b $3
	dc.b $ED, $7, $0, $0, $F2
	dc.b $D, $8, $0, $8, $F8
	dc.b $ED, $3, $0, $B, $2
DATAE1VS56T7VD_58: dc.b $2
	dc.b $ED, $B, $0, $0, $F0
	dc.b $D, $8, $0, $C, $F8
DATAE1VS56T7VD_59: dc.b $6
	dc.b $5, $0, $0, $0, $0
	dc.b $D, $0, $0, $1, $8
	dc.b $D, $0, $0, $2, $F8
	dc.b $D, $0, $0, $3, $0
	dc.b $ED, $7, $0, $4, $F0
	dc.b $ED, $2, $0, $C, $0
DATAE1VS56T7VD_5A: dc.b $4
	dc.b $5, $9, $0, $0, $F7
	dc.b $FD, $8, $0, $6, $EF
	dc.b $ED, $D, $0, $9, $EF
	dc.b $E5, $0, $0, $11, $FF
DATAE1VS56T7VD_5B: dc.b $4
	dc.b $E4, $0, $0, $0, $F9
	dc.b $EC, $D, $0, $1, $F1
	dc.b $FC, $9, $0, $9, $F1
	dc.b $C, $8, $0, $F, $F9
DATAE1VS56T7VD_5C: dc.b $3
	dc.b $F4, $A, $0, $0, $F9
	dc.b $F4, $1, $0, $9, $11
	dc.b $FC, $5, $0, $B, $E9
DATAE1VS56T7VD_5D: dc.b $3
	dc.b $FB, $D, $0, $0, $F1
	dc.b $F3, $C, $0, $8, $F9
	dc.b $FB, $4, $0, $C, $11
DATAE1VS56T7VD_5E: dc.b $2
	dc.b $F3, $A, $0, $0, $0
	dc.b $F3, $A, $8, $0, $E8
DATAE1VS56T7VD_5F: dc.b $3
	dc.b $FB, $D, $8, $0, $EF
	dc.b $F3, $C, $8, $8, $E7
	dc.b $FB, $4, $8, $C, $DF
DATAE1VS56T7VD_60: dc.b $3
	dc.b $F4, $A, $8, $0, $EF
	dc.b $F4, $1, $8, $9, $E7
	dc.b $FC, $5, $8, $B, $7
DATAE1VS56T7VD_61: dc.b $3
	dc.b $F4, $D, $0, $0, $EA
	dc.b $4, $C, $0, $8, $F2
	dc.b $FC, $0, $0, $C, $A
DATAE1VS56T7VD_62: dc.b $3
	dc.b $F4, $D, $0, $0, $EC
	dc.b $4, $8, $0, $8, $F4
	dc.b $F4, $1, $0, $B, $C
DATAE1VS56T7VD_63: dc.b $3
	dc.b $F4, $D, $8, $0, $F6
	dc.b $4, $C, $8, $8, $EE
	dc.b $FC, $0, $8, $C, $EE
DATAE1VS56T7VD_64: dc.b $5
	dc.b $EF, $8, $0, $0, $F2
	dc.b $FF, $C, $0, $3, $ED
	dc.b $F, $8, $0, $7, $F6
	dc.b $F7, $8, $0, $A, $F1
	dc.b $7, $4, $0, $D, $F5
DATAE1VS56T7VD_65: dc.b $5
	dc.b $F4, $C, $0, $0, $F3
	dc.b $EC, $8, $0, $4, $F7
	dc.b $FC, $C, $0, $7, $F5
	dc.b $4, $C, $0, $B, $F3
	dc.b $C, $8, $0, $F, $F6
DATAE1VS56T7VD_66: dc.b $5
	dc.b $EE, $A, $0, $0, $EE
	dc.b $FE, $4, $0, $9, $6
	dc.b $6, $8, $0, $B, $F5
	dc.b $E, $8, $0, $E, $F8
	dc.b $F6, $0, $10, $11, $6
DATAE1VS56T7VD_67: dc.b $4
	dc.b $E8, $E, $0, $0, $EF
	dc.b $0, $5, $0, $C, $F7
	dc.b $0, $0, $0, $10, $7
	dc.b $10, $4, $0, $11, $FF
DATAE1VS56T7VD_68: dc.b $6
	dc.b $E9, $E, $0, $0, $EE
	dc.b $1, $C, $0, $C, $F6
	dc.b $E1, $0, $0, $10, $FE
	dc.b $9, $8, $0, $11, $FE
	dc.b $E9, $0, $0, $14, $E
	dc.b $F9, $0, $0, $15, $E
DATAE1VS56T7VD_69: dc.b $3
	dc.b $E9, $F, $0, $0, $F2
	dc.b $9, $C, $0, $10, $F2
	dc.b $E1, $0, $0, $14, $2
DATAE1VS56T7VD_6A: dc.b $6
	dc.b $EC, $4, $0, $0, $F8
	dc.b $EC, $0, $0, $2, $8
	dc.b $F4, $C, $0, $3, $F2
	dc.b $FC, $8, $0, $7, $F5
	dc.b $4, $C, $0, $A, $F2
	dc.b $C, $8, $0, $E, $F5
DATAE1VS56T7VD_6B: dc.b $7
	dc.b $EC, $4, $0, $0, $F9
	dc.b $E4, $0, $0, $2, $FE
	dc.b $EC, $0, $0, $3, $9
	dc.b $F4, $C, $0, $4, $F3
	dc.b $FC, $8, $0, $8, $F6
	dc.b $4, $C, $0, $B, $F3
	dc.b $C, $8, $0, $F, $F6
DATAE1VS56T7VD_6C: dc.b $7
	dc.b $EC, $4, $0, $0, $F9
	dc.b $E4, $0, $0, $2, $FE
	dc.b $EC, $0, $0, $3, $9
	dc.b $F4, $C, $0, $4, $F3
	dc.b $FC, $8, $0, $8, $F6
	dc.b $4, $C, $0, $B, $F3
	dc.b $C, $8, $0, $F, $F6
DATAE1VS56T7VD_6D: dc.b $4
	dc.b $E8, $A, $0, $0, $F4
	dc.b $F3, $0, $0, $9, $EC
	dc.b $0, $6, $0, $A, $F4
	dc.b $F0, $0, $0, $10, $C
DATAE1VS56T7VD_6E: dc.b $4
	dc.b $F0, $D, $0, $0, $EC
	dc.b $E8, $8, $0, $8, $F4
	dc.b $0, $6, $0, $B, $F4
	dc.b $F0, $0, $0, $11, $C
DATAE1VS56T7VD_6F: dc.b $4
	dc.b $E8, $A, $0, $0, $F4
	dc.b $E8, $1, $0, $9, $C
	dc.b $F0, $0, $0, $B, $EC
	dc.b $0, $6, $0, $C, $F4
DATAE1VS56T7VD_70: dc.b $5
	dc.b $EC, $F, $0, $0, $EE
	dc.b $F4, $0, $0, $10, $E6
	dc.b $4, $0, $0, $11, $E
	dc.b $A, $8, $0, $12, $FC
	dc.b $12, $0, $0, $15, $4
DATAE1VS56T7VD_71: dc.b $2
	dc.b $ED, $F, $0, $0, $EE
	dc.b $D, $8, $0, $10, $F6
DATAE1VS56T7VD_72: dc.b $3
	dc.b $EF, $B, $0, $0, $FB
	dc.b $FF, $5, $0, $C, $EB
	dc.b $F, $8, $0, $10, $FB
DATAE1VS56T7VD_73: dc.b $2
	dc.b $F4, $B, $0, $0, $FB
	dc.b $FC, $6, $0, $C, $EB
DATAE1VS56T7VD_74: dc.b $3
	dc.b $F3, $B, $0, $0, $FD
	dc.b $FB, $6, $0, $C, $ED
	dc.b $13, $0, $0, $12, $FD
DATAE1VS56T7VD_75: dc.b $3
	dc.b $4, $D, $0, $0, $EE
	dc.b $F4, $D, $0, $8, $F6
	dc.b $4, $0, $0, $10, $E
DATAE1VS56T7VD_76: dc.b $3
	dc.b $F2, $F, $0, $0, $F2
	dc.b $12, $0, $0, $10, $F2
	dc.b $EA, $4, $0, $11, $FA
DATAE1VS56T7VD_77: dc.b $6
	dc.b $F7, $C, $0, $0, $EB
	dc.b $EF, $8, $0, $4, $F3
	dc.b $FF, $D, $0, $7, $F3
	dc.b $E7, $0, $0, $F, $FB
	dc.b $F, $4, $0, $10, $FB
	dc.b $F7, $0, $0, $12, $B
DATAE1VS56T7VD_78: dc.b $3
	dc.b $EF, $F, $0, $0, $F2
	dc.b $F, $4, $0, $10, $F2
	dc.b $E7, $4, $0, $12, $FA
DATAE1VS56T7VD_79: dc.b $4
	dc.b $EA, $7, $0, $0, $F9
	dc.b $F2, $1, $0, $8, $F1
	dc.b $F2, $3, $0, $A, $9
	dc.b $A, $9, $0, $E, $F1
DATAE1VS56T7VD_7A: dc.b $3
	dc.b $EC, $E, $0, $0, $F3
	dc.b $4, $9, $0, $C, $FB
	dc.b $FC, $0, $0, $12, $13
DATAE1VS56T7VD_7B: dc.b $2
	dc.b $EE, $E, $0, $0, $F4
	dc.b $6, $9, $0, $C, $FC
DATAE1VS56T7VD_7C: dc.b $3
	dc.b $EE, $E, $0, $0, $F4
	dc.b $6, $8, $0, $C, $FC
	dc.b $E, $4, $0, $F, $4
DATAE1VS56T7VD_7D: dc.b $3
	dc.b $EC, $E, $0, $0, $F3
	dc.b $4, $9, $0, $C, $FB
	dc.b $FC, $0, $0, $12, $13
DATAE1VS56T7VD_7E: dc.b $3
	dc.b $EC, $F, $0, $0, $F2
	dc.b $F4, $1, $0, $10, $EA
	dc.b $4, $0, $0, $12, $12
DATAE1VS56T7VD_7F: dc.b $5
	dc.b $EA, $B, $0, $0, $F7
	dc.b $F2, $2, $0, $C, $EF
	dc.b $F2, $1, $0, $F, $F
	dc.b $FA, $0, $0, $11, $E7
	dc.b $A, $0, $0, $12, $F7
DATAE1VS56T7VD_80: dc.b $4
	dc.b $F5, $D, $0, $0, $EA
	dc.b $ED, $C, $0, $8, $F2
	dc.b $5, $4, $0, $C, $F2
	dc.b $F5, $6, $0, $E, $A
DATAE1VS56T7VD_81: dc.b $3
	dc.b $EE, $F, $0, $0, $EF
	dc.b $F6, $0, $0, $10, $E7
	dc.b $F6, $2, $0, $11, $F
DATAE1VS56T7VD_82: dc.b $5
	dc.b $E8, $D, $0, $0, $EC
	dc.b $F8, $A, $0, $8, $F4
	dc.b $10, $0, $0, $11, $F4
	dc.b $E8, $1, $0, $12, $C
	dc.b $8, $0, $0, $14, $C
DATAE1VS56T7VD_83: dc.b $1
	dc.b $F1, $F, $0, $0, $F2
DATAE1VS56T7VD_84: dc.b $1
	dc.b $F2, $F, $0, $0, $F2
DATAE1VS56T7VD_85: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAE1VS56T7VD_86: dc.b $2
	dc.b $F1, $E, $0, $0, $F1
	dc.b $9, $8, $0, $C, $F1
DATAE1VS56T7VD_87: dc.b $1
	dc.b $F1, $F, $0, $0, $F1
DATAE1VS56T7VD_88: dc.b $2
	dc.b $F1, $B, $0, $0, $F4
	dc.b $F9, $0, $0, $C, $EC
DATAE1VS56T7VD_89: dc.b $3
	dc.b $F0, $E, $0, $0, $EC
	dc.b $E8, $0, $0, $C, $F4
	dc.b $8, $9, $0, $D, $F4
DATAE1VS56T7VD_8A: dc.b $3
	dc.b $F0, $E, $0, $0, $ED
	dc.b $8, $6, $0, $C, $F5
	dc.b $8, $0, $0, $12, $5
DATAE1VS56T7VD_8B: dc.b $3
	dc.b $F0, $E, $0, $0, $ED
	dc.b $8, $6, $0, $C, $F5
	dc.b $8, $0, $0, $12, $5
DATAE1VS56T7VD_8C: dc.b $3
	dc.b $EE, $B, $0, $0, $F0
	dc.b $E, $9, $0, $C, $F0
	dc.b $F6, $2, $0, $12, $8
DATAE1VS56T7VD_8D: dc.b $3
	dc.b $F2, $E, $0, $0, $EC
	dc.b $A, $9, $0, $C, $F4
	dc.b $1A, $4, $0, $12, $F4
DATAE1VS56T7VD_8E: dc.b $3
	dc.b $F2, $E, $0, $0, $EC
	dc.b $A, $A, $0, $C, $F4
	dc.b $22, $0, $0, $15, $FC
DATAE1VS56T7VD_8F: dc.b $4
	dc.b $EE, $7, $0, $0, $F2
	dc.b $E, $A, $0, $8, $F2
	dc.b $F6, $2, $0, $11, $2
	dc.b $E, $0, $0, $14, $A
DATAE1VS56T7VD_90: dc.b $4
	dc.b $EE, $7, $0, $0, $F2
	dc.b $E, $A, $0, $8, $F2
	dc.b $F6, $2, $0, $11, $2
	dc.b $E, $0, $0, $14, $A
DATAE1VS56T7VD_91: dc.b $4
	dc.b $EE, $7, $0, $0, $F2
	dc.b $E, $A, $0, $8, $F2
	dc.b $F6, $2, $0, $11, $2
	dc.b $E, $0, $0, $14, $A
DATAE1VS56T7VD_92: dc.b $3
	dc.b $F4, $B, $0, $0, $F4
	dc.b $14, $9, $0, $C, $F4
	dc.b $C, $1, $0, $12, $C
DATAE1VS56T7VD_93: dc.b $4
	dc.b $F4, $B, $0, $0, $F3
	dc.b $14, $9, $0, $C, $F3
	dc.b $FC, $0, $0, $12, $B
	dc.b $D, $0, $0, $13, $B
DATAE1VS56T7VD_94: dc.b $3
	dc.b $F4, $B, $0, $0, $F4
	dc.b $14, $9, $0, $C, $F4
	dc.b $D, $0, $0, $12, $C
DATAE1VS56T7VD_95: dc.b $3
	dc.b $F4, $B, $0, $0, $F4
	dc.b $14, $9, $0, $C, $F4
	dc.b $D, $0, $0, $12, $C
DATAE1VS56T7VD_96: dc.b $3
	dc.b $F5, $B, $0, $0, $F4
	dc.b $15, $9, $0, $C, $F4
	dc.b $D, $0, $0, $12, $C
DATAE1VS56T7VD_97: dc.b $4
	dc.b $E7, $B, $0, $0, $F0
	dc.b $7, $5, $0, $C, $F8
	dc.b $EF, $1, $0, $10, $8
	dc.b $F, $0, $0, $12, $8
DATAE1VS56T7VD_98: dc.b $4
	dc.b $E8, $B, $0, $0, $EF
	dc.b $8, $5, $0, $C, $F7
	dc.b $F0, $1, $0, $10, $7
	dc.b $10, $0, $0, $12, $7
DATAE1VS56T7VD_99: dc.b $4
	dc.b $E7, $B, $0, $0, $EF
	dc.b $7, $5, $0, $C, $F7
	dc.b $EF, $1, $0, $10, $7
	dc.b $F, $0, $0, $12, $7
DATAE1VS56T7VD_9A: dc.b $4
	dc.b $4, $C, $0, $0, $EF
	dc.b $E4, $3, $0, $4, $F7
	dc.b $C, $8, $0, $8, $F7
	dc.b $EC, $6, $0, $B, $FF
DATAE1VS56T7VD_9B: dc.b $3
	dc.b $FC, $E, $0, $0, $F0
	dc.b $EC, $5, $0, $C, $F8
	dc.b $F4, $0, $0, $10, $8
DATAE1VS56T7VD_9C: dc.b $4
	dc.b $EC, $D, $0, $0, $E8
	dc.b $FC, $9, $0, $8, $F0
	dc.b $E4, $0, $0, $E, $F8
	dc.b $C, $8, $0, $F, $F8
DATAE1VS56T7VD_9D: dc.b $3
	dc.b $EC, $E, $0, $0, $E8
	dc.b $4, $8, $0, $C, $F0
	dc.b $C, $8, $0, $F, $F8
DATAE1VS56T7VD_9E: dc.b $5
	dc.b $E7, $F, $0, $0, $ED
	dc.b $F7, $2, $0, $10, $D
	dc.b $7, $4, $0, $13, $ED
	dc.b $7, $1, $0, $15, $5
	dc.b $F, $4, $0, $17, $E5
DATAE1VS56T7VD_9F: dc.b $4
	dc.b $E8, $B, $0, $0, $F1
	dc.b $8, $D, $0, $C, $F1
	dc.b $F0, $1, $0, $14, $9
	dc.b $8, $0, $0, $16, $11
DATAE1VS56T7VD_A0: dc.b $2
	dc.b $E8, $E, $0, $0, $F0
	dc.b $0, $6, $0, $C, $F8
DATAE1VS56T7VD_A1: dc.b $3
	dc.b $FC, $E, $0, $0, $EC
	dc.b $E4, $A, $0, $C, $F4
	dc.b $FC, $0, $0, $15, $C
DATAE1VS56T7VD_A2: dc.b $5
	dc.b $FB, $D, $0, $0, $EC
	dc.b $B, $4, $0, $8, $EC
	dc.b $E3, $A, $0, $A, $F4
	dc.b $B, $4, $0, $13, $4
	dc.b $FB, $1, $0, $15, $C
DATAE1VS56T7VD_A3: dc.b $5
	dc.b $6, $C, $0, $0, $ED
	dc.b $E, $0, $0, $4, $ED
	dc.b $E6, $B, $0, $5, $F5
	dc.b $E, $8, $0, $11, $FD
	dc.b $6, $0, $0, $14, $D
DATAE1VS56T7VD_A4: dc.b $4
	dc.b $E8, $B, $0, $0, $F3
	dc.b $8, $5, $0, $C, $F3
	dc.b $10, $0, $0, $10, $3
	dc.b $F5, $0, $8, $11, $B
DATAE1VS56T7VD_A5: dc.b $3
	dc.b $E7, $B, $0, $0, $F2
	dc.b $7, $9, $0, $C, $F2
	dc.b $EF, $1, $0, $12, $A
DATAE1VS56T7VD_A6: dc.b $5
	dc.b $ED, $E, $0, $0, $E3
	dc.b $5, $8, $0, $C, $EB
	dc.b $D, $1, $0, $F, $FB
	dc.b $ED, $2, $0, $11, $3
	dc.b $F5, $2, $0, $14, $B
DATAE1VS56T7VD_A7: dc.b $6
	dc.b $EE, $E, $0, $0, $EA
	dc.b $F6, $0, $0, $C, $E2
	dc.b $FE, $5, $0, $D, $A
	dc.b $6, $8, $0, $11, $F2
	dc.b $E, $4, $0, $14, $2
	dc.b $16, $0, $0, $16, $2
DATAE1VS56T7VD_A8: dc.b $4
	dc.b $EB, $E, $0, $0, $ED
	dc.b $F3, $0, $0, $C, $E5
	dc.b $3, $C, $0, $D, $F5
	dc.b $B, $4, $0, $11, $5
DATAE1VS56T7VD_A9: dc.b $6
	dc.b $E7, $B, $0, $0, $ED
	dc.b $EF, $1, $0, $C, $E5
	dc.b $EF, $3, $0, $E, $5
	dc.b $FF, $0, $0, $12, $D
	dc.b $7, $4, $0, $13, $F5
	dc.b $F, $4, $0, $15, $FD
DATAE1VS56T7VD_AA: dc.b $4
	dc.b $EC, $D, $0, $0, $E4
	dc.b $FC, $A, $0, $8, $EC
	dc.b $14, $0, $0, $11, $FC
	dc.b $F4, $6, $0, $12, $4
DATAE1VS56T7VD_AB: dc.b $7
	dc.b $EB, $D, $0, $0, $E3
	dc.b $F3, $2, $0, $8, $3
	dc.b $FB, $8, $0, $B, $EB
	dc.b $FB, $5, $0, $E, $B
	dc.b $3, $4, $0, $12, $F3
	dc.b $B, $1, $0, $14, $FB
	dc.b $B, $0, $0, $16, $B
DATAE1VS56T7VD_AC: dc.b $4
	dc.b $F0, $E, $0, $0, $E6
	dc.b $8, $C, $0, $C, $EE
	dc.b $10, $4, $0, $10, $FE
	dc.b $8, $0, $0, $12, $E
DATAE1VS56T7VD_AD: dc.b $7
	dc.b $E7, $3, $0, $0, $F2
	dc.b $EF, $2, $0, $4, $EA
	dc.b $EF, $7, $0, $7, $FA
	dc.b $F7, $0, $0, $F, $E2
	dc.b $FF, $2, $0, $10, $A
	dc.b $7, $0, $0, $13, $12
	dc.b $F, $4, $0, $14, $FA
DATAE1VS56T7VD_AE: dc.b $5
	dc.b $F4, $F, $0, $0, $E7
	dc.b $EC, $8, $0, $10, $F7
	dc.b $F4, $4, $0, $13, $7
	dc.b $4, $1, $0, $15, $7
	dc.b $C, $1, $0, $17, $F
DATAE1VS56T7VD_AF: dc.b $4
	dc.b $F8, $E, $0, $0, $E4
	dc.b $F0, $8, $0, $C, $EC
	dc.b $F8, $6, $0, $F, $4
	dc.b $E8, $1, $0, $15, $C
DATAE1VS56T7VD_B0: dc.b $2
	dc.b $F2, $B, $0, $0, $E8
	dc.b $FA, $9, $0, $C, $0
DATAE1VS56T7VD_B1: dc.b $4
	dc.b $F4, $E, $0, $0, $E4
	dc.b $EC, $0, $0, $C, $FC
	dc.b $C, $8, $0, $D, $FC
	dc.b $F4, $6, $0, $10, $4
DATAE1VS56T7VD_B2: dc.b $4
	dc.b $ED, $9, $0, $0, $FB
	dc.b $F5, $A, $0, $6, $E3
	dc.b $FD, $6, $0, $F, $FB
	dc.b $5, $1, $0, $15, $B
DATAE1VS56T7VD_B3: dc.b $4
	dc.b $F3, $E, $0, $0, $E6
	dc.b $EB, $6, $0, $C, $6
	dc.b $3, $1, $0, $12, $6
	dc.b $B, $0, $0, $14, $E
DATAE1VS56T7VD_B4: dc.b $4
	dc.b $F5, $E, $0, $0, $E8
	dc.b $ED, $0, $0, $C, $F8
	dc.b $FD, $5, $0, $D, $8
	dc.b $F5, $0, $0, $11, $10
DATAE1VS56T7VD_B5: dc.b $3
	dc.b $F6, $E, $0, $0, $E7
	dc.b $EE, $4, $0, $C, $EF
	dc.b $F6, $6, $0, $E, $7
DATAE1VS56T7VD_B6: dc.b $5
	dc.b $F7, $B, $0, $0, $ED
	dc.b $17, $8, $0, $C, $ED
	dc.b $EF, $8, $0, $F, $F5
	dc.b $FF, $8, $0, $12, $5
	dc.b $7, $1, $0, $15, $5
DATAE1VS56T7VD_B7: dc.b $6
	dc.b $F9, $E, $0, $0, $EC
	dc.b $11, $8, $0, $C, $EC
	dc.b $19, $0, $0, $F, $F4
	dc.b $E9, $5, $0, $10, $FC
	dc.b $F1, $1, $0, $14, $C
	dc.b $F9, $0, $0, $16, $14
DATAE1VS56T7VD_B8: dc.b $4
	dc.b $EF, $5, $0, $0, $5
	dc.b $F7, $B, $0, $4, $ED
	dc.b $FF, $1, $0, $10, $5
	dc.b $17, $0, $0, $12, $F5
DATAE1VS56T7VD_B9: dc.b $7
	dc.b $FE, $E, $0, $0, $EA
	dc.b $F6, $C, $0, $C, $F2
	dc.b $16, $4, $0, $10, $F2
	dc.b $EE, $0, $0, $12, $2
	dc.b $FE, $4, $0, $13, $A
	dc.b $6, $0, $0, $15, $A
	dc.b $F6, $0, $0, $16, $12
DATAE1VS56T7VD_BA: dc.b $5
	dc.b $FD, $E, $0, $0, $ED
	dc.b $15, $4, $0, $C, $ED
	dc.b $ED, $9, $0, $E, $F5
	dc.b $FD, $2, $0, $14, $D
	dc.b $FD, $0, $0, $17, $15
DATAE1VS56T7VD_BB: dc.b $7
	dc.b $0, $A, $0, $0, $ED
	dc.b $18, $4, $0, $9, $ED
	dc.b $F8, $8, $0, $B, $F5
	dc.b $E8, $5, $0, $E, $FD
	dc.b $0, $8, $0, $12, $5
	dc.b $8, $0, $0, $15, $5
	dc.b $F0, $0, $0, $16, $D
DATAE1VS56T7VD_BC: dc.b $4
	dc.b $F8, $E, $0, $0, $ED
	dc.b $10, $8, $0, $C, $ED
	dc.b $E8, $1, $0, $F, $5
	dc.b $F0, $1, $0, $11, $D
DATAE1VS56T7VD_BD: dc.b $7
	dc.b $8, $C, $0, $0, $E6
	dc.b $F8, $D, $0, $4, $EE
	dc.b $10, $8, $0, $C, $EE
	dc.b $18, $0, $0, $F, $F6
	dc.b $F0, $8, $0, $10, $FE
	dc.b $E8, $0, $0, $13, $6
	dc.b $F8, $1, $0, $14, $E
DATAE1VS56T7VD_BE: dc.b $5
	dc.b $0, $9, $0, $0, $EC
	dc.b $F8, $C, $0, $6, $F4
	dc.b $E8, $5, $0, $A, $FC
	dc.b $0, $4, $0, $E, $4
	dc.b $F0, $0, $0, $10, $C
DATAE1VS56T7VD_BF: dc.b $3
	dc.b $F8, $A, $0, $0, $EF
	dc.b $E8, $5, $0, $9, $F7
	dc.b $F0, $6, $0, $D, $7
DATAE1VS56T7VD_C0: dc.b $3
	dc.b $F8, $A, $0, $0, $EE
	dc.b $E8, $5, $0, $9, $F6
	dc.b $F0, $6, $0, $D, $6
DATAE1VS56T7VD_C1: dc.b $3
	dc.b $0, $9, $0, $0, $EC
	dc.b $F0, $D, $0, $6, $F4
	dc.b $0, $4, $0, $E, $4
DATAE1VS56T7VD_C2: dc.b $4
	dc.b $E7, $B, $0, $0, $F9
	dc.b $EF, $1, $0, $C, $F1
	dc.b $7, $C, $0, $E, $F1
	dc.b $F, $4, $0, $12, $F9
DATAE1VS56T7VD_C3: dc.b $4
	dc.b $E7, $B, $0, $0, $F9
	dc.b $EF, $1, $0, $C, $F1
	dc.b $7, $C, $0, $E, $F1
	dc.b $F, $4, $0, $12, $F9
DATAE1VS56T7VD_C4: dc.b $3
	dc.b $EB, $E, $0, $0, $F3
	dc.b $3, $9, $0, $C, $F3
	dc.b $13, $0, $0, $12, $FB
DATAE1VS56T7VD_C5: dc.b $3
	dc.b $EA, $E, $0, $0, $F3
	dc.b $2, $9, $0, $C, $F3
	dc.b $12, $0, $0, $12, $FB
DATAE1VS56T7VD_C6: dc.b $5
	dc.b $F3, $D, $0, $0, $E8
	dc.b $EB, $8, $0, $8, $F0
	dc.b $3, $8, $0, $B, $F8
	dc.b $B, $4, $0, $E, $0
	dc.b $FB, $0, $0, $10, $8
DATAE1VS56T7VD_C7: dc.b $4
	dc.b $E8, $B, $0, $0, $ED
	dc.b $8, $8, $0, $C, $FD
	dc.b $F0, $2, $0, $F, $5
	dc.b $0, $0, $0, $12, $D
DATAE1VS56T7VD_C8: dc.b $4
	dc.b $EB, $B, $0, $0, $EF
	dc.b $B, $8, $0, $C, $FF
	dc.b $F3, $2, $0, $F, $7
	dc.b $3, $0, $0, $12, $F
DATAE1VS56T7VD_C9: dc.b $3
	dc.b $EB, $B, $0, $0, $F0
	dc.b $B, $4, $0, $C, $0
	dc.b $FB, $1, $0, $E, $8
DATAE1VS56T7VD_CA: dc.b $3
	dc.b $EF, $B, $0, $0, $E9
	dc.b $F7, $6, $0, $C, $1
	dc.b $FF, $0, $0, $12, $11
DATAE1VS56T7VD_CB: dc.b $3
	dc.b $EE, $B, $0, $0, $E9
	dc.b $F6, $6, $0, $C, $1
	dc.b $FE, $0, $0, $12, $11
DATAE1VS56T7VD_CC: dc.b $4
	dc.b $ED, $B, $0, $0, $E9
	dc.b $D, $0, $0, $C, $F1
	dc.b $F5, $6, $0, $D, $1
	dc.b $FD, $0, $0, $13, $11
DATAE1VS56T7VD_CD: dc.b $4
	dc.b $EE, $B, $0, $0, $E9
	dc.b $E, $0, $0, $C, $F1
	dc.b $F6, $6, $0, $D, $1
	dc.b $FE, $0, $0, $13, $11
DATAE1VS56T7VD_CE: dc.b $4
	dc.b $EE, $B, $0, $0, $E9
	dc.b $E, $0, $0, $C, $F1
	dc.b $F6, $6, $0, $D, $1
	dc.b $FE, $0, $0, $13, $11
DATAE1VS56T7VD_CF: dc.b $4
	dc.b $F8, $A, $0, $0, $EE
	dc.b $E8, $5, $0, $9, $FE
	dc.b $F8, $5, $0, $D, $6
	dc.b $F0, $0, $0, $11, $E
DATAE1VS56T7VD_D0: dc.b $3
	dc.b $F8, $A, $0, $0, $EE
	dc.b $F0, $C, $0, $9, $F6
	dc.b $F8, $5, $0, $D, $6
DATAE1VS56T7VD_D1: dc.b $5
	dc.b $EB, $D, $0, $0, $F2
	dc.b $3, $9, $0, $8, $F2
	dc.b $FB, $8, $0, $E, $FA
	dc.b $13, $0, $0, $11, $FA
	dc.b $E3, $0, $0, $12, $2
DATAE1VS56T7VD_D2: dc.b $3
	dc.b $EB, $E, $0, $0, $F2
	dc.b $3, $9, $0, $C, $F2
	dc.b $13, $0, $0, $12, $FA
DATAE1VS56T7VD_D3: dc.b $4
	dc.b $F1, $D, $0, $0, $E9
	dc.b $E9, $8, $0, $8, $F1
	dc.b $1, $9, $0, $B, $F9
	dc.b $F9, $0, $0, $11, $9
DATAE1VS56T7VD_D4: dc.b $3
	dc.b $E9, $B, $0, $0, $F1
	dc.b $9, $8, $0, $C, $F9
	dc.b $F9, $1, $0, $F, $9
DATAE1VS56T7VD_D5: dc.b $5
	dc.b $EF, $A, $0, $0, $E9
	dc.b $F7, $0, $0, $9, $E1
	dc.b $F7, $6, $0, $A, $1
	dc.b $FF, $0, $0, $10, $11
	dc.b $7, $4, $0, $11, $E9
DATAE1VS56T7VD_D6: dc.b $3
	dc.b $EF, $B, $0, $0, $E9
	dc.b $F7, $6, $0, $C, $1
	dc.b $FF, $0, $0, $12, $11
DATAE1VS56T7VD_D7: dc.b $3
	dc.b $FC, $E, $0, $0, $EA
	dc.b $EC, $9, $0, $C, $FA
	dc.b $FC, $2, $0, $12, $A
DATAE1VS56T7VD_D8: dc.b $3
	dc.b $FC, $E, $0, $0, $EF
	dc.b $EC, $9, $0, $C, $F7
	dc.b $F4, $3, $0, $12, $F
DATAE1VS56T7VD_D9: dc.b $3
	dc.b $FF, $D, $0, $0, $EE
	dc.b $EF, $D, $0, $8, $F6
	dc.b $FF, $4, $0, $10, $E
DATAE1VS56T7VD_DA: dc.b $4
	dc.b $7, $C, $0, $0, $EA
	dc.b $F7, $D, $0, $4, $F2
	dc.b $EF, $8, $0, $C, $FA
	dc.b $F7, $1, $0, $F, $12
DATAE1VS56T7VD_DB: dc.b $4
	dc.b $ED, $E, $0, $0, $F4
	dc.b $5, $5, $0, $C, $FC
	dc.b $15, $0, $0, $10, $FC
	dc.b $ED, $0, $0, $11, $14
DATAE1VS56T7VD_DC: dc.b $5
	dc.b $F3, $D, $0, $0, $F4
	dc.b $EB, $C, $0, $8, $FC
	dc.b $3, $5, $0, $C, $FC
	dc.b $13, $0, $0, $10, $FC
	dc.b $F3, $0, $0, $11, $14
DATAE1VS56T7VD_DD: dc.b $4
	dc.b $EC, $B, $0, $0, $F2
	dc.b $E4, $4, $0, $C, $FA
	dc.b $C, $4, $0, $E, $2
	dc.b $FC, $1, $0, $10, $A
DATAE1VS56T7VD_DE: dc.b $4
	dc.b $E5, $7, $0, $0, $F8
	dc.b $ED, $2, $0, $8, $F0
	dc.b $F5, $3, $0, $B, $8
	dc.b $5, $4, $0, $F, $F8
DATAE1VS56T7VD_DF: dc.b $5
	dc.b $E6, $3, $0, $0, $EB
	dc.b $6, $8, $0, $4, $EB
	dc.b $EE, $6, $0, $7, $F3
	dc.b $F6, $5, $0, $D, $3
	dc.b $FE, $0, $0, $11, $13
DATAE1VS56T7VD_E0: dc.b $5
	dc.b $E7, $7, $0, $0, $EB
	dc.b $7, $4, $0, $8, $F3
	dc.b $EF, $2, $0, $A, $FB
	dc.b $F7, $5, $0, $D, $3
	dc.b $FF, $0, $0, $11, $13
DATAE1VS56T7VD_E1: dc.b $5
	dc.b $EA, $E, $0, $0, $EC
	dc.b $2, $C, $0, $C, $F4
	dc.b $A, $8, $0, $10, $FC
	dc.b $12, $0, $0, $13, $4
	dc.b $FA, $0, $0, $14, $C
DATAE1VS56T7VD_E2: dc.b $3
	dc.b $FF, $D, $8, $0, $F6
	dc.b $EF, $D, $8, $8, $EE
	dc.b $FF, $4, $8, $10, $E6
DATAE1VS56T7VD_E3: dc.b $4
	dc.b $7, $C, $8, $0, $F9
	dc.b $F7, $D, $8, $4, $F1
	dc.b $EF, $8, $8, $C, $F1
	dc.b $F7, $1, $8, $F, $E9
	even