; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Nov 23 2019 22:25:31 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATAQ72E9ONBW4:
		dc.w DATAQ72E9ONBW4_0-DATAQ72E9ONBW4
		dc.w	DATAQ72E9ONBW4_1-DATAQ72E9ONBW4
		dc.w DATAQ72E9ONBW4_2-DATAQ72E9ONBW4
		dc.w	DATAQ72E9ONBW4_3-DATAQ72E9ONBW4
		dc.w DATAQ72E9ONBW4_4-DATAQ72E9ONBW4
		dc.w byte_CB47-DATAQ72E9ONBW4
		dc.w byte_CB26-DATAQ72E9ONBW4
		dc.w byte_CB31-DATAQ72E9ONBW4
		dc.w byte_CB3C-DATAQ72E9ONBW4
DATAQ72E9ONBW4_0: dc.b $8
	dc.b $F8, $5, $0, $3E, $B8
	dc.b $F8, $5, $0, $32, $C8
	dc.b $F8, $5, $0, $2E, $D8
	dc.b $F8, $1, $0, $20, $E8
	dc.b $F8, $5, $0, $8, $F0
	dc.b $F8, $5, $0, $1C, $10
	dc.b $F8, $5, $0, $0, $20
	dc.b $F8, $5, $0, $3E, $30
DATAQ72E9ONBW4_1: dc.b $6
	dc.b $F8, $5, $0, $36, $D0
	dc.b $F8, $5, $0, $0, $E0
	dc.b $F8, $5, $0, $3E, $F0
	dc.b $F8, $5, $0, $3E, $0
	dc.b $F8, $5, $0, $10, $10
	dc.b $F8, $5, $0, $C, $20
DATAQ72E9ONBW4_2: dc.b $6
	dc.b $F8, $D, $21, $4A, $B0
	dc.b $F8, $1, $21, $62, $D0
	dc.b $F8, $9, $1, $64, $18
	dc.b $F8, $D, $1, $6A, $30
	dc.b $F7, $4, $0, $6E, $CD
	dc.b $FF, $4, $18, $6E, $CD
DATAQ72E9ONBW4_3: dc.b $7
	dc.b $F8, $D, $21, $5A, $B0
	dc.b $F8, $D, $20, $66, $D9
	dc.b $F8, $1, $21, $4A, $F9
	dc.b $F7, $4, $0, $6E, $F6
	dc.b $FF, $4, $18, $6E, $F6
	dc.b $F8, $D, $FF, $F0, $28
	dc.b $F8, $1, $1, $70, $48
DATAQ72E9ONBW4_4: dc.b $7
	dc.b $F8, $D, $21, $52, $B0
	dc.b $F8, $D, $20, $66, $D9
	dc.b $F8, $1, $21, $4A, $F9
	dc.b $F7, $4, $0, $6E, $F6
	dc.b $FF, $4, $18, $6E, $F6
	dc.b $F8, $D, $FF, $F8, $28
	dc.b $F8, $1, $1, $70, $48
DATAQ72E9ONBW4_5: dc.b $0
DATAQ72E9ONBW4_6: dc.b $0
DATAQ72E9ONBW4_7: dc.b $0
DATAQ72E9ONBW4_8: dc.b $0
	even