; ================================================================================
; Sprite Mappings - generated by Flex 2 Sat Nov 23 2019 22:58:33 GMT-0500 (Eastern Standard Time)
; ================================================================================

DATASWQDLVO9PFM:
	dc.w DATASWQDLVO9PFM_0-DATASWQDLVO9PFM, DATASWQDLVO9PFM_1-DATASWQDLVO9PFM
	dc.w DATASWQDLVO9PFM_2-DATASWQDLVO9PFM, DATASWQDLVO9PFM_3-DATASWQDLVO9PFM
	dc.w DATASWQDLVO9PFM_4-DATASWQDLVO9PFM, DATASWQDLVO9PFM_5-DATASWQDLVO9PFM
	dc.w DATASWQDLVO9PFM_6-DATASWQDLVO9PFM, DATASWQDLVO9PFM_7-DATASWQDLVO9PFM
	dc.w DATASWQDLVO9PFM_8-DATASWQDLVO9PFM
DATASWQDLVO9PFM_0: dc.b $D
	dc.b $F8, $5, $0, $8, $90
	dc.b $F8, $5, $0, $1C, $A0
	dc.b $F8, $5, $0, $0, $B0
	dc.b $F8, $5, $0, $32, $C0
	dc.b $F8, $5, $0, $3E, $D0
	dc.b $F8, $5, $0, $10, $F0
	dc.b $F8, $5, $0, $2A, $0
	dc.b $F8, $5, $0, $10, $10
	dc.b $F8, $5, $0, $3A, $20
	dc.b $F8, $5, $0, $0, $30
	dc.b $F8, $5, $0, $26, $40
	dc.b $F8, $5, $0, $C, $50
	dc.b $F8, $5, $0, $3E, $60
DATASWQDLVO9PFM_1: dc.b $6
	dc.b $F8, $D, $21, $4A, $B0
	dc.b $F8, $1, $21, $62, $D0
	dc.b $F8, $9, $1, $64, $18
	dc.b $F8, $D, $1, $6A, $30
	dc.b $F7, $4, $0, $6E, $CD
	dc.b $FF, $4, $18, $6E, $CD
DATASWQDLVO9PFM_2: dc.b $7
	dc.b $F8, $D, $21, $52, $B0
	dc.b $F8, $D, $20, $66, $D9
	dc.b $F8, $1, $21, $4A, $F9
	dc.b $F7, $4, $0, $6E, $F6
	dc.b $FF, $4, $18, $6E, $F6
	dc.b $F8, $D, $FF, $F8, $28
	dc.b $F8, $1, $1, $70, $48
DATASWQDLVO9PFM_3: dc.b $0
DATASWQDLVO9PFM_4: dc.b $4
	dc.b $F8, $D, $9F, $D1, $B0
	dc.b $F8, $D, $9F, $D9, $D0
	dc.b $F8, $1, $9F, $E1, $F0
	dc.b $F8, $6, $1F, $E3, $40
DATASWQDLVO9PFM_5: dc.b $4
	dc.b $F8, $D, $9F, $D1, $B0
	dc.b $F8, $D, $9F, $D9, $D0
	dc.b $F8, $1, $9F, $E1, $F0
	dc.b $F8, $6, $1F, $E9, $40
DATASWQDLVO9PFM_6: dc.b $3
	dc.b $F8, $D, $9F, $D1, $B0
	dc.b $F8, $D, $9F, $D9, $D0
	dc.b $F8, $1, $9F, $E1, $F0
DATASWQDLVO9PFM_7: dc.b $C
	dc.b $F8, $5, $0, $3E, $9C
	dc.b $F8, $5, $0, $36, $AC
	dc.b $F8, $5, $0, $10, $BC
	dc.b $F8, $5, $0, $8, $CC
	dc.b $F8, $1, $0, $20, $DC
	dc.b $F8, $5, $0, $0, $E4
	dc.b $F8, $5, $0, $26, $F4
	dc.b $F8, $5, $0, $3E, $14
	dc.b $F8, $5, $0, $42, $24
	dc.b $F8, $5, $0, $0, $34
	dc.b $F8, $5, $0, $18, $44
	dc.b $F8, $5, $0, $10, $54
DATASWQDLVO9PFM_8: dc.b $F
	dc.b $F8, $5, $0, $3E, $88
	dc.b $F8, $5, $0, $32, $98
	dc.b $F8, $5, $0, $2E, $A8
	dc.b $F8, $1, $0, $20, $B8
	dc.b $F8, $5, $0, $8, $C0
	dc.b $F8, $5, $0, $18, $D8
	dc.b $F8, $5, $0, $32, $E8
	dc.b $F8, $5, $0, $42, $F8
	dc.b $F8, $5, $0, $42, $10
	dc.b $F8, $5, $0, $1C, $20
	dc.b $F8, $5, $0, $10, $30
	dc.b $F8, $5, $0, $2A, $40
	dc.b $F8, $5, $0, $0, $58
	dc.b $F8, $5, $0, $26, $68
	dc.b $F8, $5, $0, $26, $78
	even